### ISSUE TITLE
Desativar o botão de anexo no RocketChat

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#102]
No momento a Taís não suporta processamento de arquivos, além de não termos uma necessidade real para isso.

Melhor desativar para evitar confusão e problemas
- [ ] Adicionar no script a remoção do **habilitar upload**.

--------
**Critérios de aceitação**
- [x] A janela de chat no ambiente DEV não mostra o botão de anexar arquivos.

**Comment by MatheusFaria** [comment]
Duplicada na #135
