### ISSUE TITLE
Trocar "Tu" por "Você" nos balões de chat

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#103]
Na maior parte do país as pessoas não tem o hábito de usar o pronome tu. Melhor usar uma formulação mais comum, como "Você".

--------
**Critérios de aceitação**
- [ ] Os balões enviados pelo usuário são identificados como "Você".
- [ ] A mudança pode ser visualizada por todos no ambiente DEV.

**Comment by rodmaia** [comment]
Mudamos o idioma do Rocket para "Default" assim, ela usa o idioma do navegador e resolve temporariamente o problema

**Comment by LeoSilvaGomes-zz** [comment]
Sabendo que não temos poder para alterar algumas informações de algumas plataformas, chegamos ao um ponto onde essa issue se dará como fechada, mesmo que não resolvida, pois não temos como alterar essa informação já que isso a cargo da RocketChat
