### ISSUE TITLE
Corrigir mensagem do "is typing"

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#104]
A mensagem atual mostra "**rouana** está a escrever". Primeiro, a mensagem deve mencionar a Taís e segundo deve usar a formulação de português brasileiro "está escrevendo".

-------
**Critérios de aceitação**
- [ ] Ver a mensagem "**Taís** está escrevendo" durante uma sessão de chat no ambiente DEV

**Comment by arthurTemporim** [comment]
Dependemos da Rocket.Chat para fazer a atualização da língua.

**Comment by MatheusFaria** [comment]
Parece que nas Settings > General o Rocket deixa fazer traduções personalizadas, podemos usar pra resolver este problema

**Comment by joenio** [comment]
abriram uma issue recentemente no repositório do Rocket.Chat relatando esse mesmo problema, o autor da issue sugere o caminho para correção, precisamos testar e se funcionar corretamente sem efeitos colaterais indesejados enviar um pull-request com a correção para a galera do rocket.

https://github.com/RocketChat/Rocket.Chat/issues/13305

**Comment by MatheusMiranda** [comment]
> abriram uma issue recentemente no repositório do Rocket.Chat relatando esse mesmo problema, o autor da issue sugere o caminho para correção, precisamos testar e se funcionar corretamente sem efeitos colaterais indesejados enviar um pull-request com a correção para a galera do rocket.
> 
> [RocketChat/Rocket.Chat#13305](https://github.com/RocketChat/Rocket.Chat/issues/13305)

A issue #103 está relacionada ao mesmo problema.
