### ISSUE TITLE
Melhorar mensagem de início automático

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#105]
A mensagem atual "Olá, posso te ajudar?" induz respostas que a Taís não está preparada para reagir como: "sim", "pode", "não sei", etc.

Precisamos identificar algo que seja curto e que induza as pessoas a iniciar o fluxo de saudação. Devemos evitar que a pessoa entre em um assunto mais complexo. Um exemplo a evitar:
- Olá, tudo bem?
- Não, estou com um problema....

---------
**Critérios de aceitação**
- [x] A Taís continua sendo a primeira a falar.
- [x] A nova msg inicial induz a pessoa a fazer uma saudação de forma implícita (sem mostrar uma instrução).
- [x] A nova msg induz à uma resposta curta e específica .

**Comment by palomacmamede** [comment]
@rodmaia2099  ótimo, posso fazer essa quest amanhã?
