### ISSUE TITLE
Especificar atividades de monitoramento do beta

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#108]
As necessidades gerais de monitoramento foram definidas [aqui na wiki](https://github.com/lappis-unb/rouana/wiki/Plano-de-comunica%C3%A7%C3%A3o-com-beta-testers).

- [x] Validar necessidades gerais e identificar elementos faltantes
- [x] Definir responsáveis por cada tarefa de monitoramento
- [x] Identificar ferramentas e ambientes necessários
- [x] Documentar detalhes das atividades
- [x] Avaliar a necessidade de hospedar o beta fora do LAPPIS. (queda de energia/internet)
-------
**Critérios de aceitação**
- [x] Os membros da equipe sabem o que fazer, como fazer e quando fazer
- [x] As pessoas envolvidas no monitoramento sabem como comunicar problemas para a equipe
- [x] O processo está documentado e acessível, e não apenas na cabeça de alguém

**Comment by arthurTemporim** [comment]
O documento elaborado para a solução desta issue é esse:
[Processo](https://github.com/lappis-unb/rouana/wiki/Processo-de-Monitoramento-do-Beta)

**Comment by MatheusFaria** [comment]
- Timeout no gitlab durante o deploy
- Bot esta `offline` (deixar tutorial para o rancher ou ponteiro para uma pessoa)

**Comment by MatheusFaria** [comment]
Sobre o **beta**

Iremos migrar para o ambiente do minc assim que a máquina de produção de lá estiver disponível.

**Comment by arthurTemporim** [comment]
@rodmaia2099 verifique por favor o [documento](https://github.com/lappis-unb/rouana/wiki/Processo-de-Monitoramento-do-Beta) pra saber se ele está de acordo com o esperado
