### ISSUE TITLE
Documentar resultado do questionário do Refinamento

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#110]
O questionário está em: https://docs.google.com/forms/d/1FuZRYKmR69JTSycZPbMsLkDD8U2m2C-2NUhn51Vs2xw/edit

É preciso documentar os resultados de forma permamente na wiki.

------

**Critérios de aceitação**

- [x] Os gráficos e a análise dos resultados estão disponíveis na Wiki
- [x] O conteúdo é facilmente compreensível por qualquer pessoa envolvida com o projeto.

**Comment by rodmaia2099** [comment]
Questionário compilado em: https://github.com/lappis-unb/rouana/wiki/Tais-Homologa%C3%A7%C3%A3o-v2.0
