### ISSUE TITLE
Dump de Perguntas e Respostas

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#115]
- [X] Extrair todas as perguntas e suas relativas respostas.
- [x] Colocar o resultado na Wiki
- [ ] Gerar PDF com resultado para a aprovação do MinC

**Comment by arthurTemporim** [comment]
A primeira versão do arquivo com pergunta e respostas está [aqui](https://docs.google.com/document/d/1RR_cT6GB_WpqPkLKb3KxFHfNqdJ0Y1n3NGWwxNgh6kY/edit#heading=h.31ftzi5z8rhl)

**Comment by rodmaia** [comment]
A versão mais atualizada está aqui: 
https://github.com/lappis-unb/rouana/wiki/Mensagens-da-Ta%C3%ADs

**Comment by rodmaia** [comment]
Acho que podemos enviar diretamente o link da Wiki, assim, as pessoas sempre vão ler a versão mais atualizada do documento.
