### ISSUE TITLE
Resolução de problemas com respostas incoerentes no fluxo

### ISSUE THREAD

**Issue by palomacmamede** [lablivre-unb/tais#126]
- [ ] revisar colocações de palavras parecidas entre as intents 

- [x] observar quais as respostas incoerentes se repetem e em quais intents caem

- [ ] propor solução de melhoria das intents

- [ ] testar melhorias

**Comment by palomacmamede** [comment]
[Compilação de Sinônimos](https://docs.google.com/document/d/1ME5hdWTsdV8GXgLoTmzcRBI_p-W_VQWMZKI1HuX_gJc/edit#)

**Comment by palomacmamede** [comment]
[Especulações Sobre as Incoerências do Fluxo](https://docs.google.com/document/d/1nFba6uRAW3CuMg38_g8fn6FaUIFNSRkdxKfv5bw9L5M/edit)

**Comment by MatheusFaria** [comment]
As atividades não foram completadas. #152
