### ISSUE TITLE
Monitorar as instâncias oficiais da Taís

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#129]
No momento a Taís tem duas instâncias oficiais. A versão Beta, voltada para um grupo fechado de produtores culturais e servidores do MinC, e a versão de Produção, aberta para toda a população no portal da Lei Rouanet.

Precisamos criar a prática de monitorar essas instâncias para garantir que:
* o bot **está funcionando** - está o maior tempo possível no ar sem interrupções e que as interrupções que acontecerem foram programadas pela equipe;
* o bot está funcionando **corretamente** - está funcionando da forma que foi projetada para funcionar (seja essa forma certa ou errada) sem apresentar nenhum comportamento anormal;
* estamos capturando **feedback e hábitos de conversa** dos usuários - sabemos como as pessoas estão conversando com a Taís, a precisão com que a Taís está respondendo, quais tópicos ou formas de perguntar não estão sendo identificadas pela Taís e o que as pessoas estão achando de tudo isso.

Para isso já estamos fazendo algumas dessas atividades manualmente. Isso vai nos ensinar o que precisamos monitorar de fato e como devemos fazê-lo.

A partir disso, devemos automatizar essa prática. O que inclui adaptar uma ferramenta de analytics do mercado para usar com a Taís.

**Comment by rodmaia** [comment]
Nosso **plano A** para o analytics é usar Kibana + Elastic Search para gerar. O  **plano B** é implementar uma aplicação com ML para ler os logs "manualmente".

**Comment by LeoSilvaGomes-zz** [comment]
Essa issue tinha como objetivo estabelecer algumas métricas para a conclusão de que o bot da Tais está em um estado bom, tanto de utilização quanto de manutenção. Neste vies podemos concluir que já temos dados suficientes para concluir os requisitos *funcionamento*, *hábitos de conversa*. Utilizando tanto o Kibana quanto o Elastic Search para nos ajudar a tirar informações da Tais em geral.
