### ISSUE TITLE
Evoluir o motor de treinamento e inteligência da Taís

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#130]
A Taís precisa evoluir a capacidade de responder com maior precisão os tópicos que já estão mapeados atualmente.

Precisamos refinar a modelagem do conhecimento da assistente virtual e melhorar a competência técnica de toda a equipe nesse tipo de atividade.

Reestruturar histórias e intenções de um jeito em que fique melhor para a intepretação via Rasa.

**Comment by RochaCarla** [comment]
ja foi resolvido esse problema
