### ISSUE TITLE
Ampliar conteúdo da Taís em beta-teste

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#132]
Em paralelo à evolução técnica da Taís, precisamos ampliar a base de conhecimento dela.

Os novos conteúdos vão ter duas fontes:

1. Sugestões da SEFIC
     * Os técnicos da SEFIC vão mapear tópicos para que a Taís dê a definição
     * Apenas definições com pouca profundidade na resposta
1. Feedback do processo (refinamento e homologação)
     * Nós vamos mapear tópicos que as pessoas solicitaram mas que a Taís não é capaz de responder (diferente de tópicos que ela consegue responder, mas simplesmente respondeu errado)
     * Vamos repassar essa nova lista de tópicos para a SEFIC e decidir em conjunto quais serão de fato incorporados

**Comment by RochaCarla** [comment]
ja foi resolvida em outras issues
