### ISSUE TITLE
Melhorar configuração do ambiente de Produção

### ISSUE THREAD

**Issue by MatheusMiranda** [lablivre-unb/tais#135]
Automatizar as segintes atividades:

- [x] Colocar prefix nas URLs do Django; configurar para o django puxe o prefix de variavel de env
- [x] Credentials: Setar senhas via variavel de ambiente
- [x] ~Idioma, Trigger~
- [x] Remover o attach

**Criterios de Aceitação**
- [x] Levantar o ambiente com senhas seguras via env var
- [x] Produção configurada sem alterações nos arquivos fontes

**Comment by rodmaia** [comment]
Feito também:
* Remoção da configuração automática do webhook que eliminou erros no log do RocketChat
* Adicionado prefixo nas URLs do Django para controlar rotas do Beta no MinC e da Prod.


Falta fazer (mapeado em #184):
* Melhorar variáveis de ambiente para serem auto-explicativas para qualquer pessoa
