### ISSUE TITLE
Máquina de Produção

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#139]
Acertar com a equipe da CGTIC um ambiente separado da homolagação pra colocar a Taís.

**Comment by joenio** [comment]
segue abaixo o email enviado ao Christian solicitando este novo ambiente, aguardando resposta.

```
Date: Sat, 22 Sep 2018 12:11:37 -0300
From: Joenio Costa <joenio@joenio.me>
To: christian.miranda@cultura.gov.br
Subject: Nova VM para separar ambientes de homologacao e producao
User-Agent: Mutt/1.10.1 (2018-07-13)

Oi Christian,

Em nome do Lappis solicito mais um servidor para ser utilizado como ambiente de
produção, atualmente estamos utilizando a VM 192.168.15.16 para isso, mas num
futuro próximo essa VM será reservada para homologação e migraremos os serviços
para a nova máquina.

Os requisitos e configurações são os mesmos da máquina atual.

Obrigado,
--
Joenio Costa
http://joenio.me
```

**Comment by rodmaia** [comment]
@joenio tivemos alguma atualização disso?

**Comment by joenio** [comment]
sim, tivemos, christian encaminhou a solicitação para o time de suporte do MinC no dia 05 (sexta-feira), aguardando o time de suporte entrar em contato para dar encaminhamento.

**Comment by joenio** [comment]
em 15 de outubro cobrei resposta ao minc, eles ainda não tinham efetuado a solicitação, en 17 de outubro (quarta-feira) christian reforçou o pedido cobrando ao suporte do minc, email do christian abaixo.

```
Date: Wed, 17 Oct 2018 07:24:05 -0300 (BRT)
From: Christian Moryah Contiero Miranda <***>
To: ***
Subject: Re: Nova VM para separar ambientes de homologacao e producao
X-Mailer: Zimbra 8.8.9_GA_3006 (ZimbraWebClient - FF62 (Linux)/8.8.9_GA_3006)

   Pessoal, alguma resposta sobre essa demanda ?
   Time do Lappis está aguardando.
   Obrigado.

   Christian Moryah Contiero Miranda
   Analista em Tecnologia da Informação
   Coordenação-Geral de Infraestrutura Tecnológica
   Subsecretaria de Gestão Estratégica
   Secretaria Executiva
   Ministério da Cultura
```

**Comment by joenio** [comment]
Acabei de enviar um email para o MinC pedindo notícias sobre essa demanda.

**Comment by joenio** [comment]
Carlos Eduardo Lopes Prazeres (MinC) atendeu nossa solicitação em 27/Nov/2018, mas o acesso não está ok ainda, troquei alguns emails solicitando detalhes de acesso, acabei de enviar novamente um email pois apesar de terem disponibilizado a máquina não estou conseguindo acesso via VPN.
