### ISSUE TITLE
Gerar métricas no Kibana

### ISSUE THREAD

**Issue by MatheusFaria** [lablivre-unb/tais#146]
Métricas necessárias:
* Intents que ela não conseguiu responder (no tempo)
	* Listar todas as perguntas recebidas que geraram erros
* Gráfico de intents vs. utter -> mapeia utters respondidas errado
	* Detectar anomalias (pontos fora da curva)

**Comment by rodmaia** [comment]
@RochaCarla @MatheusFaria parece que a versão mais nova do Kibana vem com dados de exemplo para testar a ferramenta: https://www.elastic.co/blog/kibana-6-4-0-released.

Será que isso pode facilitar a nossa vida de testar sem precisar colocar esforço em um stack nosso do elastic search?
