### ISSUE TITLE
Consolidar todas as análises de conteúdo na wiki

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#152]
Fizemos várias atividades de análise tanto do refinamento quanto do beta teste (inserir vírgula para o @MatheusFaria) mas as informações estão dispersas nos seguintes documentos:

* https://docs.google.com/spreadsheets/d/1hb6chITZdLfqKfccMHMlTHHJ6645smdouFg72dwULTM/edit#gid=1927489573 (apenas as planilhas compiladas - verdes)
* https://docs.google.com/document/d/1nFba6uRAW3CuMg38_g8fn6FaUIFNSRkdxKfv5bw9L5M/edit
* https://docs.google.com/document/d/1ME5hdWTsdV8GXgLoTmzcRBI_p-W_VQWMZKI1HuX_gJc/edit#

**Tarefas**

- [x] Tirar os resultados das análises dos diferentes documentos e colar nas páginas certas da Wiki

**Critérios de aceitação**

- [x] Todos os resultados de análise foram passados para a Wiki e os documentos originais podem ser apagados.
- [x] A equipe pode realizar discussões de mudança de conteúdo olhando apenas para a wiki.

**Comment by rodmaia** [comment]
Pessoal, vamos priorizar a consolidação dos tópicos que a Taís ainda não trata para podermos repassar isso pro MinC antes do final da sprint.

**Comment by rodmaia** [comment]
> **Na #163, @palomacmamede disse:**
> Sobre dificuldade/Impedimentos: a separação de temas da compilação de sinônimos tem várias perguntas que não possuem temas das intents que já temos. Preciso de ajuda nessa parte para otimizar o trabalho. (:

@palomacmamede acho que não entendi o problema 😃 Se as perguntas nos sinônimos não tem conteúdo previsto nas intents existentes então será que são sinônimos mesmo?

**Comment by arthurTemporim** [comment]
As mensagens que o bot ainda não consegue responder e que podem ser adicionadas no futuro estão documentadas neste documento:

[Novos tópicos para inserir no futuro](https://github.com/lappis-unb/rouana/wiki/Novos-t%C3%B3picos-para-inserir-no-futuro)

Os sinônimos extraidos estão documentados no seguinte arquivo:

[Sinônimos de tópicos existentes](https://github.com/lappis-unb/rouana/wiki/Sin%C3%B4nimos-de-t%C3%B3picos-existentes)

**Comment by arthurTemporim** [comment]
Ainda falta documentar ou avaliar a necessidade desse documento:

[Intents classificados errado](https://github.com/lappis-unb/rouana/wiki/Intents-classificados-errado)

O preenchimento desse documento é muito trabalhoso e o ganho muito pequeno tendo em mente que as `stories`, `intents`, `utters` e quantidade de `epochs` estão em constante mudança e cada um desses tópicos interferem diretamente na classificação da `intent`. A nova versão da Taís também é bem diferente da versão do teste, de forma que levantar todos os problemas de classificação da versão antiga não será aproveitado em nada na nova versão do bot.

**Comment by arthurTemporim** [comment]
Em relação aos [tópicos complicados](https://github.com/lappis-unb/rouana/wiki/T%C3%B3picos-complicados-para-avaliar) esse documento deve ser elaborado em grupo, inicialmente tendo como artefato de entrada [novos tópicos](https://github.com/lappis-unb/rouana/wiki/Novos-t%C3%B3picos-para-inserir-no-futuro) e depois atualizar de acordo com a demanda.

**Comment by rodmaia** [comment]
Terminei de passar as análises de sinônimos que a Paloma e a Gabi fizeram para a Wiki.

Também passei os [Intents classificados errado](https://github.com/lappis-unb/rouana/wiki/Intents-classificados-errado) mas não coloquei as intents esperadas. @MatheusMiranda essa task é tua e a @palomacmamede pode te orientar.

@palomacmamede também joguei os tópicos complicados. Você pode revisar aqueles DOCS que você tinha criado para ter certeza que a gente migrou tudo?

**Comment by palomacmamede** [comment]
@rodmaia2099  acredito que tudo foi migrado corretamente (:

**Comment by rodmaia** [comment]
Falta documentar as intents esperadas quando a Taís entregou intents erradas
