### ISSUE TITLE
Organizar sarau de histórias

### ISSUE THREAD

**Issue by MatheusFaria** [lablivre-unb/tais#155]
Elaborar um encontro para disseminação do conhecimento sobre elaboração de histórias no rasa, seguindo a nova estrutura da `develop`.

**Tarefas**

- [x] Preparar uma branch para todos utilizarem como base
- [x] Limitar o conteudo que a Tais sabe falar
- [x] Marcar dia e local do sarau
- [x] Preparar as apresentações
- [x] Configurar ambientes de todos antes do evento
- [x] Realizar evento

**Critérios de aceitação**

- [x] Histórias implementadas e funcionando

**Comment by MatheusFaria** [comment]
Planilha de horários: https://docs.google.com/spreadsheets/d/1h6eTIxqKjcYncYAE-GyecuD5Fmmh26QdZv0r_Rz2L8c/edit#gid=0

**Comment by RochaCarla** [comment]
O Sarau foi organizado dia 01/10.. a branch usada para o trabalho foi v2.1.0 
Foram realizadas as seguintes atividades

- [x] Apresentação do que foi feito, com o Rasa e as conversas 

- [x] Pipeline NLU 

- [x] Atualização do pipeline NLU usando Tensorflow

- [x] Entendendo as policies   -  policies=[KerasPolicy(),MemoizationPolicy(max_history=4)]

- [x] Testamos 2 estratégias - 1) Criar histórias com até 3 intents todos os domínios (branch tempoloma). 2) Preencher historias c todas as etapas até chegar nas folhas

**Comment by RochaCarla** [comment]
Encaminhamentos:

- [ ] @gabibguedes @KahCosta vão evoluir as estratégias, a partir da branch Tempoloma, documentar na wiki a avaliação das duas estratégias
