### ISSUE TITLE
Criar endpoint de setPresence na API do Rocket.Chat

### ISSUE THREAD

**Issue by MatheusFaria** [lablivre-unb/tais#156]
Precisamos de um endpoint de setPresence para manter o bot online e abandonar o connector DDP

**Tarefas**

- [ ] Criar endpoint de setPresence na API do Rocket.Chat

**Critérios de aceitação**

- [ ] Conseguir setar a presença via API do Rocket

**Comment by RochaCarla** [comment]
resolvido !
