### ISSUE TITLE
Problema no deploy da develop

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#159]
Após push na branch `develop` o pipeline do gitlab-ci foi executado, isso não deveria acontecer.

**Tarefas**

- [ ] Retirar a execução do pipeline quando ocorrem pushs na `develop`;

**Critérios de aceitação**

- [ ] Garantir que o ambiente de dev só vai ser atualizado com mudanças na master.

**Comment by rodmaia** [comment]
Duplicada de #151
