### ISSUE TITLE
Relatorio de Acompanhamento 04 

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#160]
Fazer o relatório de acompanhamento do trabalho realizado pela equipe entre julho 2018 - setembro 2018.

**Tarefas**

- [x] Listar as principais funcionalidades desenvolvidas no período

- [ ] Descrever, de forma sucinta, os principais objetivos da equipe no período

- [ ] Linkar documentação da wikii relacionada às atividades identificadas nas tarefas acima

**Critérios de aceitação**

- [x] Ter uma página markdown com o conteúdo

- [ ] O conteúdo refletir o trabalho realizado no período

**Comment by MatheusFaria** [comment]
Qual o prazo de entrega?

**Comment by MatheusFaria** [comment]
Comecei a documentar aqui
https://github.com/lappis-unb/rouana/wiki/Relat%C3%B3rio-de-Entrega-Julho-a-Setembro-2018

Falta pescar os anexos e mais atividades desenvolvidas

**Comment by MatheusFaria** [comment]
Talvez seria bom colocar os relatórios de análise. Mas não sei onde estão @RochaCarla @rodmaia2099

**Comment by rodmaia** [comment]
Quais relatórios de análise @MatheusFaria ?

**Comment by MatheusFaria** [comment]
@rodmaia2099 os enviados para o MinC

**Comment by MatheusFaria** [comment]
@RochaCarla pode dar uma olhada?
