### ISSUE TITLE
Estudar automatização de Testes de Aceitação

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#162]
Implementar testes automatizados para a Taís.

**Tarefas:**
- [x] Dockerizar bot com `--enable_api`
- [x] Dockerizar script de testes
- [x] Documentar
- [ ] ~Criar vários testes~

**Comment by arthurTemporim** [comment]
Foi implementado testes de aceitação utilizando `pytest`.
É necessário executar o teste após executar o bot com o comando `make run-test`. Para testar `pytest test/test.py`

**Comment by arthurTemporim** [comment]
Done with #296
