### ISSUE TITLE
Review 01/10/2018 

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#163]
Atualização do status da review metade da sprint.

Atualizar nos comentários:

- [ ] Número das issues fechadas (se teve processo de PR + validação) 

- [ ] Status das issues remanescentes (registrar problemas encontrados, se necessário, issues novas abertas)

- [ ] Registrar alguma dificuldade/impedimento para conseguir fechar todas as issues alocadas pra cada membro essa semana (até o final da sprint)

**Comment by palomacmamede** [comment]
Sobre dificuldade/Impedimentos: a separação de temas da compilação de sinônimos tem várias perguntas que não possuem temas das intents que já temos. Preciso de ajuda nessa parte para otimizar o trabalho. (:

**Comment by RochaCarla** [comment]
Li alguns textos interessantes para entender melhor o Rasa. Algumas leituras que valem a pena:

- [x] Como deixar de forma explícita que intento são similares - https://blog.rasa.com/supervised-word-vectors-from-scratch-in-rasa-nlu/

- [x] Pipeline NLU (vale a pena estudar) - https://rasa.com/docs/nlu/choosing_pipeline/

**Comment by palomacmamede** [comment]
[Documentar pipeline de análise #140](https://github.com/lappis-unb/rouana/issues/140)
Hoje mesmo o @MatheusFaria e eu, vamos escrever como foi o método da pesquisa.

**Comment by brunapinos** [comment]
Manter o env igual o da master #150 
Ontem eu e o @MatheusMiranda começamos a fazer o merge, mas alguns arquivos o próprio git escolhe as alterações, o que acaba por retirar mudanças essenciais. Desse modo, investigamos o funcionamento do rebase, que acabou por acontecer a mesma coisa.
Amanhã vamos tentar novamente, e se der errado vamos modificar na mão mesmo.

Remover menu de contexto #123
Quarta fizemos as mudanças e mandamos os emails aos beta-testers, porém colocar a página de manutenção está pendente. Só falta a parte do Django.

Deixar domain.yml enxuta #77
Ainda não trabalhei com a @gabibguedes,  então peço que ela atualize sobre o andamento da issue.

**Comment by arthurTemporim** [comment]
A issue #108 **Especificar atividades de monitoramento do beta** está finalizada

**Comment by arthurTemporim** [comment]
A issue #152 **Consolidar todas as análises de conteúdo na wiki**  está em andamento.

**Comment by gabibguedes** [comment]
Deixar domain.yml enxuta #77 
Comecei a estudar sobre o rasa addons mas ainda não pareei com a @brunapinos, ainda temos que ver como fazer o dispatcher.

Consolidar todas as análises de conteúdo na wiki #152 
Eu e o @arthurTemporim falamos com a @palomacmamede  para entender melhor os documentos feitos na sprint passada e foi feito os comentários para guiar os preenchimentos das tabelas de markdown

**Comment by KahCosta** [comment]
A issue #135 Melhorar configuração de ambiente está finalizada.
