### ISSUE TITLE
TAIS entrando em momentos errados em 'denuncia'

### ISSUE THREAD

**Issue by MatheusMiranda** [lablivre-unb/tais#167]
**Tarefas**

- [x] Investigar porquê a TAIS está entrando em 'denuncia' de forma incorreta.

**Critérios de aceitação**

- [x] Melhorar o fluxo para que os usuário não entrem no subfluxo de curiosidades por acidente.
- [x] Resultados foram documentados, de acordo com #173.

**Comment by MatheusMiranda** [comment]
Eu e a @gabibguedes investigamos as conversas do ambiente de homologação para tentar descobrir o motivo do problema.
Uma das causas que descobrimos foi que, devido às interações erradas dos beta testers, a TAIS acabava entrando no fluxo de curiosidades, mesmo que o usuário não tivesse esta intenção. E como ela estava dentro do fluxo de curiosidades, sempre que o usuário fazia alguma pergunta iniciada com 'como...' ela identificava a intenção de denúncia.

**Comment by gabibguedes** [comment]
As intents de denuncia possuem muitos exemplos de "como faço" e "um projeto" as perguntas que entraram nessa intent errada continham essas palavras

**Comment by arthurTemporim** [comment]
Verifiquem o `pipeline` de execução da Tais para identificar como funcionam as `intents`.

 [Pipeline](https://github.com/lappis-unb/rouana/blob/develop/rouana/config.yml)

**Comment by palomacmamede** [comment]
O grande problema de retirar os pronomes interrogativos das intents é que algumas intents precisam destes pronomes o que possivelmente ocasionaria outro tipo de problema, temos que descobrir se é um problema de código, por exemplo, temos que estudar melhor o uso das entities, e se isso alteraria a classificação das intents.

**Comment by palomacmamede** [comment]
Estamos melhorando o formato das intents, criando um padrão eficiente para balanceá-las, e em breve poderemos testar a sua eficácia!

**Comment by arthurTemporim** [comment]
O último critério de aceitação foi movido para #203.
