### ISSUE TITLE
Monitorar a Taís em Beta e em Prod

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#169]
[Esta é uma issue contínua] À cada semana, uma pessoa da equipe ficará responsável por fazer um teste rápido da Taís para detectar problemas. Também ficará responsável por analisar os fluxos de conversa e extrair dados para o mapeamento de [conteúdo da Taís](https://github.com/lappis-unb/rouana/wiki#conte%C3%BAdo-da-ta%C3%ADs).

Se existir algum problema, tente resolver de acordo com as instruções do [Processo de Monitoramento](https://github.com/lappis-unb/rouana/wiki/Processo-de-Monitoramento-do-Beta).  **Caso tenha conseguido resolver**, comunique à equipe para podermos saber o que aconteceu e te dar os parabéns. **Caso não tenha conseguido**, avise à equipe o mais rápido possível para tentarmos outras formas de solução.

**Tarefas**

- [ ] **1.** 1x ao dia: [testar a Taís manualmente](https://github.com/lappis-unb/rouana/wiki/Processo-de-Monitoramento-do-Beta) no Beta
- [ ] **2.** 1x ao dia: [testar a Taís manualmente](https://github.com/lappis-unb/rouana/wiki/Processo-de-Monitoramento-do-Beta) em Prod
- [ ] **3.** 1x ao dia: acessar o tais.betateste@gmail.com e responder as dúvidas dos beta-testers. Peça ajuda ao @rodmaia2099 ou à @RochaCarla.
- [ ] **4.** 1x por semana: analisar os logs de **todas as novas conversas** do Beta e extrair [novos tópicos para inserir no futuro](https://github.com/lappis-unb/rouana/wiki/Novos-t%C3%B3picos-para-inserir-no-futuro), [intents classificados errado](https://github.com/lappis-unb/rouana/wiki/Intents-classificados-errado) e [sinônimos de tópicos existentes](https://github.com/lappis-unb/rouana/wiki/Sin%C3%B4nimos-de-t%C3%B3picos-existentes).
- [ ] **5.** 1x por semana: analisar os logs de 10 as conversas de Prod e extrair [novos tópicos para inserir no futuro](https://github.com/lappis-unb/rouana/wiki/Novos-t%C3%B3picos-para-inserir-no-futuro), [intents classificados errado](https://github.com/lappis-unb/rouana/wiki/Intents-classificados-errado) e [sinônimos de tópicos existentes](https://github.com/lappis-unb/rouana/wiki/Sin%C3%B4nimos-de-t%C3%B3picos-existentes).
- [ ] **6.** Efetuar as atividades **4** e **5** de acordo com a [documentação](https://github.com/lappis-unb/rouana/wiki/Pipeline-de-An%C3%A1lise-Manual)
- [ ] **7.** **Abrir issues para problemas encontrados**
- [ ] **8.** **Documentar na issue os resultados das tarefas realizadas**

**Critérios de aceitação**

- [ ] A equipe do bot deve descobrir problemas com a Taís antes dos usuários.
- [ ] A equipe do bot sabe quais intents estão dando problemas e quais sinônimos precisam ser alimentados.

**Comment by arthurTemporim** [comment]
Na Sprint 14, apenas a verificação se o bot está online foi feita tanto em produção quanto em beta.
Fazer análise das conversas do período de 08/10 à 22/10.
