### ISSUE TITLE
Melhorar estado "em manutenção" no beta

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#170]
(Continuação de #123)
Criamos um procedimento para colocar o beta em estado de manutenção 1x por semana. 

**Tarefas**
- [x] Mostrar mensagem de manutenção ao invés dos campos de login 
- [x] Subir para Beta e testar
- [x] Documentar passo-a-passo de como ativar o modo de manutenção na [Wiki](https://github.com/lappis-unb/rouana/wiki/Processo-de-Monitoramento-do-Beta)

**Critérios de aceitação**

- [x] Qualquer pessoa da equipe consegue colocar o beta em manutenção apenas olhando o passo-a-passo.
- [x] Beta-testers não precisam fazer login para saber que a Taís está em manutenção

**Comment by MatheusMiranda** [comment]
Passos para ativar/desativar a página de manutenção: https://github.com/lappis-unb/rouana/wiki/Manuten%C3%A7%C3%A3o-Tais

**Comment by rodmaia** [comment]
Show de bola @MatheusMiranda! Assim que você subir isso pro Beta, de preferência amanhã de manhã  17/10, avisa a Kamilla pfv.

@KahCosta, como você está no plantão da monitoria essa semana, você vai validar a documentação e o processo de colocar a Taís em manutenção. Com base só na documentação, tenta colocá-la em estado de manutenção e tirar alguns minutos depois. Se der ruim, avisa o Miranda.
