### ISSUE TITLE
Melhorar métricas do Kibana

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#171]
Métricas desejadas:
* Intents mais frequentes vs perguntas mais frequentes

Métricas necessárias:
* Intents que ela não conseguiu responder (no tempo)
	* Listar todas as perguntas recebidas que geraram erros
* Gráfico de intents vs. utter -> mapeia utters respondidas errado
	* Detectar anomalias (pontos fora da curva)

**Comment by arthurTemporim** [comment]
Engloba a #146
