### ISSUE TITLE
Livechat não carrega de primeira em PROD

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#172]
Acontece em diferentes browsers e diferentes sistemas operacionais.

**Passos para reproduzir**

* Acessar o ambiente de prod: http://rouanet.cultura.gov.br/rouanet-bot-teste/
* Notar que a janela do livechat não aparece
* Recarregar a página (um número variável de tentativas)
* Notar que finalmente a janela do livechat aparece

**Comportamento esperado**
Que a janela do livechat aparecesse em poucos segundos após carregar a página, assim como acontece no Beta.

**Tasks**

- [ ] Documentar o que o @MatheusFaria não documentou
- [ ] Resolver o bug

**Comment by RochaCarla** [comment]
nao tem controle
