### ISSUE TITLE
Propor fusão do Refinamento com Beta

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#174]
Atualmente o processo de evolução da Taís passa por uma etapa de Refinamento com servidoras da SEFIC e outra de Homologação (Beta Teste) com produtores culturais. 

Queremos juntar essas duas etapas para acelerar a evolução da Taís.

**Tarefas**

- [x] Propor a inclusão das servidoras da SEFIC no beta e a fusão das duas etapas.

**Critérios de aceitação**

- [ ] A concordância da SEFIC ou uma justificativa da recusa.

**Comment by RochaCarla** [comment]
email foi enviado com o email da tais em cópia  (maia e poppi tb)

**Comment by arthurTemporim** [comment]
Ainda não houve resposta.

**Comment by rodmaia** [comment]
@RochaCarla quando a gente vai fazer essa fusão?
