### ISSUE TITLE
Atualizar a sintaxe da Taís 2.0

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#175]
Queremos facilitar a migração da Taís 2.0 para 2.1 no futuro. Seria ideal mudar a sintaxe dela agora, antes de outras mudanças de conteúdo ocorram.

**Tarefas**

- [x] Atualizar o **domain.yml** da `master` com a versão da `devel`
- [x] Verificar `actions` anteriores e se existe utters correspondentes e se não tiver, criar
- [x] Modificar o nome das `actions` nas `stories` para `utters`
- [x] Apagar todas as `actions`
- [ ] ~Usar a variável que previne o RASA de "misturar" as histórias `Augmentation_factor=0` no `load_data`~
- [x] Revisar as mensagens para garantir que o texto está correto
- [ ] Testar no ambiente DEV
- [ ] Testar de novo no ambiente DEV
- [ ] Testar mais um pouquinho no ambiente DEV

**Critérios de aceitação**

- [x] Uma comparação lado-a-lado entre a Taís com a sintaxe antiga (localhost de alguém da equipe) e com a sintaxe nova (ambiente DEV) dá **exatamente** os mesmos resultados, ou resultados mais precisos
- [x] Mostrar resultados para 3 membros da equipe não envolvidas com a issue. Das 3, pelo menos 1 é um membro senior.

**Comment by RochaCarla** [comment]
Nao foi realizada e voltou pro backlog
