### ISSUE TITLE
Analisar e preparar o artigo 44 da IN 5/2017

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#176]
Breve comentário sobre o contexto e descrição da issue.

**Tarefas**

- [x] Analisar o conteúdo do artigo 44 da  IN 5/2017 para entender onde se encaixa no fluxo da Taís 2.0 (antiga)
- [ ] ~~Usar esse conteúdo para melhorar as utters existentes até o momento~~
- [ ] ~~Melhorar a estrutura da [documentação na wiki](https://github.com/lappis-unb/rouana/wiki/Novos-t%C3%B3picos-para-inserir-no-futuro) para incluir o texto extraído do artigo 44~~
- [x] Mapear novos tópicos na wiki com prioridade máxima para inclusão

**Critérios de aceitação**

- [x] Sabemos do que trata o artigo 44
- [x] Sabemos qual o esforço de incluir todo o seu conteúdo na base de conhecimento da Taís
- [ ] Novos tópicos estão mapeados e prontos para serem trabalhados para a equipe incluir na base de conhecimento da Taís

**Comment by rodmaia** [comment]
Conteúdo enviado pela SEFIC

## Perguntas e Respostas
Nesta página, encontre as respostas às principais perguntas relativas à Instrução Normativa 5/2017 do Incentivo Fiscal da Lei Rouanet.


### Quais as etapas de aprovação de um projeto?
**Apresentação de proposta:** O proponente (responsável pelo projeto) insere uma proposta cultural no Sistema de Apoio às Leis de Incentivo à Cultura (Salic), de forma eletrônica. Devem ser preenchidos campos previamente definidos, tais como resumo, ficha técnica, orçamento, plano de distribuição de produtos/ingressos, e apresentados documentos obrigatórios de acordo com a área do projeto, conforme determinação da Instrução Normativa da Lei Rouanet vigente.
 
**Análise de admissibilidade:** o Ministério da Cultura (MinC) realiza a análise de admissibilidade da proposta a partir de critérios objetivos estabelecidos pela Lei 8.313/91 e pela Instrução Normativa em vigor, como, por exemplo:
Verificação do completo e correto preenchimento do formulário de apresentação da proposta cultural;
Análise quanto ao enquadramento do proponente e da proposta cultural;
Caso seja admitida, a proposta recebe um número de Pronac
Prazo: até 60 dias, podendo ser ampliado para até 120 dias quando os projetos forem de restauração do patrimônio histórico ou construção de imóveis.
Após a admissibilidade, o MinC publica **portaria de autorização para captação de recursos incentivados** no Diário Oficial da União (DOU).
 
**Análise técnica:** o projeto é encaminhado à análise técnica por parecerista da área cultural do projeto. São analisados requisitos como:
Atendimento aos objetivos do incentivo fiscal da Lei Rouanet;
Suficiência das informações prestadas;
Aferição da capacidade técnica do proponente para execução do projeto apresentado;
Adequação do projeto às medidas de acessibilidade e democratização de acesso ao público;
Compatibilidade dos custos previstos no projeto com os preços praticados no mercado regional da produção, conforme métrica estabelecida pelo MinC – o que se mostrar inadequado pode sofrer cortes justificados pelo parecerista;
Relação custo/benefício do projeto no âmbito cultural, incluindo o impacto da utilização do mecanismo de incentivo fiscal na redução do preço final de produtos ou serviços culturais com público pagante, podendo o parecerista propor redução nos preços solicitados;
Atendimento aos critérios e limites de custos estabelecidos pela Lei e Instrução Normativa em vigor;
**Prazo:** até 30 dias do seu recebimento, podendo ser prorrogado por mais 120 dias quando se tratar de projeto de recuperação de patrimônio histórico ou construção de imóveis.
Nos casos de projetos culturais que tenham como objeto a preservação de bens culturais tombados ou registrados pelos poderes públicos (federal, estadual, distrital ou municipal), será obrigatória, também, a apreciação pelo órgão responsável pelo tombamento ou registro.
 
**Análise pela CNIC:** Após emissão do parecer técnico, o projeto cultural será apreciado pela Comissão Nacional de Incentivo à Cultura (CNIC), que homologa a execução do projeto.
A CNIC é um colegiado de assessoramento de caráter paritário, formado por representantes dos setores artísticos, culturais e empresariais, em paridade da sociedade civil e do poder público;
Analisa os projetos culturais, inclusive sob seus aspectos orçamentários, podendo para tanto solicitar informações adicionais, diligenciando o proponente, emitindo parecer conclusivo pela aprovação, total ou parcial, ou rejeição do projeto cultural.
 
**Decisão final:** o ministro de Estado da Cultura, em última instância, decide quanto à aprovação ou rejeição do projeto cultural. Historicamente, por convenção, o MinC acompanha a decisão do órgão consultivo. Excepcionalmente, é possível que o ministro decida de forma diferente, fundamentando a justificativa.

### Qualquer pessoa pode apresentar uma proposta cultural?
*curiosidades_lei_rouanet_elegibilidade*
R – Proponente é a pessoa responsável por apresentar, realizar e responder pelo projeto cultural. Pode ser uma pessoa física com atuação na área cultural ou pessoa jurídica de direito público ou privado, com ou sem fins lucrativos, cujo ato constitutivo ou instrumento congênere disponha sobre sua finalidade cultural.

### Qual é o período do ano em que as propostas devem ser apresentadas ao MinC?
*(novo intent/fluxo)*
R – As propostas culturais podem ser apresentadas ao MinC de 1º de fevereiro a 30 de novembro de cada ano.

### Com quanto tempo de antecedência do evento as propostas de projetos devem ser apresentadas ao Ministério da Cultura (MinC) para que haja tempo hábil para a aprovação e captação de recursos?
*(novo intent/fluxo)*
R – As propostas candidatas devem ser apresentadas com pelo menos 90 dias de antecedência.

### É preciso comprovar experiência na área para apresentar uma proposta ao MinC?
*(novo intent/fluxo)*

R – A comprovação de experiência não é necessária para a admissão do primeiro projeto de realizadores culturais recém-inseridos no mercado. Com esta regra, o MinC busca apoiar novos empreendedores com bons projetos para que se consolidem. Apoiar o jovem empreendedor gera maiores possibilidades de atuação no campo da inovação.
No caso de proponentes experientes, a experiência em atividades culturais deve ser comprovada no ato de inscrição da proposta.
No caso de pessoa jurídica, a comprovação é realizada por meio do código de Classificação Nacional de Atividades Econômicas (CNAE), referente à área cultural nos registros do CNPJ da instituição.

### Há limites de quantidade de propostas apresentadas e de valor do projeto?
*(novo intent/fluxo)*
R – Sim, há limite no número de projetos e no valor máximo da soma dos projetos por perfil de proponente:
Para a Pessoa Física e para o Empresário Individual com enquadramento em Microempresário Individual (MEI), o valor máximo é de R$ 1,5 milhão para até quatro projetos por ano;
Para os demais enquadramentos de Empresário Individual, o valor máximo é de R$ 7, 5 milhões para até oito projetos por ano;
Para a Empresa Individual de Responsabilidade Limitada (EIRELI), Sociedades Limitadas (Ltda.) e demais Pessoas Jurídicas, o valor máximo é de R$ 60 milhões para até 16 projetos por ano.
 
### Esses limites podem ser ultrapassados? Em quais situações?
*(novo intent/fluxo)*
*(combinar com intent acima???)*
Os limites podem ser ultrapassados caso o projeto cultural seja realizado em espaços públicos ou nas regiões do País mais carentes de projetos Culturais.

*No caso de espaços públicos, o limite pode ser acrescido de:*
Mais dois projetos para Pessoa Física e Empresário Individual com enquadramento em Microempresário Individual (MEI), mantidos os limites orçamentários;
Mais três projetos para demais enquadramentos de Empresário Individual, mantidos os limites orçamentários;
 Mais quatro projetos para Empresa Individual de Responsabilidade Limitada (EIRELI), Sociedades Limitadas (Ltda.) e demais Pessoas Jurídicas, mantidos os limites orçamentários.

*Os limites podem ser ultrapassados nas seguintes regiões:*
Na Região Sul do País e estados de Espírito Santo e Minas Gerais – aumento de até 25% nos limites;
Nas Regiões Norte, Nordeste e Centro-Oeste: aumento de até 50% nos limites.
Essa extensão dos limites não contempla projetos relativos à realização de planos anuais e plurianuais de atividades; e a conservação e restauração de imóveis, monumentos, espaços e demais objetos tombados por qualquer das esferas de poder.
Exceções aos limites podem ser autorizadas pela área técnica do MinC em projetos de preservação de acervos e exposições organizadas com acervos museológicos de reconhecido valor cultural e de construção e implantação de equipamentos culturais de reconhecido valor cultural.

### Há um valor máximo por projeto?
*(Sinônimo de: Há limites de quantidade de propostas apresentadas e de valor do projeto?)*
R – O valor máximo do projeto pode atingir o valor total permitido por ano conforme o seu perfil.

### Os produtos culturais/ ingressos podem ser comercializados? Há um limite de preço a ser executado por produto realizado com apoio de incentivo fiscal?
*(novo intent/fluxo)*
R – Do total dos ingressos de um projeto cultural, a Instrução Normativa da Lei Rouanet estabelece que:
50% dos ingressos devem ser comercializados a uma média de preço de R$ 225,00.
Mínimo de 10% deve ser distribuído gratuitamente, com caráter social, educativo ou formação artística;
Até 10% deve ser disponibilizado gratuitamente pelos patrocinadores;
Até 10% deve ser distribuído gratuitamente pelo proponente de forma a divulgar o projeto;
Mínimo de 20% dos ingressos deve ser comercializado em valores que não ultrapassem R$ 75;

### Por que é obrigatória a contratação de profissionais de contabilidade e de advocacia para realização do projeto?
*(novo intent/fluxo)*
R  O desconhecimento de preceitos legais e contábeis ou a inobservância de alguns itens na realização dos projetos pode causar prejuízos à sua execução, resultando em reprovação e devolução de recursos ao erário. A Instrução Normativa da Lei Rouanet permite que o contador seja do quadro de funcionários da empresa do proponente da proposta cultural.

### O próprio proponente do projeto pode captar os recursos para a sua execução?
*(novo intent/fluxo)*
Sim. O profissional que captar os recursos para o projeto – seja ele o próprio proponente ou alguém contratado exclusivamente com este objetivo – poderá ser remunerado até o limite de 10% do valor do Custo do Projeto, sendo o teto do valor da remuneração de R$ 150 mil.
Este percentual pode ser expandido quando o projeto é realizado fora do eixo Rio-São Paulo, nas seguintes regiões do País:
15% do valor total do custo do projeto para projetos executados nas Regiões Norte, Nordeste e Centro-Oeste;
12,5% para os projetos realizados na Região Sul e nos estados de Minas Gerais e Espírito Santo.
Os valores destinados à remuneração para captação de recursos somente poderão ser pagos proporcionalmente às parcelas já captadas.

### O proponente (autor do projeto) é remunerado? Há limite para remuneração do proponente?
*(novo intent/fluxo)*
R – O proponente poderá ser remunerado com recursos decorrentes de renúncia fiscal, desde que preste serviço ao projeto, conforme previsto no orçamento apresentado. O valor desta remuneração, ainda que por diversos serviços, não pode ultrapassar 50% do custo do projeto.
O percentual de 50% inclui remuneração por serviços realizados por cônjuge, companheiro, parentes em linha reta ou colateral até o segundo grau, parentes com vínculo de afinidade com o proponente e em benefício de empresa coligada ou que tenha sócio em comum.
O limite pode ser ultrapassado quando a remuneração é feita a grupos artísticos familiares que atuem na execução do projeto ou quando se tratar de pagamento a um mesmo fornecedor em projetos de execução de obras e restauros.

### Quais os valores para pagamento de cachês em projetos realizados com incentivo fiscal? Há limites a serem observados?
*(novo intent/fluxo)*
R – O limite para pagamento de cachês artísticos por apresentação é:
R$ 45 mil para artista ou modelo solo;
R$ 90 mil para grupos artísticos e para grupos de modelos de desfiles de moda;
No caso de orquestras, os valores são: R$ 2.250 mil por músico e R$ 45 mil para o maestro;
A aprovação de valores superiores aos definidos acima poderá ser feita pelo plenário da Comissão Nacional de Incentivo à Cultura (CNIC), a depender das justificativas apresentadas pelo proponente e pela área técnica.

### É possível que o patrocinador faça a prospecção da sua marca em um projeto realizado com incentivo fiscal?
*(novo intent/fluxo)*
R – O patrocinador pode ativar sua marca em um projeto, desde que as ações sejam realizadas com recursos próprios, não decorrentes do incentivo fiscal, nas seguintes situações:
Veiculação da imagem institucional ou nome do incentivador em peças de divulgação além das aprovadas pelo Ministério da Cultura;
 
Fornecimento de produtos ou serviços do patrocinador ao projeto cultural, desde que comprovada a maior economicidade ou exclusividade;

**Comment by rodmaia** [comment]
Documentei sugestões do que podemos integrar em intents e actions existentes: apenas uma pequena parte. A maior parte desse material são novos conteúdos e tópicos variados.

**Comment by palomacmamede** [comment]
Em relação a essa pergunta eu acredito que a pergunta é sobre elegibilidade, mas eles trouxeram uma resposta de "definição de proponente".  [## intent:definicao_proponente]
Qualquer pessoa pode apresentar uma proposta cultural? 
Pois, a resposta da elegibilidade é mais completa: [voilá!]

 _utter_lei_rouanet_quem_pode_ser_proponente:
    - text: |
          Todo projeto cultural, de qualquer artista, produtor e agente cultural brasileiro, pode se beneficiar desta Lei e se candidatar à captação de recursos de renúncia fiscal.

          A proponência pode ser feita por Pessoas físicas com atuação comprovada na área cultural, ou Pessoas jurídicas de natureza cultural com, no mínimo, dois anos de atividade,

          podendo ser:

          Pessoas jurídicas públicas da administração indireta

          (autarquias, fundações culturais etc.)

          ou pessoas jurídicas privadas com ou sem fins lucrativos

          (empresas, cooperativas, fundações, ONGs, organizações culturais etc.)_

**Comment by palomacmamede** [comment]
É preciso comprovar experiência na área para apresentar uma proposta ao MinC? [ acredito que seja uma nova intent]

**Comment by palomacmamede** [comment]
Esses limites podem ser ultrapassados? Em quais situações? (combinar com intent acima???)
Sim, acho que a Taís poderia falar, algo como "você quer saber em quais situações esses limites podem ser ultrapassados?" , após a resposta sobre quantidade de projetos. (:

**Comment by palomacmamede** [comment]
Adicionar essa pergunta/resposta no fluxo é de extrema essencialidade, visto que grande parte das pessoas que participaram dos testes, tiveram interesse em saber sua resposta: **O próprio proponente do projeto pode captar os recursos para a sua execução?**

**Comment by rodmaia** [comment]
>Esses limites podem ser ultrapassados? Em quais situações? (combinar com intent acima???)
Sim, acho que a Taís poderia falar, algo como "você quer saber em quais situações esses limites podem ser ultrapassados?" , após a resposta sobre quantidade de projetos. (:

Concordo, vamos fazer duas perguntas encadeadas no fluxo

**Comment by palomacmamede** [comment]
As Issues para inserção de novos conteúdos foram abertas, se você puder revisar @rodmaia2099 .

**Comment by rodmaia** [comment]
## As issues criadas foram: #187, #189, #190, #191, #192, #193, #194, #195, #196 , #197 e #199.

**Comment by rodmaia** [comment]
@palomacmamede revisei as issues e fiz algumas mudanças:
* inclui a parte de documentação como tarefa
* melhorei os critérios de aceitação para incluir a nossa documentação da wiki de "conteúdo atual" e a área equivalente no Beta
* Criei uma issue para melhorar a intent de elegibilidade, combinando o conteúdo novo com os sinônimos de pergunta que a gente já tinha mapeado

**Faltou** a gente documentar o que vai ser feito com aquele tópico grande: *Quais as etapas de aprovação de um projeto?*. Você pode revisar onde as mudanças relativas à isso podem entrar e criar as issues com base na que eu fiz pra #197?

**Comment by palomacmamede** [comment]
@rodmaia2099 em breve vou atualizar as issues neste novo formato que você criou que inclusive ficou muito mais completo e eficiente. Sobre o tópico _Quais as etapas de aprovação de um projeto?_ , temos que pensar em como encaixá-lo no fluxo de forma que não fique massiva,  é um tópico muito importante visto que alguns usuários fizeram este tipo de pergunta.

**Comment by palomacmamede** [comment]
@rodmaia2099  Eu tive uma ideia para o tópico _Quais as etapas de aprovação de um projeto?_, acho que a Taís poderia responder a pergunta usando de resposta apenas os tópicos, ex: As etapas do processo são Apresentação de proposta, Análise de Admissibilidade, Análise técnica, Prazo, Análise pela CNIC e Decisão final. Daí, ao final da explicação ela poderia perguntar se o usuário gostaria de saber mais sobre algum tópico, se sim, ela o explica de forma aprofundada, o que acha?
