### ISSUE TITLE
Testar nova versão do RASA

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#186]
Atualizar o RASA e testar a Tais com a  base de dados da atual.

**Tarefas**

- [x]  Configurar um **bot base** com a nova versão do RASA;
- [x] Trazer conteúdo da Taís para o **bot base** com ajustes finos;
- [ ] Testar conexões com **Rocket.Chat**;
- [ ] Testar conexões com **livechat**;
- [ ] Documentar as mudanças da nova versão, tanto ganhos quanto perdas;
- [ ] Documentar a forma de execução do bot.

**Critérios de aceitação**

- [ ] Garantir que a nova versão do bot tem o mesmo comportamento que o antigo;
- [ ] Garantir que todos os membros do time compreendem as mudanças e os avanços.

**Comment by arthurTemporim** [comment]
Vlw @diegodorgam

**Comment by RochaCarla** [comment]
Estudar quais os fatores que influenciam o algoritmo LSTM (KerasPolicy).
Algumas boas referencias:

http://adventuresinmachinelearning.com/keras-lstm-tutorial/

https://chatbotsmagazine.com/contextual-chat-bots-with-tensorflow-4391749d0077

https://www.tensorflow.org/tutorials/representation/word2vec

https://arxiv.org/pdf/1606.01269.pdf

**Comment by chris-redfield** [comment]
Pra testar o NLU é fácil, basta consultar a api rest dele, nesse link tem as refs:

https://rasa.com/docs/nlu/http/

**Comment by RochaCarla** [comment]
Foi definido que se nao houvesse evolução em uma semana essa issue sera fechada..

**Comment by arthurTemporim** [comment]
A nova versão do RASA está funcionando no console neste repositório [Taís](https://github.com/lappis-unb/tais).
* Utilizando as `intents` e `stories` da versão anterior a Taís continua funcionando no console
* Não foi feito nenhum teste com a conexão da Rocket.Chat
* O README precisa ser melhorado com as mudanças feitas
* Testes com sinônimos funcionam bem com esta versão.
* É necessário construir um script como o `train.py` para verificar se esta versão permite que todos os comportamentos do script anterior também funcione perfeitamente.
*  O Docker desta versão está funcionando.

**Comment by RochaCarla** [comment]
Funcionalidades "novas" avaliadas/mapeadas
- permissão de mandar msg e tracker os dados do bot por meio da API
- Novas policies/refatoração de policies (não foi testado)
- Feature utilização de sinonimos dentro do markdown das intents (verificar se é ou nao funcionalidade nova)

**Comment by RochaCarla** [comment]
Nao foi finalizado um estudo mais aprofundado para verificar a real necessidade/ benefício de da mudanca de versões. A mudança tem overheads (atualizar conector e testar a tais na nova versão), e por falta de evidencias dos beneficios, não vamos priorizar essa transiçao e tal issue volta pra icebox
