### ISSUE TITLE
Acrescentar tópico "limites de quantidade/valor de proposta"

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#187]
**Tarefas**

- [x] Acrescentar os tópicos com id 109 [(Novos tópicos para inserir no futuro)](https://github.com/lappis-unb/rouana/wiki/Novos-t%C3%B3picos-para-inserir-no-futuro) na versão Beta da Taís
- [x] Atualizar documentação do conteúdo da Taís em [Mensagens da Taís](../wiki/Mensagens-da-Taís), no *Changelog* e em *O que ela sabe responder* no Beta.

**Critérios de aceitação**

- [x] A Taís é capaz de responder esses tópicos no Beta
- [x] O novo conteúdo não reduziu a precisão de resposta para outros tópicos
- [x] Os gestores da SEFIC conseguem ver o que foi alterado a partir da página da Wiki
- [x] Os beta-testers sabem o que foi alterado na Taís ao ler o *Changelog* e *O que ela sabe responder* do Beta ao serem publicados

## Conteúdos

**Há limites de quantidade de propostas apresentadas e de valor do projeto?**
R – Sim, há limite no número de projetos e no valor máximo da soma dos projetos por perfil de proponente:
Para a Pessoa Física e para o Empresário Individual com enquadramento em Microempresário Individual (MEI), o valor máximo é de R$ 1,5 milhão para até quatro projetos por ano;
Para os demais enquadramentos de Empresário Individual, o valor máximo é de R$ 7, 5 milhões para até oito projetos por ano;
Para a Empresa Individual de Responsabilidade Limitada (EIRELI), Sociedades Limitadas (Ltda.) e demais Pessoas Jurídicas, o valor máximo é de R$ 60 milhões para até 16 projetos por ano.

**Esses limites podem ser ultrapassados? Em quais situações?**
Os limites podem ser ultrapassados caso o projeto cultural seja realizado em espaços públicos ou nas regiões do País mais carentes de projetos Culturais.

No caso de espaços públicos, o limite pode ser acrescido de:
Mais dois projetos para Pessoa Física e Empresário Individual com enquadramento em Microempresário Individual (MEI), mantidos os limites orçamentários;
Mais três projetos para demais enquadramentos de Empresário Individual, mantidos os limites orçamentários;
Mais quatro projetos para Empresa Individual de Responsabilidade Limitada (EIRELI), Sociedades Limitadas (Ltda.) e demais Pessoas Jurídicas, mantidos os limites orçamentários.

Os limites podem ser ultrapassados nas seguintes regiões:
Na Região Sul do País e estados de Espírito Santo e Minas Gerais – aumento de até 25% nos limites;
Nas Regiões Norte, Nordeste e Centro-Oeste: aumento de até 50% nos limites.
Essa extensão dos limites não contempla projetos relativos à realização de planos anuais e plurianuais de atividades; e a conservação e restauração de imóveis, monumentos, espaços e demais objetos tombados por qualquer das esferas de poder.
Exceções aos limites podem ser autorizadas pela área técnica do MinC em projetos de preservação de acervos e exposições organizadas com acervos museológicos de reconhecido valor cultural e de construção e implantação de equipamentos culturais de reconhecido valor cultural.

**Há um valor máximo por projeto?**
R – O valor máximo do projeto pode atingir o valor total permitido por ano conforme o seu perfil.

**Comment by RochaCarla** [comment]
Seguir o roteiro proposto em:
[https://github.com/lappis-unb/rouana/wiki/Intents-Eficientes](https://github.com/lappis-unb/rouana/wiki/Intents-Eficientes)
