### ISSUE TITLE
Acrescentar tópico "captação de recursos"

### ISSUE THREAD

**Issue by palomacmamede** [lablivre-unb/tais#192]
**Tarefas**

- [x] Acrescentar os tópicos com id 113 [(Novos tópicos para inserir no futuro)](https://github.com/lappis-unb/rouana/wiki/Novos-t%C3%B3picos-para-inserir-no-futuro) na versão Beta da Taís
- [x] Atualizar documentação do conteúdo da Taís em [Mensagens da Taís](../wiki/Mensagens-da-Taís), no *Changelog* e em *O que ela sabe responder* no Beta.

**Critérios de aceitação**

- [x] A Taís é capaz de responder esses tópicos no Beta
- [x] O novo conteúdo não reduziu a precisão de resposta para outros tópicos
- [x] Os gestores da SEFIC conseguem ver o que foi alterado a partir da página da Wiki
- [x] Os beta-testers sabem o que foi alterado na Taís ao ler o *Changelog* e *O que ela sabe responder* do Beta ao serem publicados

## Conteúdo

**O próprio proponente do projeto pode captar os recursos para a sua execução?**
Sim. O profissional que captar os recursos para o projeto – seja ele o próprio proponente ou alguém contratado exclusivamente com este objetivo – poderá ser remunerado até o limite de 10% do valor do Custo do Projeto, sendo o teto do valor da remuneração de R$ 150 mil.
Este percentual pode ser expandido quando o projeto é realizado fora do eixo Rio-São Paulo, nas seguintes regiões do País:
15% do valor total do custo do projeto para projetos executados nas Regiões Norte, Nordeste e Centro-Oeste;
12,5% para os projetos realizados na Região Sul e nos estados de Minas Gerais e Espírito Santo.
Os valores destinados à remuneração para captação de recursos somente poderão ser pagos proporcionalmente às parcelas já captadas.

**Comment by RochaCarla** [comment]
Seguir o roteiro proposto em:
[https://github.com/lappis-unb/rouana/wiki/Intents-Eficientes](https://github.com/lappis-unb/rouana/wiki/Intents-Eficientes)

**Comment by RochaCarla** [comment]
Grande parte das tarefas relacionadas à issue não foram realizadas
