### ISSUE TITLE
Melhorar tópico "elegibilidade"

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#197]
**Tarefas**

- [x] No beta, melhorar o intent "curiosidades_lei_rouanet_elegibilidade" com as perguntas mapeadas em `lei_rouanet_quem_pode_ser_proponente` na página [Sinônimos de tópicos existentes](../wiki/Sinônimos-de-tópicos-existentes)
- [x] No beta, melhorar a action/utter relacionada à elegibilidade com o coneúdo abaixo
- [ ] Atualizar documentação do conteúdo da Taís em [Mensagens da Taís](../wiki/Mensagens-da-Taís), no *Changelog* e em *O que ela sabe responder* no Beta.

**Critérios de aceitação**

- [x] A Taís é capaz de responder esses tópicos no Beta
- [x] A alteração de conteúdo aumentou a precisão de resposta para elegibilidade
- [x] A alteração de conteúdo não reduziu a precisão de resposta para outros tópicos
- [ ] Os gestores da SEFIC conseguem ver o que foi alterado a partir da página da Wiki
- [ ] Os beta-testers sabem o que foi alterado na Taís ao ler o *Changelog* e *O que ela sabe responder* do Beta ao serem publicados

## Conteúdo

**Qualquer pessoa pode apresentar uma proposta cultural?**

R – Proponente é a pessoa responsável por apresentar, realizar e responder pelo projeto cultural. Pode ser uma pessoa física com atuação na área cultural ou pessoa jurídica de direito público ou privado, com ou sem fins lucrativos, cujo ato constitutivo ou instrumento congênere disponha sobre sua finalidade cultural.

**Comment by palomacmamede** [comment]
Possível solução:

## intent:lei_rouanet_quem_pode_ser_proponente
- quem pode se inscrever na lei rouanet
- quem pode participar
- quem pode submeter projetos
- quem pode apresentar projetos
- quem pode apresentar proposta cultural
- quem pode apresentar proposta
- quem pode propor projetos via Lei Rouanet
- quem pode cadastrar projetos lei de incentivo
- quem pode iniciar um projeto na lei rouanet
- quem pode se aplicar
- quem pode propor
- quem não pode participar
- quero participar da lei
- quero me tornar um proponente
- quero me inscrever na lei rouanet
- quero ser proponente
- posso me inscrever na lei rouanet
- posso ser preponente
- posso inscrever uma proposta como pessoa fisica
- eu posso usar a lei
- eu posso participar da lei rouanet 
- o proponente pode ser pessoa física ou jurídica
- o proponente pode ser pessoa fisica ou juridica
- parentes de proponente podem apresentar projetos
- parentes podem propor projetos
- pessoa física pode ser proponente
- quais projetos se encaixam na lei rouanet
- qualquer empresa pode apresentar um projeto
- qualquer pessoa pode apresentar um projeto
- qualquer segmento cultural pode propor um projeto na lei rouanet
- qual tipo de projeto pode ser apresentado na lei rouanet
- como pessoa fisica eu posso inscrever uma proposta
- como ser proponente
- como me inscrever
- como me tornar proponente
- é necessário comprovar experiência cultural para ser proponente
- minha empresa pode ser proponente
- mei pode ser proponente
- tenho uma banda de musica posso propor um projeto 
- agente publico pode enviar propostas
- elegibilidade
- inscrever
- participar
- usar a lei

**Comment by palomacmamede** [comment]
Utter antiga:
Todo projeto cultural, de qualquer artista, produtor e agente cultural brasileiro, pode se beneficiar desta Lei e se candidatar à captação de recursos de renúncia fiscal. A proponência pode ser feita por Pessoas físicas com atuação comprovada na área cultural, ou Pessoas jurídicas de natureza cultural com, no mínimo, dois anos de atividade, podendo ser:
Pessoas jurídicas públicas da administração indireta (autarquias, fundações culturais etc.) ou pessoas jurídicas privadas com ou sem fins lucrativos (empresas, cooperativas, fundações, ONGs, organizações culturais etc.)
