### ISSUE TITLE
Acrescentar tópico "Quais as etapas de aprovação de um projeto?"

### ISSUE THREAD

**Issue by palomacmamede** [lablivre-unb/tais#199]
**Tarefas**

- [x] Acrescentar os tópicos com id 121 [(Novos tópicos para inserir no futuro)](https://github.com/lappis-unb/rouana/wiki/Novos-t%C3%B3picos-para-inserir-no-futuro) na versão Beta da Taís
- [x] Atualizar documentação do conteúdo da Taís em [Mensagens da Taís](../wiki/Mensagens-da-Taís), no *Changelog* e em *O que ela sabe responder* no Beta.
- [x] Analisar se a melhor solução é convergir o fluxo de curiosidades/proposta ou se será mais eficiente a duplicação do conteúdo

**Critérios de aceitação**

- [x] A Taís é capaz de responder esses tópicos no Beta
- [x] O novo conteúdo não reduziu a precisão de resposta para outros tópicos
- [x] Os gestores da SEFIC conseguem ver o que foi alterado a partir da página da Wiki
- [x] Os beta-testers sabem o que foi alterado na Taís ao ler o *Changelog* e *O que ela sabe responder* do Beta ao serem publicados

## Conteúdos

Quais as etapas de aprovação de um projeto?
Apresentação de proposta: O proponente (responsável pelo projeto) insere uma proposta cultural no Sistema de Apoio às Leis de Incentivo à Cultura (Salic), de forma eletrônica. Devem ser preenchidos campos previamente definidos, tais como resumo, ficha técnica, orçamento, plano de distribuição de produtos/ingressos, e apresentados documentos obrigatórios de acordo com a área do projeto, conforme determinação da Instrução Normativa da Lei Rouanet vigente.

Análise de admissibilidade: o Ministério da Cultura (MinC) realiza a análise de admissibilidade da proposta a partir de critérios objetivos estabelecidos pela Lei 8.313/91 e pela Instrução Normativa em vigor, como, por exemplo:
Verificação do completo e correto preenchimento do formulário de apresentação da proposta cultural;
Análise quanto ao enquadramento do proponente e da proposta cultural;
Caso seja admitida, a proposta recebe um número de Pronac
Prazo: até 60 dias, podendo ser ampliado para até 120 dias quando os projetos forem de restauração do patrimônio histórico ou construção de imóveis.
Após a admissibilidade, o MinC publica portaria de autorização para captação de recursos incentivados no Diário Oficial da União (DOU).

Análise técnica: o projeto é encaminhado à análise técnica por parecerista da área cultural do projeto. São analisados requisitos como:
Atendimento aos objetivos do incentivo fiscal da Lei Rouanet;
Suficiência das informações prestadas;
Aferição da capacidade técnica do proponente para execução do projeto apresentado;
Adequação do projeto às medidas de acessibilidade e democratização de acesso ao público;
Compatibilidade dos custos previstos no projeto com os preços praticados no mercado regional da produção, conforme métrica estabelecida pelo MinC – o que se mostrar inadequado pode sofrer cortes justificados pelo parecerista;
Relação custo/benefício do projeto no âmbito cultural, incluindo o impacto da utilização do mecanismo de incentivo fiscal na redução do preço final de produtos ou serviços culturais com público pagante, podendo o parecerista propor redução nos preços solicitados;
Atendimento aos critérios e limites de custos estabelecidos pela Lei e Instrução Normativa em vigor;
Prazo: até 30 dias do seu recebimento, podendo ser prorrogado por mais 120 dias quando se tratar de projeto de recuperação de patrimônio histórico ou construção de imóveis.
Nos casos de projetos culturais que tenham como objeto a preservação de bens culturais tombados ou registrados pelos poderes públicos (federal, estadual, distrital ou municipal), será obrigatória, também, a apreciação pelo órgão responsável pelo tombamento ou registro.

Análise pela CNIC: Após emissão do parecer técnico, o projeto cultural será apreciado pela Comissão Nacional de Incentivo à Cultura (CNIC), que homologa a execução do projeto.
A CNIC é um colegiado de assessoramento de caráter paritário, formado por representantes dos setores artísticos, culturais e empresariais, em paridade da sociedade civil e do poder público;
Analisa os projetos culturais, inclusive sob seus aspectos orçamentários, podendo para tanto solicitar informações adicionais, diligenciando o proponente, emitindo parecer conclusivo pela aprovação, total ou parcial, ou rejeição do projeto cultural.

Decisão final: o ministro de Estado da Cultura, em última instância, decide quanto à aprovação ou rejeição do projeto cultural. Historicamente, por convenção, o MinC acompanha a decisão do órgão consultivo. Excepcionalmente, é possível que o ministro decida de forma diferente, fundamentando a justificativa.

**Comment by arthurTemporim** [comment]
@palomacmamede @rodmaia2099 **Me ajuda com essa intent!** como posso colocar isso no texto? ta muito grande, separo em intents menores? divido em mensagens separadas? mando um textão só?

**Comment by rodmaia** [comment]
Essa intent já existe na real. Devemos usar o conteúdo para melhorar a utter que dá a visão geral sobre o processo e as utters que explicam individualmente cada etapa.

**Comment by palomacmamede** [comment]
este conteúdo já foi implementado e testado com sucesso
