### ISSUE TITLE
Estudar chatbot UX

### ISSUE THREAD

**Issue by MatheusFaria** [lablivre-unb/tais#20]
**Links Importantes**

https://medium.com/labworks-io/the-conversation-designers-handbook-or-how-to-design-chatbots-google-home-actions-and-alexa-17ebb87b332c

https://chatbotsmagazine.com/6-tips-for-designing-your-best-chatbot-591aba9c9eff

https://chatbotsmagazine.com/cheat-sheet-all-facebook-chatbot-interactions-4b14e4e00178

https://chatbotsmagazine.com/cheat-sheet-all-facebook-chatbot-interactions-4b14e4e00178

https://hbr.org/2017/04/ai-wont-change-companies-without-great-ux

**Comment by arthurTemporim** [comment]
Um relatório foi elaborado e está neste link:

[Estudo sobre melhores práticas de bots](https://github.com/lappis-unb/EcossistemasSWLivre/wiki/Estudo-sobre-melhores-pr%C3%A1ticas-de-bots)
