### ISSUE TITLE
Estudo sobre intents

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#203]
Estudar e criar guideline de intents, bem como documentá-lo e analisar suas características: como escrever e testar intents.

**Tarefas**

- [x] Criar modelo eficaz para intents
- [x] Testar eficácia do modelo
- [x] Argumentar eficácia do modelo
- [x] Parametrização do treinamento (RasaNLU)

**Critérios de aceitação**

- [x] O modelo foi implementado 
- [x] O modelo é eficaz

**Comment by palomacmamede** [comment]
O Estudo sobre as Intents foi documentado neste link [Como Criar Intents mais Eficientes para o Rasa em PT-BR](https://github.com/lappis-unb/rouana/wiki/Intents-Eficientes)

**Comment by RochaCarla** [comment]
Foi atualizado também os hiperparâmetros que interferem no treinamento das intents no mesmo documento
