### ISSUE TITLE
Refatorar conteúdo das intents

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#205]
Refatorar o conteúdo de cada `intent` de acordo com o guideline e com as intents levantadas [neste documento](https://github.com/lappis-unb/rouana/wiki/Mensagens-da-Ta%C3%ADs)

**Tarefas**

**Verificar as seguintes hipóteses**
- [x] Garantir que todas as `intents` tenham exatamente **20** exemplos
- [x] Dividir os exemplos em **10** frases e **10** palavras chaves
- [x] Intents com apenas letras minúsculas
- [x] Intents sem acentos
- [x] Intents sem erros ortográficos
- [x] Intents  sem pontuação ortográfica
- [ ] ~Adicionar exemplos que são semelhantes às intents já levantados no beta teste (sinônimos considerados relevantes)~

**Após todas as mudanças feitas**
- [x] Recalibrar o treinamento do nlu no `train.py`

**Critérios de aceitação**

- [x] Ter a Tais funcionando com toda evolução implementada

**Comment by arthurTemporim** [comment]
Após testes utilizando o pipeline atual, algumas hipóteses levantadas nesta issue não foram verdadeiras. Nos comentários a seguir pode ser verificado cada resultado.

`config.yml` atual:
```
language : "pt"
pipeline:
    - name: "tokenizer_whitespace"
    - name: "ner_crf"
    - name: "ner_synonyms"
    - name: "intent_featurizer_count_vectors"
    - name: "intent_classifier_tensorflow_embedding"
```
[tokenizer_whitespace](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/tokenizer.py)

**Comment by arthurTemporim** [comment]
**Intents sem acentos** `FALSO`

De acordo com o pipeline atual é necessário ter exemplos de palavras acentuadas e não acentuadas para que o bot compreenda da `intent`

Então variar exemplos com e sem acentos da mesma palavra são necessários.

**Comment by arthurTemporim** [comment]
**Intents sem pontuação ortográfica** `VERDADEIRO`

Para o `config.yml` atual não faz diferença pontuação ortográfica como por exemplo:
 `,`, `?`, `!`, `.`

Então todas as pontuações podem ser removidas.

**Comment by RochaCarla** [comment]
@arthurTemporim Atualiza essas informações no documento sobre guidelines de intents
[https://github.com/lappis-unb/rouana/wiki/Intents-Eficientes](https://github.com/lappis-unb/rouana/wiki/Intents-Eficientes)

**Comment by arthurTemporim** [comment]
**Intents sem erros ortográficos** `FALSO`

O pipeline atual precisa de "exemplos mais explicitos" para ter seu funcionamento correto, isso é mais explicto em poucas palavras. quando são usadas frases mais completas o comportamento do NLU é melhor.

Logo se o objetivo do bot for entender erros ortográficos é necessario adiciona-los

**Comment by arthurTemporim** [comment]
**Intents com apenas letras minúsculas** `FALSO`

Não faz diferença letras maísculas ou minúsculas para o NLU atual. Para manter padrão sugiro manter tudo em minúsculo.

**Comment by arthurTemporim** [comment]
**Dividir os exemplos em 10 frases e 10 palavras chaves** `SEM CONCLUSÂO`

Não conseguimos identficar evolução ou piora na utilização de 20 exemplos divididos em 10 frases e 10 palavras chaves. Porém ter um padrão para todas as `intents` é uma boa prática que facilita a manutenção do bot.

**Comment by arthurTemporim** [comment]
**Recalibrar o treinamento do nlu no `train.py`**

Sobre este critério não existe nada de "configuração" no `train.py` relacionado ao **nlu** apenas chamadas de métodos, é necessário melhorar nosso `train.py` para recalibrar o **nllu**, aparentemente está dando overfiting mas tem que ser verificado.
