### ISSUE TITLE
Bug - Entrando no fallback mesmo após acertar uma intent

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#207]
Teste no ambiente de beta testes, realiado dia 23/10

Comportamento esperado
- Ao acertar uma intent, a Tais apresenta a resposta associada à intent (Action/utter) e depois apresenta a mensagem de volta ao fluxo (tem mais alguma pergunta?)

Comportamento observado
- Em duas intents  (o que é salic  e o que é a fase de prestacao de contas), após identificar corretamente a intent, e responder a action/utter correta, a Tais apresenta a mensagem "nao entendi", ao inves de (tem mais alguma curiosidade)

**Comment by arthurTemporim** [comment]
Foi resolvida na [aqui](https://github.com/lappis-unb/rouana/commit/c755b2af3ad08467187c57de68f0752b6de4c190)
