### ISSUE TITLE
Sarau Rasa CORE!!

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#224]
Sarau Rasa Hard Core! - a ser realizado dia 12/11 as 15 horas :)
**Tarefas**

- [ ] Temporim e kamilla! - 10 min para explicar o notebook e como funciona o Rasa NLU (Conceitos, como funciona, como fazer) - documentar na Wiki

- [ ] Dorgam! - 10 min para explicar o funcionamento do Policy Rasa (conceitos, como funciona, como fazer) - documentar na Wiki

- [ ] Carla - 5 min para explicar o funcionamento do Keras LSTM (conceitos, como funciona, como fazer) - hiperparamentros 

- [x] Paloma - 5 min para falar sobre diálogos no novo modelo do Rasa :P (Conceitos, como funciona, como fazer) - documentar na Wiki

- [ ] Farias - 10 min falar sobre monitoramento (conceitos, como funciona, como fazer) - documentar na wiki

- [ ] Gabi - 10 min. falar sobre testes automatizados - pytest, uso api rasa, rasatracker, assertequals (qq coisa falar com temporim)

**Comment by RochaCarla** [comment]
Documentação a ser disponibilizada em [https://github.com/lappis-unb/rouana/wiki/Estudo-sobre-pipeline-ML-Rasa](https://github.com/lappis-unb/rouana/wiki/Estudo-sobre-pipeline-ML-Rasa)

**Comment by palomacmamede** [comment]
[Novo Modelo de Diálogos](https://github.com/lappis-unb/rouana/wiki/Novo-Modelo-de-Di%C3%A1logos)
