### ISSUE TITLE
Implementar o novo modelo de diálogos da Taís e criar exemplos

### ISSUE THREAD

**Issue by palomacmamede** [lablivre-unb/tais#225]
Criar diálogos mais harmônicos que não seja presos ao modelo de fluxo antigo, bem como entender as mudanças que serão necessárias nas conversas.

**Tarefas**

- [x] Entender o novo modelo de Stories
- [x] Criar exemplos eficientes de diálogos de conexões [menus]
- [x] Atualizar as Utters de conexão
- [x] Adicionar conteúdos que ela sabe responder - criar intent e Utter

**Critérios de aceitação**

- [x] Diálogos deixaram a conversa mais fluída e mais livre
- [x] A interação é eficiente

**Comment by RochaCarla** [comment]
Sugestão. Ao responder uma pergunta, ao invés de perguntar se ele tem mais dúvida, perguntar se a pergunta atendeu ? ex: "Esta resposta atendeu sua dúvida?"(Bia)

**Comment by RochaCarla** [comment]
criar atalhos, para facilitar o acesso à informação do usuário, como por exemplo #menu (olhar como a Bia faz esses atalhos)

**Comment by palomacmamede** [comment]
O novo modelo de diálogos já foi implementado.
