### ISSUE TITLE
Levantar stack de monitoramento em devel e em beta

### ISSUE THREAD

**Issue by MatheusFaria** [lablivre-unb/tais#227]
- [x] Revisar estrutura de monitoramento: formato dos dados, conexões e vizualizações
- [x] Melhorar segurança do elasticsearch
- [x] Levantar elastic em devel
- [x] Levantar elastic em beta
- [ ] Implementar replay para conversas antigas

**Critérios de aceitação**

- [x] Elastice e Kibana acessiveis com usuário e senha
- [x] Vizualizações montadas no dashboard
- [ ] É possível ver e analisar conversas antigas

**Comment by RochaCarla** [comment]
Issue será fechada e issue de replay vai ser reaberta na nova sprint #257
