### ISSUE TITLE
Entender diferentes escritas de "rouanet"

### ISSUE THREAD

**Issue by rodrigocam** [lablivre-unb/tais#229]
Como rouanet pode ser um nome difícil de escrever para quem não tem nenhum conhecimento sobre a lei, seria bacana se o bot entendesse palavras como: "ruane", "ruanê", "ruanet", "rouane", "rouanê".

**Critérios de aceitação**

- [x] Perguntar o que é a lei rouanet com diferentes formas de escrita e o bot responder corretamente sobre a lei.

**Comment by RochaCarla** [comment]
Issue fechada
