### ISSUE TITLE
Aceitar uma pergunta como resposta no fluxo de sim ou não

### ISSUE THREAD

**Issue by rodrigocam** [lablivre-unb/tais#232]
Aceitar direto uma pergunta quando o bot perguntar se gostaria de saber mais.

![rouana](https://user-images.githubusercontent.com/12930004/48072505-d13b5900-e1c3-11e8-8ea6-86b8d9674336.png)

**Critérios de aceitação**

- [x] Responder a pergunta do bot com uma outra pergunta e ele responder corretamente.

**Comment by palomacmamede** [comment]
Esta ideia já foi implementada na criação da Utter_manter_conversa na issue #238
