### ISSUE TITLE
Proposta de estrutura de dialogo

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#238]
Propor um modelo diálogo para a Tais.

**Tarefas**

- [x] Utilizar 

**Critérios de aceitação**

- [x] Cada critério de aceitação descreve uma condição necessária para que a issue seja considerada completa
- [x] A condição necessária pode ser a nível de comportamento ou resultado

**Comment by RochaCarla** [comment]
Núcleos de conversa

- Entender o Incentivo
- Processo
- Operacional/Meu projeto
- O que é/definição

As intents vao ser separadas em tres grandes grupos (de acordo com a expectativa de uso)

- intents mais frequentes
- Intents menos frequentes
- intents raras

O que tem  que ser feito

- [x] Introdução 1 contato

- [x] Introdução retorno

- [x] #meajuda - menu detalhado

- [x] manter conversa

- [x] fim da conversa

**Comment by palomacmamede** [comment]
A proposta de estrutura de diálogo já foi criada e implementada
