### ISSUE TITLE
Acrescentar o tópico "Quantos projetos foram aprovados este ano"

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#242]
**Tarefas**

- [x] intent
- [x] utter
- [x] storie
- [x] testar

**Critérios de aceitação**

- [x] O conteúdo funciona
- [x] Passou nos testes

## Conteúdos

**Quantos projetos foram aprovados este ano?**
R –    Para consultar os projetos que foram aprovados este ano, ou em alguma outra data específica,
          acesse: http://versalic.cultura.gov.br/

**Comment by palomacmamede** [comment]
A Taís responde esse conteúdo junto com o de Valor Máximo por projeto:
utter_lei_rouanet_valor_maximo_pessoa_juridica:
    - text: |
          Então, em relação aos demais enquadramentos de Empresário Individual, o valor máximo é de R$ 7,5 milhões para até oito projetos por ano;
          Para a Empresa Individual de Responsabilidade Limitada (EIRELI), Sociedades Limitadas (Ltda.) e demais Pessoas Jurídicas, o valor máximo é de R$ 60 milhões para até **16 projetos por ano**.

          Se o projeto cultural ocorrer em espaço público, o Empresário Individual tem a quantidade de projetos acrescido em 3, mas o valor máximo não muda.
          Ássim como as Empresa Individual de Responsabilidade Limitada (EIRELI), Sociedades Limitadas (Ltda.) e demais Pessoas Jurídicas, quem podem somar mais 4 projetos, se realizados em espaço público, mantendo os limites orçamentários.

**Comment by palomacmamede** [comment]
Conteúdo já existente:

utter_lei_rouanet_quantidade_de_projetos:
    - text: |
          Até o momento foram enviadas mais de 240.000 propostas, das quais mais de 89.000 foram aprovadas, se tornando projetos.
          Há mais de 43.000 proponentes cadastrados e mais de 80.000 incentivadores contribuindo com projetos.
          Além disso, mais de 69.000 fornecedores foram contratados pelos proponentes.
          Para consultar os projetos que já participaram, acesse: http://versalic.cultura.gov.br/
