### ISSUE TITLE
Acrescentar o tópico democratização do acesso e formação de plateia

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#243]
**Tarefas**

- [x] Acrescentar os tópicos com id 3 [(Novos tópicos para inserir no futuro)](https://github.com/lappis-unb/rouana/wiki/Novos-t%C3%B3picos-para-inserir-no-futuro) na versão Beta da Taís - somente a intent
- [x] Atualizar documentação do conteúdo da Taís em [Mensagens da Taís](../wiki/Mensagens-da-Taís), no *Changelog* e em *O que ela sabe responder* no Beta.

**Critérios de aceitação**

- [x] A Taís é capaz de responder esses tópicos no Beta
- [x] O novo conteúdo não reduziu a precisão de resposta para outros tópicos
- [x] Os gestores da SEFIC conseguem ver o que foi alterado a partir da página da Wiki
- [x] Os beta-testers sabem o que foi alterado na Taís ao ler o *Changelog* e *O que ela sabe responder* do Beta ao serem publicados

## Conteúdos

** É obrigatória realizar a formação de plateia no projeto?**
R –

**Comment by arthurTemporim** [comment]
VERIFICAR SE JÁ EXISTE

**Comment by palomacmamede** [comment]
As informações sobre a obrigatoriedade da formação de plateia estão  no art 57 da INSTRUÇÃO NORMATIVA Nº 1, DE 20 DE MARÇO DE 2017

**Comment by palomacmamede** [comment]
A Utter comercialização de ingressos responde uma parte do questionamento, porém não sana totalmente a dúvida, seria interessante tbm adicionar um conteúdo sobre acesso democratização do acesso

**Comment by palomacmamede** [comment]
XXII - Formação de plateias: Ações presenciais e gratuitas, destinadas a alunos e professores de instituições de ensino de qualquer nível, que visem a conscientização para a importância da arte e da cultura por intermédio do produto do projeto cultural. (NR)

**Comment by palomacmamede** [comment]
XV - Democratização do acesso: medidas presentes na proposta cultural que promovam ou ampliem a possibilidade de fruição dos bens, produtos e ações culturais, em especial às camadas da população menos assistidas ou excluídas do exercício de seus direitos culturais por sua condição socioeconômica ou por quaisquer outras circunstâncias.

**Comment by palomacmamede** [comment]
Art. 57.  As propostas culturais deverão apresentar ação de formação de plateia ou equivalente, em território brasileiro, com rubricas orçamentárias próprias, apresentada no Plano de Distribuição do projeto como produto acessório da atividade principal.

§ 1º  O mínimo de 50% (cinquenta) das ações de formação de plateia deverão ser destinadas a estudantes e professores de instituições públicas de ensino.

§ 2º  As atividades previstas nesse artigo deverão ser registradas por meio vídeográfico e disponibilizadas gratuitamente, em sua íntegra, na internet.

§ 3º  O número de estudantes e professores beneficiados pela ação de formação de plateia deve corresponder a 10% (dez por cento) do quantitativo de produtos culturais previstos no Plano de Distribuição. As propostas deverão contemplar o mínimo de 20 (vinte) beneficiários, podendo, a critério do proponente, se limitar a 1.000 (mil).

§ 4º  Projetos de formação ou que disponibilizem programas educativos deverão acrescentar ações de conscientização para importância da arte e cultura em suas atividades, em cumprimento ao disposto neste artigo.

**Comment by palomacmamede** [comment]
O que a gente responde sobre comercialização de ingressos: 

Do total de ingressos de um projeto cultural, a Lei Rouanet estabelece que a venda deve ser feita da seguinte forma:
        50% dos ingressos devem ser comercializadosa uma média de preço de R$225,00;
        Minimo de 10% deve ser vendido gratuitamente, com caráter social, educativo ou formação artística;
        Até 10% deve ser disponnibilizado gratuitamente pelos patrocinadores;
        Até 10% deve ser distribuido gratuitamente pelo proponente de forma a divulgar o projeto;
        Minimo de 20% dos ingressos deve ser comercializado em valores que não utrapassem R$75,00.

**Comment by palomacmamede** [comment]
Complicação do conteúdo: ele não está mapeado nos documentos enviados pelo MinC para a base de conhecimento da Tais

**Comment by palomacmamede** [comment]
O conteúdo foi testado e devidamente adicionado
