### ISSUE TITLE
Acrescentar tópico Como enviar a prestação de contas do projeto

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#244]
**Tarefas**

- [x] intent

**Testar**

- [x] como enviar a prestação de contas do projeto? 
- [x] como fazer prestação de contas? 
- [x] por qual meio eu apresento a prestação de contas? 
- [x] posso entregar a prestação de contas meio fisico? 
- [x] posso enviar a prestação de contas meio fisico?
- [x] quais os documentos fiscais válidos para a prestação de contas dos projetos?

**Critérios de aceitação**

- [x] O conteúdo funciona
- [x] Passou nos testes

**Comment by palomacmamede** [comment]
Também contempla a issue #269 
Como enviar a prestação de contas do projeto?; como fazer prestação de contas?; por qual meio eu apresento a prestação de contas?; posso entregar a prestação de contas meio fisico? posso enviar a prestação de contas meio fisico?; quais os documentos fiscais válidos para a prestação de contas dos projetos?; qual o periodo para prestar contas ?;

texto do processo de prestação de contas - janete ;)

**Comment by palomacmamede** [comment]
A Tais já responde esse conteúdo, sendo necessária apenas a atualização da intent **salic_preenchimento_comprovacao_financeira**

  _utter_salic_preenchimento_comprovacao_financeira:
    - text: |
          Olha, é preciso inserir a comprovação financeira a partir do momento que  o projeto começa a ser executado. Agora, vou te ajudar a fazer a sua comprovação na plataforma Salic: clique no menu "Comprovação Financeira" que está localizado na barra lateral. Nesse menu você terá acesso à planilha orçamentária para fazer a comprovação de cada um dos itens previstos. Sobre a comprovação de objeto, você só pode inserir os comprovantes após o final do período de execução do projeto,  é só clicar no menu "Comprovação de Objeto", localizado na barra lateral._
