### ISSUE TITLE
Configurar treinamento supervisionado

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#25]
Implementar treinamento supervisionado para melhorar a Rouana de forma interativa.
* Documentação [interactive_learning](http://rasa.com/docs/core/interactive_learning/)

**Comment by arthurTemporim** [comment]
Documentação http://rasa.com/docs/core/interactive_learning/

**Comment by MatheusFaria** [comment]
Vamos adiar por agora, seria interessante este treinamento suprevisionado ser atacado por alguma interface.
