### ISSUE TITLE
Resposta errada ao perguntar sobre o trabalho do ministério da cultura

### ISSUE THREAD

**Issue by rodrigocam** [lablivre-unb/tais#252]
Utilizei o comando #MEAJUDA e depois perguntei sobre o trabalho do ministério da cultura.
![tais](https://user-images.githubusercontent.com/12930004/48415128-b02eb700-e733-11e8-8d0c-cd325b393268.png)

Resposta errada
![tais](https://user-images.githubusercontent.com/12930004/48415216-ec621780-e733-11e8-818d-ab5f1d5b24ef.png)

**Critérios de aceitação**

- [ ] Perguntar sobre o trabalho do ministério da cultura e o bot responder um breve resumo.

**Comment by pablodiegoss** [comment]
Testando algumas outras formas de perguntar isso, descobri que ela sabe o que o é o MinC, mas depende da pergunta pra atingir uma resposta que faz sentido.

https://gist.github.com/pablodiegoss/d62e1f4003fef19ee9122391ff315e68

**Comment by RochaCarla** [comment]
Essa forma de perguntar sugerida pelo rodrigo foi inserido na base de conhecimento da Tais
