### ISSUE TITLE
Resposta errada ao perguntar como funciona a captação

### ISSUE THREAD

**Issue by rodrigocam** [lablivre-unb/tais#253]
Mandei "oi" e em seguida mandei "como funciona a captação?", eu acreditava que como estamos no contexto de lei rouanet, o bot entenderia que se tratava da captação de recursos, mas ele respondeu errado, perguntando o que mais eu queria saber.

**Critérios de aceitação**

- [ ] Perguntar "como funciona a captação?" ou algo parecido, sem mencionar "recursos" e o bot responder sobre como funciona  captação de recursos na lei rouanet.

**Comment by arthurTemporim** [comment]
Referente a #260
