### ISSUE TITLE
Resposta para Isenção de impostos/Recursos das empresas

### ISSUE THREAD

**Issue by pablodiegoss** [lablivre-unb/tais#254]
**Tarefas**

- [x]   Mapear perguntas dos usuários de conteúdo existente

- [x]  Implementar novos exemplos de intents

- [x] Documentar quais atualizações foram feitas

**Critérios de aceitação**

- [x]   As atualizações não diminuem a eficiência da Tais

- [x]  Os testes passaram

**Contribuição**
Uma dúvida comum sobre a Lei Rouanet é como o governo "gasta" o dinheiro nos projetos, faz a isenção de impostos e como as empresas ganham alguma coisa com o investimento.
Fiz alguns testes tentando verificar se a Taís conseguia responder este tipo de pergunta, não consegui descobrir nada sobre isenção de impostos ou esse não recolhimento de impostos do governo.

**Texto da Conversa**
https://gist.github.com/pablodiegoss/430bc832e0d5ac413a543a27c7f269ac

**Comment by pablodiegoss** [comment]
Aparentemente ela já tem implementado fluxos para isso, porém, não está funcionando ou sendo chamado de acordo

**Comment by palomacmamede** [comment]
**Perguntas dos usuários [teste]:**

_utter_lei_rouanet_origem_do_dinheiro_

- [x] como funciona o recolhimento de dinheiro para os projetos? 

- [x] como os projetos recebem dinheiro? 

- [x] como financiar um projeto cultural? 

- [x] quero saber sobre o dinheiro dos projetos?

- [x] quanto custa isso pro governo?

_utter_lei_rouanet_porcentagem_de_deducao_do_imposto_

- [x] como funciona a isenção fiscal das empresas?

- [x] como as empresas ganham alguma coisa ajudando meus projetos?

- [x] como funciona a isenção fiscal?
