### ISSUE TITLE
Rasa/Elastic - implementar funcionalidade de replay de conversas

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#257]
Ser capaz de visualizar o desempenho de conversas antigas no elastic seach. O problema que o replay vai ser feito na versao mais atual do pipeline de algoritmos, o que nao reflete a experiencia original do usuario.

**Tarefas**

- [ ] Implementar replay para conversas antigas

**Critérios de aceitação**

- [ ] É possível ver e analisar conversas antigas

**Comment by MatheusFaria** [comment]
Não será mais necessário
