### ISSUE TITLE
Fazer as stories de contexto

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#258]
Replicar fluxo "antigo" usando `stories` de contexto.

**Tarefas**

- [x] Cadastro de proposta
- [x] Explicação sobre SALIC
- [x] Funcionamento do processo

**Critérios de aceitação**

- [x] Utters funcionando
- [x] Novas intents necessárias criadas
- [x] `Intents` devem funcionar fora de contexto
- [x] Com deploy em beta

**Comment by RochaCarla** [comment]
Foi atualizado o makefile com o treino online (interactive learing) - o uso está detalhado no readme (Train Online). A ideia, além dos fluxos listados na issue, é usar o interactive learning para desenhar outros cenarios possiveis de uso/ocorrencia de intents genéricas a partir das respostas dados pelas utters
