### ISSUE TITLE
Testar evolução da Taís

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#262]
Pegar todos os problemas mapeados [aqui](https://github.com/lappis-unb/rouana/wiki/Intents-classificados-errado)

**Comment by RochaCarla** [comment]
A maior parte dos erros na identificação das intents foi resolvida com a mudança do pipeline NLU. As intents que continuaram dando erros, foram adicionadas os exemplos dos beta testes no arquivo de treinamento de intents. é necessário que esse trabalho de inserir exemplos de diferentes formas de perguntar uma intent seja feita de forma contínua (como fazer para automatizar?)
