### ISSUE TITLE
numero quantos projetos foram aprovados

### ISSUE THREAD

**Issue by fernao** [lablivre-unb/tais#267]
quantos projetos foram aprovados em 2017; Quantos projetos foram aprovados este ano?; quantos projetos foram aprovados na lei rouanet em 2018?; Quantos projetos foram aprovados pela Lei Rouanet em 2017?; Quantos projetos foram aprovados pela lei de incentivos em 2017?; Quantos projetos foram aprovados pela lei de incentivos em 2017?; Quantos projetos foram aprovados pela Lei Rouanet este ano?; quantos projetos foram aprovados para São Paulo?; quantos projetos foram ate 2018 lançados pelo ministério da cultura?; Quantos projetos foram reprovados no ano de 2017?; quantos projetos na cidade de belo horizonte?; Quantos projetos prestaram contas?; Quantos projetos são aprovados anualmente para captar?; Quantos projetos tem em execução em 2018?; quantos projetos tem no salic; quantos projetos captaram recursos em 2018?; Quantos projetos estão em prazo de execução?; Quantos projetos estão sem prazo de execução?;

Para obter essa informação atualizada, acessar o link sistemas.cultura.gov.br/comparar

**Comment by palomacmamede** [comment]
Conteúdo já existente:

utter_lei_rouanet_quantidade_de_projetos:
    - text: |
          Até o momento foram enviadas mais de 240.000 propostas, das quais mais de 89.000 foram aprovadas, se tornando projetos.
          Há mais de 43.000 proponentes cadastrados e mais de 80.000 incentivadores contribuindo com projetos.
          Além disso, mais de 69.000 fornecedores foram contratados pelos proponentes.
          Para consultar os projetos que já participaram, acesse: http://versalic.cultura.gov.br/
