### ISSUE TITLE
Democratizacao

### ISSUE THREAD

**Issue by fernao** [lablivre-unb/tais#270]
"Democratização de aceso formação de plateia; Olá Taís, gostaria de saber o que é democratização do acesso e formação de plateia; É obrigatória realizar a formação de plateia no projeto?; Formação de plateia, o que é?; É obrigatória realizar a formação de plateia no projeto? democratização de acesso?"

R - Formação de plateia - ações paralelas ao produto principal do projeto, mas que não são mais obrigatórias. Não ~e mais utilizado a partir da IN 5.

R - Democratização -  são medidas presentes na proposta cultural que promova ou amplie a possibilidade de fruição dos bens , produtos e ações culturais, em especial as camadas da população menos assistidas ou excluídas do exercício de seus diretos culturais por sua condição sócio econômica ou outras circunstancias (estão previstas nos artigos artigo 20/21 da IN)

**Comment by palomacmamede** [comment]
O conteúdo foi implementado
