### ISSUE TITLE
Como fazer a comprovação da despesa executada pelo proponente

### ISSUE THREAD

**Issue by fernao** [lablivre-unb/tais#271]
**Tarefas**

- [x] intent
- [x] utter
- [x] storie
- [x] testar

**Critérios de aceitação**

- [x] O conteúdo funciona
- [x] Passou nos testes

**Conteúdos**
Como fazer a comprovação da despesa executada pelo proponente?; como enviar a prestação de contas do projeto?; Como realizar a comprovação financeira?; Como realizar a comprovação?

O proponente deverá inserir a comprovação financeira a partir do momento em a movimentação financeira, que projeto está em execução, por meio do Menu "Comprovação Financeira", localizado na barra lateral do Salic. Ao acessar esse menu, o proponente terá aceso à planilha orçamentaria para fazer a comprovação de cada um dos itens previstos.

Quanto à comprovação de objeto, o proponente só poderá inserir os comprovantes após o final do período e execução do projeto, por meio do menu "Comprovação de Objeto", localizado na barra lateral

**Utter**
  _utter_salic_preenchimento_comprovacao_financeira:
    - text: |
          Olha, é preciso inserir a comprovação financeira a partir do momento que  o projeto começa a ser executado. Agora, vou te ajudar a fazer a sua comprovação na plataforma Salic: clique no menu "Comprovação Financeira" que está localizado na barra lateral. Nesse menu você terá acesso à planilha orçamentária para fazer a comprovação de cada um dos itens previstos.Sobre a comprovação de objeto, você só pode inserir os comprovantes após o final do período de execução do projeto,  é só clicar no menu "Comprovação de Objeto", localizado na barra lateral._

**Intents testadas**

- [x] como fazer a comprovação da despesa executada pelo proponente

- [x] como enviar a prestação de contas do projeto 

- [x] como realizar a comprovação financeira

- [x] como realizar a comprovação

**Comment by palomacmamede** [comment]
Também contempla a issue #276 

Como fazer a comprovação da despesa executada pelo proponente?; como enviar a prestação de contas do projeto?; Como realizar a comprovação financeira?; Como realizar a comprovação?

A comprovação financeira deve ocorrer a medida que as despesas forem efetuadas. Para tanto, o proponente deve acessar o menu lateral "comprovação financeira" em que aparecerá a planilha com os itens aprovados para a devida comprovação
