### ISSUE TITLE
como fazer uma readequação na planilha orçamentaria

### ISSUE THREAD

**Issue by fernao** [lablivre-unb/tais#272]
**Tarefas**

- [x] intents
- [x] utters
- [x] stories
- [x] criar stories de teste
- [x] testar

**Critérios de aceitação**

- [x] O conteúdo funciona
- [x] Passou nos testes

**Conteúdos**

como fazer uma readequação na planilha orçamentaria?; como fazer uma readequação no projeto?; Como readequar um projeto; readequação do projeto lei rouanet; Quando posso readequar o meu; Como fazer uma readequação no projeto?; projeto?;

Readequações devem ser solicitadas de forma individualizadas, nos campos apropriados no SALIC. E nunca no campo "Minhas Solicitações" ! 

Tipos de readequação permitidas: 
R - {
&emsp;Remanejamento até 50 %

&emsp;Planilha Orçamentária
&emsp;R - Requisitos
&emsp;&emsp;1 - O período de execução do projeto está vigente
&emsp;&emsp;2 - A conta esta liberada
&emsp;&emsp;3 - ter captado no mínimo 20% do valor aprovado no Incentivo Fiscal
&emsp;&emsp;4 - A planilha de remanejamento orçamentária de até 50%  não pode estar sendo editada/alterada pelo proponente
&emsp;&emsp;5 - Não pode alterar a etapa de custos vinculados (remuneração para captação de recurso, custos de administração do projeto, custos de divulgação de projeto)
&emsp;Como faz
&emsp;&emsp;1 - Acessar o Salic
&emsp;&emsp;2 - Menu lateral "readequação" submenu "planilha orçamentária"
&emsp;&emsp;3 - seleciona planilha orçamentária ou inserir uma nova planilha
&emsp;&emsp;4 - Editar/incluir e/ou excluir itens, além de fazer remanejamentos entre itens acima de 50%

&emsp;Alteração de Razão Social
&emsp;Agência Bancária
&emsp;Sinópse da Obra
&emsp;Impacto Ambiental
&emsp;Especificação Técnica
&emsp;Estratégia de Execução
&emsp;Local de Realização
&emsp;Alteração de Proponente
&emsp;Plano de Distribuição
&emsp;Nome do Projeto
&emsp;Período de Execução
&emsp;Plano de Divulgação
&emsp;Resumo do Projeto
&emsp;Objetivos
&emsp;Justificativa
&emsp;Acessibilidade
&emsp;Democratização de Acesso
&emsp;Etapas de Trabalho
&emsp;Ficha Técnica
&emsp;Saldo de Aplicação
&emsp;R - Somente é permitindo após a captação de 100%. O sistema só libera esse tipo de readequação quando ocorre a captação de 100% do valor aprovado . Caso não haja captação integral, não é necessário a anuência do Minc para a utilização do recurso.

&emsp;Transferência de recursos entre projetos
&emsp;R - Acontece em 3 casos
&emsp;&emsp;1 - Na fase de análise técnica do projeto, quando não for homologado (indeferido), será oportunizado ao proponente transferir os recursos captados deste projeto para outro. Casos excepcionais estão descritas na instrução normativas
&emsp;&emsp;2 - Antes de entrar em execução (liberação da conta), o proponente pode  transferir os recursos captados deste projeto para outro. Casos excepcionais estão descritas na instrução normativas
&emsp;&emsp;3 - Final de execução, o proponente pode transferir o saldo remanescente para outro projeto.
}

**Comment by palomacmamede** [comment]
Essa Issue será usada como teste do Guia de Conversação da Tais, #449 
Que será realizado segunda, 29/04 às 10:00.

**Comment by MatheusMiranda** [comment]
**Tais:**
Olha, quando for fazer a sua readequação lembre-se que elas devem ser solicitadas de forma individualizada, nos campos apropriados no SALIC. E nunca no campo "Minhas Solicitações" !

**Tais:** 
Gostaria que eu te explicasse os tipos de readequação?

**Usuário Guilherme:** 
Sim, eu gostaria muito, meu bem

**Tais:**
Sua readequação é sobre Planilha orçamentária ou sobre outra categoria?

**Usuário Guilherme:** 
É sobre planilha

**Tais:** 
Legal, então vamos lá:

Para Planilha Orçamentária, você pode fazer um remanejamento de até 50%. mas para isso é preciso cumprir os seguintes requisitos:

1 - O período de execução do projeto está vigente
2 - A conta esta liberada
3 - ter captado no mínimo 20% do valor aprovado no Incentivo Fiscal
4 - A planilha de remanejamento orçamentária de até 50% não pode estar sendo editada/alterada pelo proponente
5 - Não pode alterar a etapa de custos vinculados (remuneração para captação de recurso, custos de administração do projeto, custos de divulgação de projeto)

Pra fazer isso é só seguir os passos abaixo:

1 - Acessar o Salic
2 - Menu lateral "readequação" submenu "planilha orçamentária"
3 - seleciona planilha orçamentária ou inserir uma nova planilha
4 - Editar/incluir e/ou excluir itens, além de fazer remanejamentos entre itens acima de 50%

**Usuário Guilherme:**
E sobre outras categorias?

**Tais:**
As outras categorias de readequação só são permitidas após a captação de 100% do valor aprovado. Caso não haja captação integral, não é necessário a anuência do Minc para a utilização do recurso. Eu vou te mandar as categorias que se encaixam nessa regra, tá bom?
São elas:

- Alteração de Razão Social
- Agência Bancária
- Sinópse da Obra
- Impacto Ambiental
- Especificação Técnica
- Estratégia de Execução
- Local de Realização
- Alteração de Proponente
- Plano de Distribuição
- Nome do Projeto
- Período de Execução
- Plano de Divulgação
- Resumo do Projeto
- Objetivos
- Justificativa
- Acessibilidade
- Democratização de Acesso
- Etapas de Trabalho
- Ficha Técnica
- Saldo de Aplicação

**Usuário Guilherme**:
Obrigado, Tais.

**Tais**:
Por nada, é um prazer te ajudar :D

**Comment by brunapinos** [comment]
**utter_readequação**:
As readequações devem ser solicitadas de forma individualizadas, nos campos apropriados no SALIC. E nunca no campo "Minhas Solicitações".

Existem algumas readequações permitidas, como Remanejamento até 50%, Planilha Orçamentária, Alteração de Razão Social, Transferência de recursos entre projetos, entre outros. 
Se você quiser saber sobre os requisitos para realizar cada alteração e como fazer, pergunte algo como: "Como fazer a readequação da Planilha Orçamentária", e eu te responderei :) 

**utter_readequação_planilha**:
Olha, os requisitos para readequar a planilha orçamentária são:

* O período de execução do projeto está vigente
* A conta esta liberada
* Rer captado no mínimo 20% do valor aprovado no Incentivo Fiscal
* A planilha de remanejamento orçamentária de até 50% não pode estar sendo editada/alterada pelo proponente
* Não pode alterar a etapa de custos vinculados (remuneração para captação de recurso, custos de administração do projeto, custos de divulgação de projeto)

Se seu projeto atende esses requisitos, para fazer a readequação, você deve: 
  1 - Acessar o Salic;
  2 - Menu lateral "readequação" submenu "planilha orçamentária";
  3 - seleciona planilha orçamentária ou inserir uma nova planilha;
  4 - Editar/incluir e/ou excluir itens, além de fazer remanejamentos entre itens acima de 50%.

**Comment by KahCosta** [comment]
**utter_readequação:** 
Bom, as readequações devem ser solicitadas de forma individualizadas, nos campos apropriados no SALIC. E nunca no campo "Minhas Solicitações" ! Espero ter solucionado sua dúvida, caso contrário tente ser um pouco mais específico

**utter_tipos_readequação:**
Atualmente a readequação beseia-se no remanejamento de até 50 % da planilha orçamentária.

**utter_saber_readequar_planilha_orcamentaria:**
Para saber se a planilha necessita de readequação é bem fácil! Basta verificar os seguintes quesitos:
1 - Verificar se o período de execução do projeto está vigente
2 - Verificar se a conta esta liberada
3 - Ter captado no mínimo 20% do valor aprovado no Incentivo Fiscal
4 - A planilha de remanejamento orçamentária ter até 50%  e não estar sendo editada/alterada pelo proponente
5 - Não ter alterado a etapa de custos vinculados (remuneração para captação de recurso, custos de administração do projeto, custos de divulgação de projeto)

Caso não siga esses quesitos é necessário que ocorra uma reademação da planilha. 


**utter_readequacao_planilha:**
Vou te auxiliar na readequação de sua planilha orçamentária, para isso basta seguir o passo a passo abaixo:
1 - Acessar o Salic
2 - Menu lateral "readequação" submenu "planilha orçamentária"
3 - seleciona planilha orçamentária ou inserir uma nova planilha
4 - Editar/incluir e/ou excluir itens, além de fazer remanejamentos entre itens acima de 50%


**utter_quando_readequar:**
Então o sistema só libera esse tipo de readequação quando ocorre a captação de 100% do valor aprovado . Caso não haja captação integral, não é necessário a anuência do Minc para a utilização do recurso.

**utter_transferencia_recursos:**
Legal! Então, a transferencia de recursos ocorre em 3 casos
1 - Na fase de análise técnica do projeto, quando não for homologado (indeferido), será oportunizado ao proponente transferir os recursos captados deste projeto para outro. Casos excepcionais estão descritas na instrução normativas
2 - Antes de entrar em execução (liberação da conta), o proponente pode transferir os recursos captados deste projeto para outro. Casos excepcionais estão descritas na instrução normativas
3 - Final de execução, o proponente pode transferir o saldo remanescente para outro projeto.

**Comment by guilacerda** [comment]
**Tais**
&emsp;&emsp;Então, as readequações devem ser solicitadas individualmente nos campos apropriados no SALIC. E não se esqueça que nunca poderá ser solicitada no campo de "Minhas solcitações".

**Tais**
&emsp;Caso sua readequação seja sobre a Planilha Orçamentária, você pode fazer um remanejamento de até 50%, obedecendo os seguintes requisitos:

* O período de execução do projeto está vigente
* A conta esta liberada
* ter captado no mínimo 20% do valor aprovado no Incentivo Fiscal
* A planilha de remanejamento orçamentária de até 50%  não pode estar sendo editada/alterada pelo proponente
* Não pode alterar a etapa de custos vinculados (remuneração para captação de recurso, custos de administração do projeto, custos de divulgação de projeto)

**Pessoa**
&emsp; Mas como faço para submeter a readequação sobre a Planilha?

**Tais**
&emsp;  Então, você deve seguir os seguintes passos para conseguir submeter os remanejamentos desejados:
* Primeiramente acesse o Salic
* Em seguida, vá ao menu lateral e clique em "planilha orçamentária" que é submenu do tópico "readequação". 
* Agora selecione a planilha orçamentária desejada, ou insira uma nova planilha.
* Agora estará pronta para as opções de editar/incluir e/ou excluir itens, além de fazer remanejamentos entre itens acima de 50%;

**Comment by pablodiegoss** [comment]
__Utter de readequação__: 
Você pode realizar adequações ou alterações do projeto no próprio SALIC, nos campos apropriados e um de cada vez. Mas não utilize o campo "Minhas Solicitações" para isso, vou te explicar onde é!
<br>
Vá na página do SALIC e no menu lateral terá "readequação" e então "planilha orçamentária", daí selecione a planilha orçamentária ou inserir uma nova planilha. Lá você poderá editar, incluir e excluir itens, além de fazer remanejamentos entre itens acima de 50%
	
É possível remanejar até 50% da planilha orçamentária cumprindo os seguintes requisitos:
1 - O período de execução do projeto está vigente
2 - A conta esta liberada
3 - ter captado no mínimo 20% do valor aprovado no Incentivo Fiscal
4 - A planilha de remanejamento orçamentária de até 50% não pode estar sendo editada/alterada pelo proponente
5 - Não pode alterar a etapa de custos vinculados (remuneração para captação de recurso, custos de administração do projeto, custos de divulgação de projeto)	
		
__utter items para readequar__:
Nem todo item pode ser readequado, mas esses aqui podem:
* Alteração de Razão Social
* Agência Bancária
* Sinópse da Obra
* Impacto Ambiental
* Especificação Técnica
* Estratégia de Execução
* Local de Realização
* Alteração de Proponente
* Plano de Distribuição
* Nome do Projeto
* Período de Execução
* Plano de Divulgação
* Resumo do Projeto
* Objetivos
* Justificativa
* Acessibilidade
* Democratização de Acesso
* Etapas de Trabalho
* Ficha Técnica
* Saldo de Aplicação

__Utter de Transferência__:
Pra você transferir recursos entre projetos é necessário estar em uma de três condições:
* Na fase de análise técnica do projeto, quando não for homologado (indeferido), será oportunizado ao proponente transferir os recursos captados deste projeto para outro. Casos 	excepcionais estão descritas na instrução normativas.
* Antes de entrar em execução (liberação da conta), o proponente pode transferir os recursos captados deste projeto para outro. Casos excepcionais estão descritas na instrução normativas.
* Ao final de execução, o proponente pode transferir o saldo remanescente para outro projeto.
}

**Comment by RochaCarla** [comment]
Carla Rocha, [29.04.19 11:02]
As readequações da planilha orçamentária devem ser solicitadas de forma individualizadas. Dica, nunca peça readequação no campo "Minhas Solicitações" ! Olha como se faz o pedido de readequação orçamentária no SALIC:
1 - Acessar o Salic (sua senha normal)
2 - Menu lateral "readequação" -> submenu "planilha orçamentária"
3 - Selecione a planilha orçamentária ou insira uma nova planilha
4 - Agora você consegue editar os itens, além de fazer remanejamentos entre itens acima de 50%

Tem vários outros detalhes referentes à readequações orçamentárias, como
1 - Tipos de readequações (que só podem ser realizados após 100% da captação)
2 - Transferência de recursos entre projetos
3 - Regras gerais para pedir readequações na planilha orçamentária

E aí, quer se aprofundar em algum desses tópicos (é só digitar o número do item)? Ou me faça outra pergunta :P

**Comment by gabibguedes** [comment]
**utter_readequacao:**

Então, as readequações devem ser solicitadas individualmente, nos campos apropriados no SALIC, não use o campo "Minhas Solicitações". A lei permite alguns tipos de readequações, como remanejamento de até 50%, readequação da planilha orçamentária, transferencia de recursos entre projetos e entre outros. Está com alguma dúvida em como fazer uma readequação específica?

**utter_requisitos_readequacao_planilha_orcamentaria:**

Para fazer a readequação da planilha orçamentária o projeto tem de cumprir com alguns requisitos, o periodo de execução do projeto tem que estar vigente, a conta deve estar liberada, deve ter sido captado no minimo 20% do valor aprovado do incentivo fiscal, a planilha orçamentáriade até 50% não pode ter sido alterada e a etapa de custos vinculados não pode ser alterada.

**utter_como_faz_readequacao_planilha_orcamentaria:**

Aí para fazer a readequação, primeiro você deve accessar o salic, no menu lateral, procure "readequação" e no submenu, "planilha orçamentária", selecione planilha orçamentária ou inserir uma nova planilha. Espero ter te ajudado :)

**utter_readequacao_transferencia_de_recursos_entre_projetos:**

A transferência de recursos entre projetos pode acontecer em tres casos: 
Na fase de análise tecnica do projeto, quando não for homologado será oportunizado ao proponente transferir os recursos captados deste projeto para outro.
Antes de entrar em execução, na liberação da conta, o proponente pode transferir os recursos captados deste projeto para outro.
Ao final da execução, o proponente pode transferir o saldo remanescente para outro projeto.

**utter_readequacao_resto:**

Nesse caso somente é permitido a readequação após o termino da capacitação, porque o sistema só libera esse tipo de readequação depois de toda a captação do valor aprovado ter sido feita. Caso não haja captação integral, não é necessário a aceitação do Minc para a utilização do recurso.

**Comment by LeoSilvaGomes-zz** [comment]
**utter_readequação:**
     Para fazer uma readequação você precisa acessar o site do Salic e faze-la individualmente. Quando você estiver na página do Salic, é só seguir esses passos:
- Acessar o Salic
- Menu lateral "readequação" submenu "planilha orçamentária"
- seleciona planilha orçamentária ou inserir uma nova planilha
- Editar/incluir e/ou excluir itens, além de fazer remanejamentos entre itens acima de 50%
Agora que você já sabe como fazer uma readequação, você gostaria de saber o que é necessário?

**utter_readequação_requisitos:**
   Então, para fazer uma readequação é necessário:
- O período de execução do projeto está vigente.
- A conta esta liberada.
- Ter captado no mínimo 20% do valor aprovado no Incentivo Fiscal.
- A planilha de remanejamento orçamentária de até 50% não pode estar sendo editada/alterada pelo proponente.
- Não pode alterar a etapa de custos vinculados (remuneração para captação de recurso, custos de administração do projeto, custos de divulgação de projeto).
   Espero ter ajudado :)   

**utter_readequação_transferência:**
    A transferência ocorre em 3 casos:
 - Na fase de análise técnica do projeto, quando não for homologado (indeferido), será oportunizado ao proponente transferir os recursos captados deste projeto para outro. Casos excepcionais estão descritas na instrução normativas
- Antes de entrar em execução (liberação da conta), o proponente pode transferir os recursos captados deste projeto para outro. Casos excepcionais estão descritas na instrução normativas
- Final de execução, o proponente pode transferir o saldo remanescente para outro projeto.
Espero estar te ajudando !

**utter_readequação_permição:**
   Hhuuummm... então, somente é permitindo após a captação de 100%. O sistema só libera esse tipo de readequação quando ocorre a captação de 100% do valor aprovado . Caso não haja captação integral, não é necessário a anuência do Minc para a utilização do recurso.

**Comment by BrunaNayara** [comment]
**utter_readequacao_orcamentaria:**
Vamos lá. Vou te explicar os tipos de readequação que você pode fazer na sua planilha orçamentária. Mas, primeiro, me fala qual tipo de readequação você quer fazer. 
1 - Remanejamento de até 50% do orçamento
2 - Transferência de recursos entre projetos
3 - Alteração de algum outro dado

**utter_readequacao_50**
Legal! 
Para fazer essa readequação, você precisa cumprir alguns requisito. Vou te falar quais são.
1 - O período de execução do projeto está vigente
2 - A conta esta liberada
3 - ter captado no mínimo 20% do valor aprovado no Incentivo Fiscal
4 - A planilha de remanejamento orçamentária de até 50% não pode estar sendo editada/alterada pelo proponente
5 - Não pode alterar a etapa de custos vinculados (remuneração para captação de recurso, custos de administração do projeto, custos de divulgação de projeto)
Você cumpre esses requisitos? 

**utter_readequacao_50_passos**
Bom! 
Então vou te ensinar como fazer. Esses são os passos:
1 - Acessar o Salic
2 - Selecionar  "readequação" no menu lateral e "planilha orçamentária" no submenu
3 - Selecionar planilha orçamentária ou inserir uma nova planilha
4 - Editar/incluir e/ou excluir itens, além de fazer remanejamentos entre itens acima de 50%
