### ISSUE TITLE
Prazos

### ISSUE THREAD

**Issue by fernao** [lablivre-unb/tais#277]
analise de proposta
60 dias a apresentação da proposta pelo proponente - O Minc Faz

analise de técnica
30 dias apos o envio para analise - as viculadas fazem
exceção - projetos complexos e de patrimônio

readequação
30 dias para solicitações diversas e 60 para readequações orçamentarias

período de captação
36 meses a contar da data da publicação da portaria de autorização

prestação de contas
envio da prestação de contas via salic dev ocorrer em ate 60 dias apos a expiração do prazo de execução

diligencias
respostas de diligencia - 20 dias prorrogaveis por mais 20 dias

desarquivar proposta
nao tem prazos

**Tarefas**

- [x] Criar Utter 
- [x] Criar intent
- [x] Criar storie
- [x] Testar

**Critérios de aceitação**

- [ ] A Taís é capaz de responder esses tópicos no Beta
- [ ] O novo conteúdo não reduziu a precisão de resposta para outros tópicos
- [ ] Os gestores da SEFIC conseguem ver o que foi alterado a partir da página da Wiki
- [ ] Os beta-testers sabem o que foi alterado na Taís ao ler o Changelog e O que ela sabe responder do Beta ao serem publicados

**Comment by brunapinos** [comment]
Esta issue começou a ser resolvida no pull request #324, porém o esforço de refatoração deste PR seria maior que abrir um novo. Logo, a issue está ligada a um novo PR #339
