### ISSUE TITLE
qual a data para apresentar um projeto 

### ISSUE THREAD

**Issue by fernao** [lablivre-unb/tais#278]
qual a data para apresentar um projeto ?; qual a data para apresentação de projeto?;Data para iniciar um projeto;Qual a data para apresentar um projeto?

1 - Planos anuais -  de 1 fevereiro até 30 de setembro

2- demais - de 1 fevereiro 30 de novembro

O envio da proposta deve ocorrer com no minimo 90 dias antes do inicio da execução

**Tarefas**

- [x] Criar Utter 
- [x] Criar intent
- [x] Criar storie
- [x] Testar

**Critérios de aceitação**

- [x] A Taís é capaz de responder esses tópicos no Beta
- [x] O novo conteúdo não reduziu a precisão de resposta para outros tópicos
- [ ] Os gestores da SEFIC conseguem ver o que foi alterado a partir da página da Wiki
- [ ] Os beta-testers sabem o que foi alterado na Taís ao ler o Changelog e O que ela sabe responder do Beta ao serem publicados

**Comment by palomacmamede** [comment]
Falta testar o conteúdo

**Comment by palomacmamede** [comment]
É preciso entender quais são esses "demais casos".

**Comment by palomacmamede** [comment]
Em vista da resposta do FAQ, acho que cabe um modificação para a retirada desta especificação "demais casos".
Qual é o período do ano em que as propostas devem ser apresentadas ao MinC?

R – As propostas culturais podem ser apresentadas ao MinC de 1º de fevereiro a 30 de novembro de cada ano.
