### ISSUE TITLE
Como é feita a divulgação de patrocínio

### ISSUE THREAD

**Issue by fernao** [lablivre-unb/tais#285]
Como é feita a divulgação de patrocínio

é feito pelo material de divulgação do projeto cultural.

Marca doo patrocinador nas peças de divulgação do projeto.
Recebe uma cota de produtos/ingressos para utilizar na divulgação do projeto.

**Tarefas**

- [x] Criar Utter 
- [x] Criar intent 
- [x] Criar storie
- [ ] Testar

**Critérios de aceitação**

- [ ] A Taís é capaz de responder esses tópicos no Beta
- [ ] O novo conteúdo não reduziu a precisão de resposta para outros tópicos
- [ ] Os gestores da SEFIC conseguem ver o que foi alterado a partir da página da Wiki
- [ ] Os beta-testers sabem o que foi alterado na Taís ao ler o Changelog e O que ela sabe responder do Beta ao serem publicados

I -   Ações adicionais realizadas pelo patrocinador, pelos proponentes ou pelos   captadores destinadas à prospecção comercial, programas de relacionamento,   ampliação da divulgação ou promoção do patrocinador e de suas marcas e   produtos, desde que com a comprovada anuência do proponente e custeadas com   recursos não-incentivados;
II - Fornecimento de produtos ou serviços do incentivador ao   projeto cultural, desde que comprovada a maior economicidade ou   exclusividade;
III - Concessão de acesso a ensaios, apresentações, visitas ou   quaisquer atividades associadas ou não ao projeto cultural; e
IV - A comercialização de produtos e subprodutos do projeto   cultural em condições promocionais.

**Comment by palomacmamede** [comment]
@KahCosta  flor, só pra lembrar da issue do dialog flow
