### ISSUE TITLE
posso prorrogar o prazo para recurso na prestação de contas por omisao?

### ISSUE THREAD

**Issue by fernao** [lablivre-unb/tais#286]
**Tarefas**

- [x] Mapear se conteúdo já existe

- [x] Update de Intent já existente

- [x] Testar

**Critérios de Aceitação**

- [x] O conteúdo não altera a eficiência da Tais

- [x] Os testes passaram

**Conteúdo**

Pergunta: Posso prorrogar o prazo para recurso na prestação de contas por omissão?
Resposta: Não é possível

**Comment by palomacmamede** [comment]
utter_processo_prazo_prestacao_contas:
    - text: |
          Envio da prestação de contas via salic deve ocorrer em até 60 dias após a expiração do prazo de execução. Esse prazo não pode ser prorrogado.
