### ISSUE TITLE
Acrescentar tópico "Captacao como captar"

### ISSUE THREAD

**Issue by fernao** [lablivre-unb/tais#289]
**Tarefas**

- [ ] Acrescentar os tópicos na versão Beta da Taís
- [ ] Atualizar documentação do conteúdo da Taís em [Mensagens da Taís](../wiki/Mensagens-da-Taís), no *Changelog* e em *O que ela sabe responder* no Beta.

**Critérios de aceitação**

- [ ] A Taís é capaz de responder esses tópicos no Beta
- [ ] O novo conteúdo não reduziu a precisão de resposta para outros tópicos
- [ ] Os gestores da SEFIC conseguem ver o que foi alterado a partir da página da Wiki
- [ ] Os beta-testers sabem o que foi alterado na Taís ao ler o *Changelog* e *O que ela sabe responder* do Beta ao serem publicados

## Conteúdos

** Pergunta: Captacao como captar**

Mensagem:

o proponente deverá buscar pessoas físicas ou jurídicas interessadas em incentivar financeiramente  seu projeto.  Isso é feito Após a publicação do Diário Oficial da União, que autoriza a captação de recursos.

O valor do incentivo poderá ser integral ou parcialmente deduzido no Imposto de Renda ;)

**Comment by palomacmamede** [comment]
A Taís já responde esse conteúdo

utter_captacao_como_captar:
    - text: |
          Para captar os recursos você deve achar incentivadores. Assim que o projeto é publicado no Diário Oficial da União você pode começar a captar recursos. Esse é parte das atribuições do proponente e não há participação do MinC.
