### ISSUE TITLE
Primeiro Medium Lappis - Tais

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#298]
Redação dos primeiros posts sobre o trabalho realizado na Tais!

**Tarefas**

- [ ] Apresentação do projeto Tais - quais os objetivos, quais os desafios, quais as metas -- @ricardopoppi 

- [ ] Inglês - Arquitetura chatbot (RasaNLU, Rasa Core, Elastik, rocket.chat) + estudo de caso tais  @MatheusFaria & @arthurTemporim  (registrar experiência GSOC)

- [ ] Inglês - Como construir um chatbot de qualidade no RASA - Tutorial (etapas) - @brunapinos + @arthurTemporim + @palomacmamede 

- [ ] Inglês - Tutorial como funciona o pipeline RASA -- importância dos algos e hiperparâmetros -- @RochaCarla @diegodorgam 

- [ ] Inglês - Utilizando notebooks para avaliar o chatbot RASA --  @KahCosta @gabibguedes 

**Critérios de aceitação**

- [ ] Texto completo, revisado, disponível na wiki 

- [ ] Conteúdo completo e com as devidas referências

**Comment by RochaCarla** [comment]
https://medium.com/swlh/chatbots-were-the-next-big-thing-what-happened-5fc49dd6fa61

**Comment by RochaCarla** [comment]
https://chatbotslife.com/our-experience-building-chatbots-with-rasa-tuning-the-nlu-pipeline-74a80cd565b8

**Comment by gabibguedes** [comment]
Utilizando notebooks para avaliar o chatbot RASA --> https://docs.google.com/document/d/1tJkMctv9UXWcAuSC7SeunUSKaJIBSbxAbAny0W1YZpA/edit?usp=sharing

**Comment by brunapinos** [comment]
[Fluxo de Chatbot: Mostre ao usuário o que ele quer](https://docs.google.com/document/d/1Jw4Jqa9SJbh5uGg6egMxa8RuTQQK81NHnRozhPk5V9k/edit?usp=sharing)

**Comment by palomacmamede** [comment]
[Encantando pessoas: poder da personalidade](https://docs.google.com/document/d/12V9KOKEyDtNCXGG5UEscAuPSdHZpjI6nCvY9PUH-Yus/edit?usp=sharing)
