### ISSUE TITLE
implementar testes de dialogo

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#310]
Implementar testes de dialogos na Tais usando a funcionalidade evaluate do rasa core..

https://rasa.com/docs/core/evaluation/

- [x]  Criar stories com fluxos, no qual os textos são exemplos não encontradas na base de treinamento
- [ ]  ~Colocar a execução de testes no pipeline da Tais~
- [ ] ~Documentar na wiki da Tais o funcionamento dos testes do Rasa Core~

**Comment by LeoSilvaGomes-zz** [comment]
### Estudo de "Evaluating and Testing" do Rasa

* Foi utilizado como ferramenta de estudo a wiki disponibilizado pelo Rasa (https://rasa.com/docs/core/evaluation/#evaluation), no qual se teve conhecimento da utilidade e de como deve ser ministrado.
* O documento em si, relata as formas disponíveis que a plataforma nos oferece de avaliação, onde avalia um modelo já treinado com o conjunto de histórias de teste, e no outro usa em conjunto o RASA NLU para analisar as mensagens de intenção. Sendo nossas exigências o caráter de avaliação do fluxo com relação as intenções, escolheu-se a segunda  opção, onde se pré define mensagens no formato no formato do usuário e correlacionando-os com as utters de acordo com as intenções.

![image](https://user-images.githubusercontent.com/38738836/53493800-0291aa80-3a7b-11e9-82d6-1ba0f6530747.png)

**Comment by LeoSilvaGomes-zz** [comment]
### Uso da teste e sua funcionalidade dentro do projeto

* Sabe-se que o teste do Rasa nos possibilita avaliar o fluxo de ponta a ponta, com as intenções pré definidas pelo mesmo, desta forma, ele nos disponibiliza uma forma de visualização desse teste no qual ele nos fornece:
  * "precision" - precisão de correlação ao exemplo do Rasa NLU com a intent.
  * "recall" - porcentagem de respostas que corresponderam a utter esperada.
  * "f1-score" - a porcentagem de relação da precisão com o recall, sendo (2x precisão x recall) / (precisão + recall)
  * "support" - o tanto de vezes que teste utiliza o componente.

![image](https://user-images.githubusercontent.com/38738836/53496480-e1cc5380-3a80-11e9-85e0-24fd4dd344b8.png)

* Desses dados gera uma matriz pelo script que permite visualizar a distribuição de confiança para todas as previsões


![image](https://user-images.githubusercontent.com/38738836/53496994-f4935800-3a81-11e9-99df-cbd19f1af336.png)
