### ISSUE TITLE
Estudo do Rasa 12.04

### ISSUE THREAD

**Issue by MatheusMiranda** [lablivre-unb/tais#314]
Subir um bot com a versão 12.04 do Rasa, e testar a utilização de Custom Actions, Testes de Aceitação, slots, e nova Policy Embeddings.

**Tarefas**

- [ ] A partir do número de PRONAC acessar a API do SALIC e mostrar algo do projeto;
- [ ] Implementar storie utilizando novo recurso da Policy do Embeddings;
- [ ] Fazer teste de aceitação para essa história.

**Critérios de aceitação**

- [ ] Documentar o funcionamento de todas as novas funcionalidades na WIKI, e garantir que todos os membros da equipe conseguem utilizá-las a partir da documentação.

**Comment by brunapinos** [comment]
Atualizei a versão do Rasa core e rasa nlu na branch `rasa_version`. Tirei também as variáveis de ambiente que não são mais necessárias, pois são de fácil modificação

**Comment by arthurTemporim** [comment]
A versão do Rasa foi atualizada para a versão `13.0.1` e foi resolvida #312

**Comment by arthurTemporim** [comment]
A policy embeddings foi dividida para a issue #327

**Comment by arthurTemporim** [comment]
A issue de custom action foi movida para #331

**Comment by arthurTemporim** [comment]
Esta issue foi dividida nas issues comentadas anteriormente.
