### ISSUE TITLE
Preparar Webinar para o dia 23/01

### ISSUE THREAD

**Issue by MatheusMiranda** [lablivre-unb/tais#315]
Breve comentário sobre o contexto e descrição da issue.

**Tarefas**

- [x] Criar base da TAIS;
- [x] Criar panfleto da apresentação;
- [x] Criar roteiro de apresentação;
- [x] Divulgar webinar;
- [x] Testar links, computadores, funcionamento do bot.

**Critérios de aceitação**

- [x] Tudo está pronto, testado e divulgado.

**Comment by arthurTemporim** [comment]
O repositório de base foi criado, [rasa-boilerplate](https://github.com/lappis-unb/rasa-boilerplate).

**Comment by RochaCarla** [comment]
Foi lindo galera!

webinar disponível em [aqui](https://youtu.be/tW4x-R82hNc)
