### ISSUE TITLE
Atualização de Intent lei_rouanet_quem_pode_ser_proponente

### ISSUE THREAD

**Issue by palomacmamede** [lablivre-unb/tais#316]
Foi observado que o vocabulário dos usuários está em divergência com o vocabulário usado nesta intent.

**Tarefas**

- [x] Atualizar a intent, adicionando novas formas de perguntar
- [x] Garantir que as mudanças não baguncem o vocabulário das outras intents
- [x] observar outras intents que podem ser atualizadas

**Critérios de aceitação**

- [ ] Testar
- [ ] O novo conteúdo não reduziu a precisão de resposta para outros tópicos

**Comment by arthurTemporim** [comment]
Ta em qual PR/branch?

**Comment by arthurTemporim** [comment]
Esse conteúdo já está na `devel`
