### ISSUE TITLE
Tais pergunta e não entende a resposta

### ISSUE THREAD

**Issue by BrunaNayara** [lablivre-unb/tais#318]
A Tais faz uma pergunta, e não entende a resposta.

T: "Mas, antes de tudo, para que a nossa conversa seja mais eficiente,
gostaria de te fazer uma pergunta, você já submeteu uma proposta?"
eu: "não"
T: "Por enquanto, só entendo perguntas completas. Então é melhor você me perguntar "como funciona a Lei Rouanet" ao invés de "Como funciona" "

**Comment by palomacmamede** [comment]
Faltava "não" com o acento na intent negar. Já foi corrigido na branch resolution õ//

**Comment by arthurTemporim** [comment]
A branch resolution já foi feito o merge no PR #322
