### ISSUE TITLE
Testar DialogFlow para automatizar criação de histórias

### ISSUE THREAD

**Issue by MatheusMiranda** [lablivre-unb/tais#328]
Testar viabilidade de utilizar o Dialog Flow para criar intents, históries e utter de forma mais fácil.

**Tarefas**

- [ ] Criar um exemplo funcional de utilização do Dialog Flow com o Lappisudo. 

**Critérios de aceitação**

- [ ] Documentação da Tais atualizada, explicando como utilizar o Dialog Flow com o Rasa.

**Comment by KahCosta** [comment]
O *DialogFlow* consiste em uma ferramenta que possibilita a criação de *intents e utters* de maneira simples, por meio da utilização da assistente virtual do google que oferece uma interface que possui uma boa usabilidade levando em conta o interesse em facilitar a criação de conteúdos para a *Taís*. É necessário que o agente (usuário) realize login por meio de uma conta do google e assim realize a criação nos espaços indicados de *intents e utters*, porém foi observado que a ferramenta apresenta algumas limitações quanto a integração com o *Rasa*. A princípio foi estudado a possibilidade de utilização da ferramenta na automatização da criação de *intents, utters e stories* assim como a adição correta no arquivo domain. O *DialogFlow* possibilita apenas a criação de intents e utters deixando a desejar no quesito de criação de *stories*, assim como o fato de possibilitar apenas uma forma de exportar os dados que é por meio de arquivos .json
No momento em que o usuário exporta os dados ele tem a opção de escolher como compactar seus arquivos, em seguida é feito o download de uma pasta contendo:

**Entities:** Arquivos .json que possui as entidades que o *DialogFlow* foi treinado para extrair
**Intents:** Arquivos .json que possui as intenções no qual o *DialogFlow* foi treinado para entender
**Agente.json:** Arquivo que contém as configurações do *DialogFlow*
**Package.json:** Arquivo que contém as configurações do software utilizado para a construção da assistente.

Foi estudado a possibilidade de integração com o *Rasa* por meio da análise da aplicação realizada em um bot que trabalha com a identificação de locais próximos ao usuário, porém a integração entre o *DialogFlow* e o *Rasa* neste repositório baseia-se apenas na inserção do conteúdo que foi extraído por meio do *DialogFlow* nos arquivos pertencentes ao bot de forma manual sendo eles *intents, actions e entidades* no formato .json

Logo, existem alguns impecilios que nos levam ao estudo de uma próxima ferramenta que seja mais satisfatória e eficiente na construção de conteúdos da *Taís*, devido ao fato de que uma vez feita a integração, seria necessario modificar todos nossos arquivos de treinamento existentes como *intents e utters* que estão em markdown para o formato .json (único formato disponível para exportação no *DialogFlow*) e estrutura do arquivo *Domain* assim como a inabilidade diante da problemática de automatização da criação de *stories*, uma vez que sua única contribuição para a construção da mesma é a disponibilização do log de conversas entre bot e usuário.
