### ISSUE TITLE
Estudo sobre automatização da criação de intents, utters e stories por meio da ferramenta Amazon Lex

### ISSUE THREAD

**Issue by KahCosta** [lablivre-unb/tais#329]
Estudar a viabilidade de automatizar a criação de intents, stories e utters por meio da utillização da API de operações de criação de modelos da Amazon Lex.

**Tarefas**

- [ ] Ver como funciona o console do Amazon Lex que permite q construção de um bot pronto para produção.
- [ ] Ver como integrar o Rasa com a operação da API de tempo de execução do Amazon Lex.
- PostText
- [ ] Estudar como funciona a criação de funções do lambda para uso das intents.
- [ ] Estudar as operações da API de modelos : 
- CreateIntentVersion
- CreateSlotTypeVersion (Uma vez que temos a intenção de aplicar o uso de slots)
- GetIntent e GetIntents
- GetSlotType e GetSlotTypes
- GetBotChannelAssociation e GetBotChannelAssociations
- [ ] Ver a aplicabilidade da API de modelos de criação para criação de uma ferramenta que exclui automaticamente versões antigas quando o bot se aproxima do limite.

**Critérios de aceitação**

- [ ] Documentação da Tais atualizada, explicando como utilizar a API do Amazon Lex com o Rasa.

**Comment by KahCosta** [comment]
A princípio o teste da ferramenta pode ser feito de forma gratuita, porém é necessário reallizar o cadastro de um cartão de crédito pois haverá cobrança se for ultrapassado os Limites do nível gratuito da AWS.
Logo deve ser analisado a viabilidade com relação ao custo de utilização e o quanto a integração com o Rasa ultrapassaria do nível que é liberado.

**Comment by KahCosta** [comment]
Caso, após o estudo detalhado da aplicabilidade desta ferramenta não for possível obter resultados satisfatórios quanto a integração da mesma com o Rasa, segue um link que possui uma lista de ferramentas alternativas que podem vir a apoiar o processo de automatização.
[Alternativas de ferramentas para automação](https://alternativeto.net/software/api-ai/)

**Comment by arthurTemporim** [comment]
Como tem a questão de cadastro de cartão de crédito o estudo feito já é o suficiente.
