### ISSUE TITLE
Adicionar Usuário para visualização do Kibana

### ISSUE THREAD

**Issue by brunapinos** [lablivre-unb/tais#340]
Criar um usuário com somente a permissão de visualizar o dashboard do Kibana.

**Comment by brunapinos** [comment]
Para criar diferentes usuário, é necessário a versão paga da stack do Elastic, como mostra [aqui](https://www.elastic.co/subscriptions)

**Comment by arthurTemporim** [comment]
O gerenciamento de usuários com o Kibana é uma feature da versão paga, mas é possível utilizar um `iframe` fornecidos por eles para permitir apenas a visualização dos dados por outros usuários.
Logo seria necessário a criação/configuração de uma aplicação web para acesso dos dashboards do nosso `kibana`.

Pra fazer isso é só clicar na aba `share` dentro do dashboard desejado e copiar a código do `iframe`.

**Comment by arthurTemporim** [comment]
A issue #360 deve implementar a página de acesso.
