### ISSUE TITLE
Avaliar interfaces de edição de conteúdo

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#343]
Estudar a fundo ferramentas de edição de conteúdo de `chatbots` que podem ser utilizadas.

**Tarefas**

- [x] Pesquisar a ferramenta
- [x] Levantar prós e contras de cada ferramenta
- [x] Viabilidade de cada ferramenta

**Critérios de aceitação**

- [x] Decidir qual ferramenta será escolhida ou se será necessário criar uma do 0
- [x] Planejar a evolução/criação da ferramenta

**Comment by arthurTemporim** [comment]
@arthurTemporim Estudar a fundo [Articulate](https://github.com/samtecspg/articulate)
@KahCosta Estudar a fundo outras opções
@BrunaNayara Estudar a fundo dificuldades de criar uma ferramenta do 0

**Comment by arthurTemporim** [comment]
O estudo deve ser documentado [aqui](https://github.com/lappis-unb/tais/wiki/estudo-de-ferramentas-de-gerenciamento-de-conteudo)

**Comment by KahCosta** [comment]
**Ferramenta Estudada:** Xenioo

**Sobre a ferramenta:** A ferramenta Xenioo permite a criação de um bot do zero assim como a criação por meio de templates já existentes! A ferramenta possui uma interface intuitiva devido ao fato da criação de intents e utters se darem por meio de caixas de diálogo no qual uma caixa é setada a outra dependendo do fluxo de conversa e da resposta do usuário! Todo o manuseio da criação se dá por meio da ação de arrastar um diálogo ao outro e apontar as setas para as caixas seguintes de diálogo. A partir do momento em que o usuário clica na caixa é aberta uma aba lateral que possui os campos e edição de conteúdo que permite ao usuário criar os diálogos assim como inserir campos de entrada ou botões.

**Prós:**
- Adição de conteúdo
- Edição de conteúdo
- Remoção de conteúdo
- Aplição de utter de forma intuitiva de acordo com a resposta do usuário
- Facilidade de linkar (criar stories) por meio de setas entre caixas de diálogo
- Permissão para clonar utters afim de não ter retrabalho
- Caixa de diálogo relacionada a fallback
- Criação de intents e entidades
- É oferecido um token para realizar integração
- Opensource [Aqui](https://github.com/xenioo/chatbot-landers/tree/master/1)

**Contras:**
- O plano Free restringe um total de 1000 mensagens por mês
- O plano Free restringe uma grande quantidade de serviços como criação de intents entre outros ...
- Não é possivel entender como são exportados os dados e como funciona integração pelo fato de que o plano Free permite apenas que se teste como é feito a criação, edição e remoção.

Logo, a viabilidade de utilização da ferramenta será se basear no código fonte citado acima para evoluir e adaptar as nossas necessidades devido a ferramenta oferecer uma interface intuitiva e de fácil utilização.

**Comment by KahCosta** [comment]
Criei uma nova issue para especificar o que será feito quanto ao estudo de ferramentas alternativas para o Articulate.
Issue #361

**Comment by arthurTemporim** [comment]
Após reunião a decisão tomada foi a de implementação de uma plataforma nova.
