### ISSUE TITLE
Melhorar testes automatizados do Rasa Core

### ISSUE THREAD

**Issue by MatheusMiranda** [lablivre-unb/tais#346]
Os testes do Rasa Core são simples, e não tem uma boa visualização dos resultados.

**Tarefas**

- [ ] Melhorar feedback para os testes que falharam/passaram;
- [ ] Melhorar matriz de confusão;
- [ ] Melhorar visualização dos parâmetros de saída(Separar 'utters' de 'intents');
- [ ] Adicionar novas informações utéis para output de testes, se basear nos outputs do `pytest` e no `rspec`;

**Critérios de aceitação**

- [ ] Issue aberta no repositório do Rasa Core;
- [ ] PR aberto com a contribuição;
- [ ] Atualização dos testes da Tais para o novo formato;

**Comment by arthurTemporim** [comment]
@MatheusMiranda Atualiza a issue, por favor.
