### ISSUE TITLE
Livechat Rouana - identidade visual

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#36]
- [x] A Rouana está sem "foto" de perfil. 

- [x] O livechat está com a idv do rocket.chat

- [x] As informações da Rouana (contato) estão erradas

**Comment by MatheusFaria** [comment]
@MatheusMiranda tem que ver se tem como colocar isso no script de deploy

**Comment by MatheusMiranda** [comment]
Como são todas configurações do RocketChat, vou ver se é possível fazer tudo via API. Nesse caso, daria pra adicionar um script ao serviço da "página de homologação".

**Comment by MatheusFaria** [comment]
Digo o script de configuração do bot que [já existe](https://github.com/lappis-unb/rouana/blob/master/scripts/bot_config.py)

Caso não dê pra fazer nele, creio que a melhor abordagem seja configurar na mão toda vez. Mas acho que tem como porque o `catbot` do rocket faz isso de alguma forma
