### ISSUE TITLE
Criar página de acesso para dashboards do kibana

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#360]
Ter uma página de acesso ao `dashboard` do kibana com validação de usuário

**Tarefas**

- [x] Criar um `dashboard` no kibana
- [x] Implementar validação de usuário
- [x] Cadastrar usuários novos
- [x] Desenvolver um layout para a página
- [x] Implementar o layout

**Critérios de aceitação**

- [x] Ter página de acesso aos `dashboards` necessários com cadastro de usuários na infra do MINC.
- [x] A página está compreensível

**Comment by arthurTemporim** [comment]
A #340 tem uma descrição de como exportar o dashboard

**Comment by guilacerda** [comment]
Já foi criado a aplicação web com o mesmo dashboard "TaisBeta" do Kibana para a Secretaria. Foi decidido que subiremos uma instância para o MinC, mesmo sem nenhuma aplicabilidade para eles, porque são dados de difícil compreensão e abstração.

Vamos seguir com a estratégia de ir atualizando ele aos poucos enquanto evoluímos com as visualizações úteis ao MinC

**Comment by guilacerda** [comment]
Novas tasks

- [ ] Adaptar o design para a identidade visual da Taís
- [ ] Separar os dashboards em abas

**Comment by AniaGomes** [comment]
![image](https://user-images.githubusercontent.com/40863789/54941845-99cc0f80-4f0c-11e9-88a6-66f834f01ebb.png)

![image](https://user-images.githubusercontent.com/40863789/54946467-e1f02f80-4f16-11e9-8451-3c03db557595.png)

![image](https://user-images.githubusercontent.com/40863789/55247687-09047500-5227-11e9-9c69-f6e3a32b114b.png)

Fontes usadas:
Segoe UI regular, semibold, italic e smallcaps regular

Cores usadas:
#384356
#2da082
#68c171
#898989
#c95050

Imagem de fundo:
![geometrica1](https://user-images.githubusercontent.com/40863789/54635673-7f54ea80-4a63-11e9-8bfa-5584955a27ae.png)

Ícones:
[icones_visualizacao.zip](https://github.com/lappis-unb/tais/files/3004761/icones_visualizacao.zip)

![kibana-logo-color-v](https://user-images.githubusercontent.com/40863789/55247735-20dbf900-5227-11e9-9885-f149e97ac587.png)

![geometrica2](https://user-images.githubusercontent.com/40863789/55247825-57197880-5227-11e9-9dca-f580485304ac.png)

Ícones Brancos:
[Icones_kibana.zip](https://github.com/lappis-unb/tais/files/3029471/Icones_kibana.zip)

**Comment by guilacerda** [comment]
Quando gerado uma página web com o iframe de algum dashboard é requisitado o usuário e senha do próprio kibana. Temos que pensar em uma estratégia para não fazer essa requisição.

**Comment by guilacerda** [comment]
**Tarefas**

- [x] Fazer o layout da página após o usuário ter logado

**Comment by guilacerda** [comment]
Está faltando adicionar somente o link dos dashboards no dropdown

**Comment by AniaGomes** [comment]
Ícone de usuário:
[icone_usuario1.zip](https://github.com/lappis-unb/tais/files/3029505/icone_usuario1.zip)

**Comment by AniaGomes** [comment]
Ícone de aviso modificado:
[icone_aviso.zip](https://github.com/lappis-unb/tais/files/3029628/icone_aviso.zip)
