### ISSUE TITLE
Problema no continuar conversa

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#363]
O bot não se comporta corretamente quando tem o objetivo de manter conversa porque algumas utters são perguntas do tipo "sim ou não", o que induz as pessoas a responderem "sim ou não" ao invés de fazer uma nova pergunta para manter a conversa.

**Tarefas**

- [x] Substituir as utters com perguntas que precisem de "sim ou não" por perguntas abertas. Ex: *O que você gostaria de saber* ao invés de *Quer saber mais coisas*?

**Critérios de aceitação**

- [x] O usuário ser capaz de permanecer em uma conversa.

**Comment by palomacmamede** [comment]
Possível solução:

  utter_continuar_conversa:
    - text: |
          O que mais você gostaria de perguntar?
    - text: |
          Em que mais posso te ajudar?
    - text: |
          Qual a sua próxima dúvida?
    - text: |
          Qual o próximo tema te interessa?
    - text: |
          O que mais você deseja saber?
    - text: |
          O que mais você gostaria de saber?
    - text: |
          O que mais você deseja perguntar?
