### ISSUE TITLE
Melhorias de fluxo da Tais

### ISSUE THREAD

**Issue by LeoSilvaGomes-zz** [lablivre-unb/tais#365]
Algumas utters possuem uma pergunta ao final do texto, e como haverá uma pergunta da utter manter conversa, a Tais acaba fazendo duas perguntas.

* Os processos serão comentados com as utters que possuem uma pergunta após a outra

**Comment by LeoSilvaGomes-zz** [comment]
## Processo 1
* cumprimentar 
    - utter_cumprimentar 
* processo_como_funciona 
    - utter_processo_como_funciona
    - utter_continuar_conversa

**Comment by palomacmamede** [comment]
É preciso melhoras as intents de explicação sobre as etapas de projeto. 
Exemplo: #analisetecnica.

**Comment by LeoSilvaGomes-zz** [comment]
É preciso melhoria utter_tudo_bem, já que a Tais está fazendo duas perguntas, uma no final e outra no inicio

**Comment by LeoSilvaGomes-zz** [comment]
Closed issue:

- Os erros citados nessa issue já foram solucionados
- Não há necessita de aprofundamento na issue (sendo necessidade de continuidade)

Se houver problemas com o mesmo vies, deve-se criar um nova issue
