### ISSUE TITLE
[DASHBOARDS] Visualizar Dashboards existentes

### ISSUE THREAD

**Issue by MarcosEllys** [lablivre-unb/tais#371]
Primeiramente parabéns pelo projeto, a Tais é um projeto nacional com uma stack poderosa em docker, no entanto, não há uma forma simples de visualizar os dashboards do kibana após instalar toda stack. 

**Tarefas**

- [x] Exportar os dashboards do kibana para rodarem automaticamente ou manualmente.

**Comment by BrunaNayara** [comment]
Essa issue vai ser feita nessa sprint. Tá na issue #411

**Comment by brunapinos** [comment]
Essa issue foi concluida no PR #440 e a explicação de como subir está no README.md
