### ISSUE TITLE
[Perfil de Usuário] Quantidade de #MEAJUDA por sessão

### ISSUE THREAD

**Issue by brunapinos** [lablivre-unb/tais#373]
Filtrar a **quantidade de #MEAJUDA** por sessão

**Tarefas**

- [x] Analisar se já existe um _endpoint_ no Kibana
- [x] Criar uma legenda para a visualização
- [x] Utilizar melhor visualização 

**Critérios de aceitação**

- [ ] Está implementado em um dashboard separado
- [ ] A visualização está auto-explicativa
- [ ] A legenda está compreensiva para todo tipo de usuário

**Comment by guilacerda** [comment]
Não conseguimos com os endpoints que temos obter a informação. Decidimos por enquanto utilizar a quantidade total de usuários que já usou a #meajuda.

**Comment by guilacerda** [comment]
Conseguimos representar corretamente a visualização a partir do gráfico de pizza.

**Comment by guilacerda** [comment]
Estudando melhor o gráfico que geramos, vimos que estava com dados falsos. Gerávamos um gráfico de pizza que um pedaço seria o valor de 714, que é a quantidade de pessoas que já falaram #meajuda com a Tais e o pedaço restante mostrava o valor de 4142. Porém, esse valor representa a quantidade total de usuários. 

Concluímos que as mesmas pessoas que mandaram mensagem #meajuda, também mandou mensagem diferentes da hastag. Com isso, o Kibana contava o mesmo usuário na pedaço da pizza que mostrava o #meajuda e no pedaço que mostrava o restante dos usuários. Assim, voltamos a ideia de mostrar somente o valor total de usuários que entraram na hastag me ajuda.
