### ISSUE TITLE
Evoluir a organização da Tais para melhorar a receptividade de contribuidores

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#379]
Alguns potenciais contribuidores/colaboradores estão relatando que o repositório da Tais tem uma grande barreira de entrada. 

**Tarefas**

- [x] Atualizar o Readme para contemplar os padroes de boas comunidades de software livre
- [x] Fazer o documento de contribuição
- [x] Organizar as issues para contemplar "good first issue" tanto de conteúdo quanto de desenvolvimento
- [ ] ~Deixar o roadmap disponível para contribuidores~
- [x] Fazer documento com as lista de dependências das licenças (exemplo https://libraries.io/github/RasaHQ/rasa_nlu)

**Critérios de aceitação**

- [ ] Desenvolvedores externos são capazes de compreender o projeto e ser capaz de contribuir

**Comment by arthur0496** [comment]
Eu dei uma revisada no que foi feito até agora e tenho algumas observações e sugestões de melhorias:
* Tanto no [readme](https://github.com/lappis-unb/tais#tais---assistente-virtual-da-cultura) quanto no [conheça a Tais](https://github.com/lappis-unb/tais/wiki#quem-%C3%A9-a-tais) são feitas menções a plataforma Salic, mas não encontrei nada explicando o que é o Salic(A mesma coisa acontece com a lei rouanet), talvez valha a pena escrever um pequeno resumo ou pelo menos colocar um link para algum lugar que os explique.
* O [readme](https://github.com/lappis-unb/tais#tais---assistente-virtual-da-cultura) apresenta o link [Teste a tais em produção](http://rouanet.cultura.gov.br/) eu não conhegui interagir com a Tais(não sei se o link esta errado ou se fui eu que não consegui achar). 
* No [readme](https://github.com/lappis-unb/tais#tais---assistente-virtual-da-cultura), quando são mencionadas as tequinologias utilizadas(Rasa, Kibana, Rocket Chat e outras) seria interessante deixar mais visível os links para os repositorios delas(eu vi esse links estão isso no link para a lista de dependencias no final do readme, mas achei muito escondido).
* No [Como conseguir ajuda](https://github.com/lappis-unb/tais#como-conseguir-ajuda) é dito que "Parte da documentação técnica do framework da Tais está disponível na [wiki do repositório](https://github.com/lappis-unb/tais/wiki). Caso não encontre sua resposta, abra uma issue que tentaremos responder o mais rápido possível.", eu acredito que a wiki do repositorio não esta suficientemente organizada para que alguem de fora da equipe consiga utiliza-la e pelo que eu entendi o objetivo dela era armazenar documentação mais voltada para a equipe do laboratorio, então acho que ela não deveria ser refenciada neste topico, ou deveria ser evoluida para que seja mais acessível a novos contribuidores.

* Acho que seria bom dizer no [Como conseguir ajuda](https://github.com/lappis-unb/tais#como-conseguir-ajuda) para adicionar a label `duvida` nas issues criadas

* O Github assim como o topico [Como Contribuir](https://github.com/lappis-unb/tais#como-contribuir) recomenda que novos contribuidores procurarem issues com a label `help wanted` ou `good first issue`, porém a label que o github recomenda é `good first issue` e a que é utilizada pelo repositorio é `good-first-issue` caso alguem clique na sugestão do github não ira encontrar nenhuma issue, e a label `help wanted` não existe.

![image](https://user-images.githubusercontent.com/26264107/55037957-1ab70400-4ffe-11e9-8911-b359903ceb04.png)

![image](https://user-images.githubusercontent.com/26264107/55038003-433efe00-4ffe-11e9-9590-934402968c4c.png)

**Comment by RochaCarla** [comment]
https://medium.freecodecamp.org/how-to-get-up-to-3500-github-stars-in-one-week-339102b62a8f

**Comment by gabibguedes** [comment]
Em relação a lista de dependencias, o link do exemplo, foi usado o libraries.io para criar a lista. Mandei solicitação para poder usar com repositorios da organização lappis-unb

**Comment by gabibguedes** [comment]
pages já está funcionando http://lappis-unb.github.io/tais

**Comment by gabibguedes** [comment]
Lista de licenças: https://libraries.io/github/lappis-unb/tais

**Comment by gabibguedes** [comment]
Foi criada uma issue para o Roadmap #431
