### ISSUE TITLE
Estrutura de sinonimos para o "O que é"

### ISSUE THREAD

**Issue by MatheusFaria** [lablivre-unb/tais#38]
Usar lista de sinonimos ou o próprio spacy para quando a pessoa digitar `o que é lei ruanet` ou `o que é lei rouane` caia na resposta certa `o que é lei rouanet`

**Comment by diegodorgam** [comment]
nesse caso acho que não precisaria de sinonimos, só o classificador daria conta de identificar o intent com o treinamento das variações. 
Os sinonimos são mais para identificação de entidades, tipo `meu cpf é 999.999.999-99` ou `meu cic é 999.999.999-99`, mesma coisa entre `RG` e `identidade`...

**Comment by MatheusFaria** [comment]
O código referente a essa issue foi removido
