### ISSUE TITLE
Explicar como conversar

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#382]
Observando a Emma, uma assistente virtual do governo Norte Americano, percebemos que ela ensina o usuário a conversar com bots, sendo assim desejamos usar este mecanismo com a Tais , ou seja pretendemos adicionar uma `utter` que explica como conversar com a Taís.

**Tarefas**

- [x] Descobrir o momento adequado para a Tais ensinar como conversar com ela
- [x] Encaixar no fluxo sem diminuição da harmonia da conversa
- [x] Criar Utter
- [x] Testar

**Critérios de aceitação**

- [x] A Utter como conversar com a Tais ajuda o usuário e melhora a conversa

**Comment by palomacmamede** [comment]
O mecanismo de informar a Missão da Tais, só funciona se o usuário perguntar especificamente da intent out_of_scope:

- onde está o diheiro
- onde está o pablo vittar
- vagabundos
- bandidos
- corrupção
- deus é fiel
- qual é o seu sexo
- você esta aonde?
- voce torce pra qual time
- como esta o tempo

**Comment by palomacmamede** [comment]
utter_manter_conversa:
    - text: |
          A minha missão é te guiar para a inscrição da sua proposta,
          Se você já sabe isso é porque você já tem um conhecimento avançado e talvez eu não consiga sanar as suas dúvidas.
          Mas podemos continuar conversando sobre alguns conceitos básicos da lei Rouanet (:

**Comment by palomacmamede** [comment]
O melhor momento de ensinar o usuário a conversar com um chatbot é na utter "o que sei falar".

**Comment by palomacmamede** [comment]
Hipótese
 utter_o_que_sei_falar:
    - text: |
          Veja alguns dos assuntos que eu posso te ajudar (:
O que é a Lei de Incentivo Cultural e como funciona
Dúvidas operacionais sobre a execução do projeto (ex: perdi minha senha no SALIC)
Ou dúvidas sobre definições, nomenclaturas, e informações relacionadas à lei e sobre Secretaria Especial da Cultura.
Para eu entender melhor a linguagem humana, fica mais fácil quando você escreve uma pergunta de cada vez e faz perguntas curtas sobre os temas que eu sei responder. 
Exemplos de perguntas: Como funciona a Lei Rouanet?
Agora pode me fazer tua pergunta!

**Comment by MatheusMiranda** [comment]
> utter_manter_conversa:
> - text: |
> A minha missão é te guiar para a inscrição da sua proposta,
> Se você já sabe isso é porque você já tem um conhecimento avançado e talvez eu não consiga sanar as suas dúvidas.
> Mas podemos continuar conversando sobre alguns conceitos básicos da lei Rouanet (:

Adicionar esse texto a utter fallback.
