### ISSUE TITLE
[Legenda] Criar legenda para os dashboards/visualizações

### ISSUE THREAD

**Issue by guilacerda** [lablivre-unb/tais#385]
Foi identificado que é possível criar uma visualização em forma de texto. Iremos utilizá-la para **cada dashboard ter uma breve explicação sobre sua finalidade**.

**Tarefas**
- [x] Criar texto explicativos para cada dashboard, se necessário
- [x] Analisar se é necessário colocar legendas nas visualizações

**Critérios de aceitação**
- [ ] As legendas estão bem explicadas
- [ ] Aplicadas em todos os dashboards (necessários)

**Comment by palomacmamede** [comment]
Optamos por criar legendas relacionadas às intents, pois as outras informações dos gráficos são completamente intuitivas.

**Comment by palomacmamede** [comment]
[LEGENDAS](https://docs.google.com/document/d/1kdyB9V3z1NFHLKKVSSkww-UXW3rsbHd1-q-DJRqFteg/edit)
