### ISSUE TITLE
[Web] Estratégia de login na aplicação web

### ISSUE THREAD

**Issue by guilacerda** [lablivre-unb/tais#386]
Com a criação da página web com o iframe dos dashboard, identificamos que é necessário o usuário e senha do próprio kibana para acessar as visualizações. Temos que pensar em uma estratégia para não fazer essa requisição.

**Tarefas**
- [x] Ver como a comunidade trata o problema (sem pagar)
- [x] Implementar a solução na aplicação

**Critérios de aceitação**
- [ ] Não é necessário o usuário e senha do kibana para acessar a visualização

**Comment by brunapinos** [comment]
Uma issue no kibana sobre o assunto https://discuss.elastic.co/t/auto-authenticating-to-iframe-embedded-kibana-dashboard/46091/4

**Comment by brunapinos** [comment]
Esse link mencionado deixa o login tanto no iFrame quanto no Kibana automaticos. Uma forma de contornar esse problema é criar uma tela de login para as duas ocasiões, assim termos o controle de quem acessa cada serviço

**Comment by guilacerda** [comment]
A @brunapinos estudou sobre o assunto e viu que era possível injetar o login do kibana via nginx. Contudo, seria necessário um login anteriormente ao acesso do próprio kibana para ter certeza que não é uma pessoa que está logada no (KIBANA MINC - IFRAMES) que está acessando os dashboards editáveis

**Comment by guilacerda** [comment]
- [ ] Subir instância em produção com nginx injetando o login/senha
**ATUALIZAÇÃO**  Foi criada uma issue para essa nova task #414
