### ISSUE TITLE
Erros no fluxo de conversa

### ISSUE THREAD

**Issue by LeoSilvaGomes-zz** [lablivre-unb/tais#389]
Breve comentário sobre o contexto e descrição da issue.

**Tarefas**

- Correção dos erros encontrados nos testes

**Comment by LeoSilvaGomes-zz** [comment]
### Reproduzir ###
- oi
- o proponente é remunerado
- como se caracteriza um projeto?
- o que mais você sabe falar? (Erro de fluxo)
- o que significa MINC?
- não
- me fale sobre a lei rouanet
- não obrigado


Confirmação:
Para confirmar o erro no fluxo...
- oi
- o que mais você sabe falar?
 
### Intents & utters ###
- Utter esperada:
     utter_o_que_sei_falar
- Utter entendida: 
     fallback

### Critério de aprovação ###
- [x] Sair do fallback
- [x] Mostrar utter_o_que_sei_falar

**Comment by LeoSilvaGomes-zz** [comment]
### Reproduzir ###

- me fale sobre a lei rounet 
- etapas de aprovação de projeto
- #análisetecnica (Erro de fluxo)
- como enviar proposta?
- sim
- não
- não, obrigado

Confirmação:
Para confirmar o erro no fluxo...
- me fale sobre a lei rounet 
- etapas de aprovação de projeto
- #analisetecnica
Tem-se a necessidade de adicionar mais intents para a identificação da utter

 
### Intents & utters ###
- Utter esperada:
     utter_lei_rouanet_analise_tecnica
- Utter entendida: 
     fallback

### Critério de aprovação ###
- [x] Sair do fallback
- [x] Mostrar utter_lei_rouanet_analise_tecnica

**Comment by palomacmamede** [comment]
Intent atual de análise técnica:

## intent:lei_rouanet_analise_tecnica
 - #análisetécnica
 - #analisetecnica
 - análisetécnica
 - analisetecnica

**Comment by palomacmamede** [comment]
Percebe-se que o problema não é com a intent e sim com a storie, sendo assim vamos testar a implementação da seguinte storie:
## LeiRouanet 1.9.1
* lei_rouanet_etapas_aprovacao_projeto
    - utter_lei_rouanet_etapas_aprovacao_projeto
    - utter_continuar_conversa
* lei_rouanet_analise_tecnica
    - utter_lei_rouanet_analise_tecnica
    - utter_continuar_conversa

**Comment by palomacmamede** [comment]
Melhoria na intent:
## intent:lei_rouanet_analise_tecnica
 - #análisetécnica
 - #análisetecnica
 - #analisetecnica
 - #analisetécnica
 - #analisetecnica
 - análisetécnica
 - análisetecnica
 - analisetecnica
 - analisetécnica
 - analisetecnica

**Comment by palomacmamede** [comment]
As melhorias estão na branch Storie
