### ISSUE TITLE
"is typing" não aparece durante o chat

### ISSUE THREAD

**Issue by MatheusFaria** [lablivre-unb/tais#39]
As mensagens estão vindo com o delay, mas o compotarmento de aparecer `is typing` é intermitente.

Aproveitar para ver que o `is typing`, quando aparece, esta da seguinte forma `is_typing`. E ver de trocar a linguagem do Rocket para português.

**Comment by diegodorgam** [comment]
tentar atualizar versão do rocket.chat

**Comment by MatheusFaria** [comment]
A princípio a atualização para o Rocket Chat 0.69.2 arruma este bug
https://github.com/RocketChat/Rocket.Chat/issues/11235

**Comment by arthurTemporim** [comment]
Obrigado @MatheusFaria
