### ISSUE TITLE
Implementar conversão markdown json

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#390]
Atualmente o `rasa-nlu-trainer` só funciona com arquivos `json` mas todo nosso conteúdo está em `markdown` então é necessario fazer a importação de arquivo `markdown` na plataforma e depois fazer o download em markdown.

**Tarefas**

- [x] Avaliar o uso de json na tais
- [x] Parse de md para json
- [ ] ~Permitir upload de ˜ `markdown` ?~
- [ ] ~Dar opção de escolha do formato de download do arquivo, ˜  `markdown` ou `json` ?~

**Critérios de aceitação**

- [ ] Ter essa funcionalidade publicada na plataforma

**Comment by BrunaNayara** [comment]
Analisar a opção de utilizarmos json dentro da tais, tendo em vista a movimentação do rasa em direção ao maior uso de json.

**Comment by BrunaNayara** [comment]
Parse de intents:
https://github.com/arthurTemporim/rasa-content-parser
