### ISSUE TITLE
Publicar plataforma

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#391]
Ter plataforma publicada no `github pages`, `gitlab pages` ou `digital ocean`.

**Tarefas**

- [x] Escolher plataforma que será publicado
- [x] Implementar publicação da plataforma

**Critérios de aceitação**

- [x] Ter plataforma publicada

**Comment by arthurTemporim** [comment]
@ Kamilla falta alguma coisa pra finalizar essa `issue`?

**Comment by MatheusMiranda** [comment]
> @ Kamilla falta alguma coisa pra finalizar essa `issue`?

Automatizar a atualização do GHpages com o que é commitado da master.

**Comment by KahCosta** [comment]
Link para acesso a plataforma [Aqui](https://lappis-unb.github.io/rasa-nlu-trainer/)
