### ISSUE TITLE
Gerenciamento da domain

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#393]
Quando mudanças em `intents`, `utters`, `actions` ou `stories` acontecerem na plataforma a atualização do arquivo `domain.yml` seja adicionar ou remover conteúdo deve ser feito de forma automática.

**Tarefas**

- [ ] Identificar `intents` e adicionar no arquivo domain
- [ ] Identificar `utters` e `utter templates` e adicionar no arquivo domain 

**Critérios de aceitação**

- [ ] Fazer download da domain atualizada com os novos dados de treinamento

**Comment by MatheusMiranda** [comment]
É preciso descrever as tarefas e critérios de aceitação @arthurTemporim

**Comment by BrunaNayara** [comment]
Issue desatualizada. Já foram abertas novas issues para tratar da domain #479
