### ISSUE TITLE
[Elastic] Configurar o backup

### ISSUE THREAD

**Issue by guilacerda** [lablivre-unb/tais#408]
É importantíssimo manter o backup atualizado do elastic para que possa fazer recuperação de dados 
a qualquer momento.

**Tarefas**

- [x] Analisar os _snapshots do elastic
- [x] Estudar outras formas de fazer o backup
- [x] Implementar o backup

**Critérios de aceitação**

- [x] É possível fazer recuperação do banco de datas anteriores
- [x] O backup é realizado de forma automática

**Comment by RochaCarla** [comment]
[[selfie-0 uploading...]]
[[selfie-1 uploading...]]
