### ISSUE TITLE
Estudar arquitetura do rasa nlu trainer

### ISSUE THREAD

**Issue by BrunaNayara** [lablivre-unb/tais#409]
Entender código, `components` e estrutura de todo o `rasa_nlu_trainer` para compreensão de onde e como evoluir a plataforma.

**Tarefas**

- [x] Entender a arquitura do projeto
- [x] Atualizar projeto com o que for levantado
- [x] Dockerizar e documentar

**Critérios de aceitação**

- [ ] Documentação da estrutura e arquitetura do projeto

**Comment by arthurTemporim** [comment]
@ygortgaleno Você pode criar um arquivo `md` sobre isso?
