### ISSUE TITLE
Implementar personalidade da TAIS de forma coerente 

### ISSUE THREAD

**Issue by palomacmamede** [lablivre-unb/tais#412]
É preciso criar um guia para a criação de utters que sirva de modelo para que pessoas diversas consigam editar o conteúdo da Tais sem modificar sua forma de falar, bem como seu comportamento e sua linguagem

**Tarefas**

- [x] Implementar personalidade da TAIS
- [x] Criar um guia para a criação de conteúdo com base na personalidade da TAIS
- [x] Criar modelos de utters coerentes com relação a personalidade da TAIS

**Critérios de aceitação**

- [x] A Tais tem uma personalidade coerente
- [x] Documentar em GH Pages

**Comment by palomacmamede** [comment]
[GUIA DE CONVERSAÇÃO DA TAIS](https://docs.google.com/document/d/16Ln6ra8UhVaPLBY7caUyxR-7ZpoeU2Q8deloiOq6nJs/edit)

**Comment by palomacmamede** [comment]
Devidamente documentada em GH Pages:
[Guia de Conversação da TAIS](https://lappis-unb.github.io/tais/guia-de-conversacao-da-tais/)

**Comment by RochaCarla** [comment]
[[selfie-0 uploading...]]
[[selfie-1 uploading...]]
