### ISSUE TITLE
Criar formulário para acrescentar conteúdo

### ISSUE THREAD

**Issue by BrunaNayara** [lablivre-unb/tais#413]
Permitir adição de conteúdo de treinamento para o bot, como `intents`, `utters` e `stories` de forma fácil na plataforma com uma interface intuituiva e que a partir de um botão de `salvar` exporte os arquivos necessários com todo o conteúdo que deve ser adicionado por algum desenvolvedor na Tais.

**Tarefas**

- [x] Criar página/card com inserção de `utter` (resposta do bot)
- [x] Criar página/card com inserção de `intent` (exemplos de perguntas que os usuários fazem)
- [x] Criar página/card com inserção de `stories` (exemplos de conversa onde o novo conteúdo é utilizado)

**Critérios de aceitação**

- [ ] Testar com a @palomacmamede a solução proposta e coletar dados de uso
- [ ] Levantar e planejar evoluções necessárias.

**Comment by KahCosta** [comment]
Tarefa executada! Para testar acesse o repositório [rasa-nlu-trainer](https://github.com/lappis-unb/rasa-nlu-trainer)
Esperando feedback da @palomacmamede para planejamento de melhorias.

**Comment by KahCosta** [comment]
Esta issue estava pendente devido a falta do deploy da ferramenta para teste! Porem isso já foi solucionado na issue #454
