### ISSUE TITLE
[Kibana] Deploy da página de acesso ao iframe

### ISSUE THREAD

**Issue by BrunaNayara** [lablivre-unb/tais#414]
As páginas de acesso já foram criadas, kibana tais e web, agora é preciso fazer o deploy para que tenha acesso externo.

**Tarefas**

- [x] Subir o serviço kibana-web
- [x] Subir o serviço kibana-tais
- [ ] ~Injetar o login do kibana via nginx~ **Nova issue:** #475 
- [x] Adicionar certificado para ambos serviços

**Critérios de aceitação**

- [x] Os serviços estão up com certificado
- [x] É possível acessar os dashboards via iframe
- [x] É possível editar os dashboards via iframe

**Comment by guilacerda** [comment]
Foi identificado que quando sobe a página em um ambiente limpo, gera um erro que não identifica a página de manutenção. Como foi uma página herdada do serviço "web", resolvi por deletar tudo o que era responsável pela "manutenção".

**Comment by guilacerda** [comment]
Tentei injetar o login pelo nginx usando ```Authorization user:password | base64```, só que não é atualizado o login. Então estou dando uma estudada no que pode estar acontecendo

**Comment by guilacerda** [comment]
> Tentei injetar o login pelo nginx usando `Authorization user:password | base64`, só que não é atualizado o login. Então estou dando uma estudada no que pode estar acontecendo

Como não foi alcançado o objetivo nessa issue, e foi identificado que seria uma mini bomba fazer a injeção do login, foi criado uma nova issue pra ser responsável por essa tarefa #475
