### ISSUE TITLE
Escrever Relatório de Acompanhamento

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#415]
Fazer o relatório de acompanhamento do trabalho realizado no periodo de janeiro - abril da frente da Tais

**Tarefas**

- [x] Detalhar o objetivo dessa entrega
- [x] evidenciar entrega

**Critérios de aceitação**

- [ ] Todo o conteudo está disponível na wiki do projeto (Ecossistemas de Software)

**Comment by BrunaNayara** [comment]
Estudos: 
- [Ferramentas de conteúdo](https://github.com/lappis-unb/tais/wiki/estudo-de-ferramentas-de-gerenciamento-de-conteudo)
- [Custom Actions](https://github.com/lappis-unb/tais/wiki/Estudo-sobre-custom-actions)
- [Slots e entidades](https://github.com/lappis-unb/tais/wiki/Uso-de-slots-e-entidades)
- [Métricas de bot para o kibana](https://github.com/lappis-unb/tais/wiki/Estudo-sobre-metricas-para-bots)
