### ISSUE TITLE
Documentar Arquitetura no GitHub Pages

### ISSUE THREAD

**Issue by gabibguedes** [lablivre-unb/tais#418]
Explicar a arquitetura da Taís no Pages. O documento já possui uma imagem representando o funcionamento, é necessário complementar com um texto explicativo (`docs/arquitetura.md`).

**Tarefas**

- [x] Complementar a documentação da arquitetura da Tais no pages.

**Critérios de aceitação**

- [x] A arquitetura pode ser compreendida por alguém de fora da equipe.

**Comment by pablodiegoss** [comment]
Estou trabalhando na issue, protótipo de diagramas sendo feitos na mão, por que ninguem merece as setinhas do draw.io :c

![photo5111713254014560363](https://user-images.githubusercontent.com/8556291/57931987-29989500-7890-11e9-9f63-db17b3bc2eac.jpg)

**Comment by pablodiegoss** [comment]
Versão digital, validada com @RochaCarla e @arthurTemporim, parece refletir bem a arquitetura atual.
![arch_lappisbot_customaction(3)](https://user-images.githubusercontent.com/8556291/57933140-d8d66b80-7892-11e9-8d58-a7eda60b099b.png)
