### ISSUE TITLE
Definir UX para a ferramenta de conteúdo 

### ISSUE THREAD

**Issue by BrunaNayara** [lablivre-unb/tais#421]
Definir experiência de usuário para a plataforma de gerenciamento de conteúdo de treinamento do bot.

**Tarefas**

- [x] Consultar equipe para saber quais são as partes de interface que já existem e que ainda precisam
- [x] Pesquisar outros softwares que criam Bots
- [x] Gerar parâmetros que guiarão a criação das features e diagramação das páginas
- [x] Criar rascunhos de possibilidades de interaface.
- [x] Utilizar da Identidade visual para criar mock ups e melhorar os rascunhos
- [x] Checar viabilidade e levantar novas necessidades a partir dos mock ups
- [x] refinar mock ups para que sejam viaveis de acordo com a equipe
- [ ] Criar protótipos a partir desses mock ups.

**Critérios de aceitação**

- [ ] É possível verificar quais os parâmetros e mock ups para que as features possam ser implementadas
- [ ] Existem protótipos usáveis.

**Comment by FranciscoSMM** [comment]
Feita uma pesquisa com softwares de criação de chatbot, principalmente usando como referência
IBM Watson
Google Dialogflow

Foram usados para definir alguns parâmetros de elementos para a plataforma. A maioria deles possui algumas coisas em comum que são mostradas em cada programa:

 - Criação e edição de Intents e Entidades
 - Chat de teste para o que foi criado
 - Visualização de Stories normalmente vista em diagrama de fluxos.

Além disso, ao levantar alguns outros parâmetros com a equipe, vimos que também havia a necessidade de:

 - Ferramentas de pesquisa de palavras
 - Área específica para criação de Utters

**Comment by FranciscoSMM** [comment]
Aqui alguns rascunhos do que foi feito a partir dos parâmetros obtidos durante a sprint. Ainda não estão finalizados, mas começaram a seguir e definir alguns elementos das páginas.

![1](https://user-images.githubusercontent.com/38992510/58028354-f1dc5800-7af0-11e9-94b0-709b4e1c4913.jpg)
![2](https://user-images.githubusercontent.com/38992510/58028355-f1dc5800-7af0-11e9-8906-e3a67ccf274a.jpg)
![4](https://user-images.githubusercontent.com/38992510/58028357-f274ee80-7af0-11e9-91fa-8861f4eaba81.jpg)
![3](https://user-images.githubusercontent.com/38992510/58028356-f274ee80-7af0-11e9-9833-067f2a5b39f6.jpg)

**Comment by FranciscoSMM** [comment]
Refinamento dos primeiros rascunhos de interface. Anda é preciso criar estilo para as páginas de projeto e rever as que já foram criadas.
![tela_intents](https://user-images.githubusercontent.com/38992510/58434996-c9c29b00-8094-11e9-979e-7195656fcf9e.png)
![tela_stories](https://user-images.githubusercontent.com/38992510/58434997-ca5b3180-8094-11e9-9036-5009c1b818d2.png)
![tela_storiesc](https://user-images.githubusercontent.com/38992510/58434998-ca5b3180-8094-11e9-80aa-657129411062.png)
![tela_storiesP](https://user-images.githubusercontent.com/38992510/58435000-ca5b3180-8094-11e9-9698-2a08b316b968.png)

**Comment by FranciscoSMM** [comment]
Após revisar os rascunhos refinados, algumas outras telas foram criadas e ajustes às antigas foram feitos:

![Chat_reviewed](https://user-images.githubusercontent.com/38992510/58819143-ed8e5f80-8605-11e9-8633-89dcaae441a1.png)
![Entities_reviewed](https://user-images.githubusercontent.com/38992510/58819145-ee26f600-8605-11e9-8a1c-bfa67c86cff5.png)
![Intents_reviewed](https://user-images.githubusercontent.com/38992510/58819146-ee26f600-8605-11e9-9276-a866c6e82ba7.png)
![Stories_reviewed](https://user-images.githubusercontent.com/38992510/58819149-eebf8c80-8605-11e9-80da-f46c73882e2d.png)
![Projects_reviewed](https://user-images.githubusercontent.com/38992510/58819147-ee26f600-8605-11e9-89db-795d903367f4.png)
![Search_reviewed](https://user-images.githubusercontent.com/38992510/58819148-eebf8c80-8605-11e9-94d5-fd795d213684.png)

**Comment by MatheusMiranda** [comment]
Link do protótipo: https://k6edxq.axshare.com/home.html
