### ISSUE TITLE
Estudo de arquitetura desacoplada de dados de treinamento e o bot

### ISSUE THREAD

**Issue by BrunaNayara** [lablivre-unb/tais#425]
Breve comentário sobre o contexto e descrição da issue.

**Tarefas**

- [x] Estudar estratégias  para desacoplar o conteúdo do bot
- [x] Olhar o ParlAI como referência

**Critérios de aceitação**

- [ ] Documentação na wiki

**Comment by pablodiegoss** [comment]
Após o entendimento da arquitetura atual do bot e organização das pastas do projeto, o planejamento inicial foi de mover os requirements do projeto para uma imagem docker de requirements, evitando reinstalação de libs a cada build do bot.

Foi criado um requirements.Dockerfile que contem as libs e requirements do bot instalados, prontos para serem executados. Este dockerfile deverá construido e atualizado quando houverem modificações no requirements.txt do projeto, pelo CI ou utilizador local.
Essa atualização pode ser feita com o script 'build-base.sh' adicionado a mesma pasta do dockerfile.

**Comment by pablodiegoss** [comment]
Após a generalização dos requisitos em outra imagem, os dados e o processo de treinamento foram separados da execução e conexões com aplicações. Assim, a arquitetura agora deve conter uma imagem de Coach, responsável por armazenar os dados, intents e stories da aplicação para realizar o treinamento e gerar as models que serão lidas pelo bot.
Então o bot só precisará ler os arquivos de model geradas pelo Coach e se preocupar com as conexões (Rocketchat, Telegram...) e tracking da conversa.

**Comment by pablodiegoss** [comment]
O Coach armazena a pasta de arquivos '.md ' e carrega em si mesmo as models resultantes do treinamento com as respectivas intents, utters e stories. Assim, é possível o versionamento dos treinamentos através de tags e imagens docker, desacoplando a execução do bot dos dados e aprendizado, agilizando também a inicialização da aplicação para desenvolvedores, já que o ultimo treinamento já está pré-carregado na imagem.
