### ISSUE TITLE
Ranking dos grupos - questões

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#43]
Avaliar os grupos em relação:

- [x] Quantidade de perguntas

- [x] Quantidade de erros durante a homologação (caminho)

**Comment by MatheusFaria** [comment]
**Curiosidades:** 8 perguntas 

**Preenchimento:** 5 perguntas

**Processo:** 3 perguntas

**Prazo:** 2 perguntas

**Erros Salic:** 5 perguntas
