### ISSUE TITLE
Adicionar parte de Tutoriais no GH Pages

### ISSUE THREAD

**Issue by gabibguedes** [lablivre-unb/tais#432]
**Tarefas**

- [ ] Adicionar uma página no pages com um feed de tutoriais

**Critérios de aceitação**

- [ ] Página de tutoriais acessível no pages
- [ ] É possível adicionar novos tutoriais na página

**OBS:** Veja o funcionamento de posts no Jekyll

**Comment by RochaCarla** [comment]
deprecated
