### ISSUE TITLE
Erros de fluxo na Tais

### ISSUE THREAD

**Issue by LeoSilvaGomes-zz** [lablivre-unb/tais#439]
A issue consiste em resolver bugs encontrados na Tais a partir dos testes, dando a referência e como reproduzi-lo

**Tarefas**

- [x] Resolver conflito entre intents (quem_eh_a_tais e definicao_tais)

**Critérios de aceitação**

- [x] Exibir diagonal principal da matriz no teste

**Comment by LeoSilvaGomes-zz** [comment]
### Reproduzir ###
- quem é a tais?
- sim
- sim
- quero
- nada obrigado

Confirmação:
Para confirmar o erro no fluxo execute a frase, "quem é a tais?", mais de uma vez e veja que a intent muda. Variando entre quem_eh_a_tais e definicao_tais
 
### Intents & utters ###
* quem_eh_a_tais
    - utter_quem_eh_a_tais

* definicao_tais
    - utter_definicao_tais
    - utter_objetivo

### Critério de aprovação ###
- [x] Diferenciar as duas intents

**Comment by palomacmamede** [comment]
A minha ideia de resolução do conflito é separar os dois conteúdos da seguinte forma:
A utter_quem_eh_a_tais recebe um novo nome "utter_quem _criou_a_tais" e responde somente as intents relacionadas a "quem te criou", "quem é seu pai" etc. Enquanto que a utter_definicao_tais continua respondendo quem ela é, mas agora de forma mais detalhada.

**Comment by palomacmamede** [comment]
utter_definicao_tais:
    - text: |
          Eu sou uma assistente virtual da Secretaria Especial da Cultura,
          meu objetivo é sanar dúvidas sobre a Lei Rouanet.
          Uma assistente virtual é uma inteligência artificial
          criada para interagir com as pessoas.
          Para me comunicar com vocês utilizo algoritmos de aprendizagem profundo (deep learning) 
          e sou toda software livre :P
          Em cada interação que temos aqui, eu aprendendo mais
          para que a gente se comunique melhor.
          Obrigada por conversar comigo!

**Comment by palomacmamede** [comment]
utter_quem_criou_a_tais:
    - text: |
          Fui desenvolvida em uma parceria entre a Secretaria Especial da Cultura 
          e o LAPPIS (Laboratório Avançado de Produção Pesquisa e Inovação em Software)
          na Universidade de Brasília, um laboratório super inovador e descolado!
          Se quiser me conhecer mais, acesse o meu projeto :)
          https://github.com/lappis-unb/tais

**Comment by palomacmamede** [comment]
As mudanças se encontram na branch fix

**Comment by palomacmamede** [comment]
Mudanças nas intents
## intent:definicao_tais
- o que é tais
- o que significa tais
- o que e um chatbot
- o que significa uma assistente virtual
- o que é uma assistente virtual
- o que um chatbot faz
- por que esse nome
- por que seu nome é tais
- qual significado de tais
- qual é seu nome
- qual sua tecnologia
- me conte mais sobre voce
- me fale sobre voce
- tais me fale sobre vc
- vc é homem ou mulher
- você é um robo
- vc é um humano
- você eh um robo
- quem é voce
- quem e vc
- definição de tais
- defina tais
- assistente virtual
- chatbot
- robo
- robô
- tais
- taís

## intent:quem_criou_a_tais
- quem te criou
- quem te desenvolveu
- quem te programou
- você tem pai
- qual seu pai
- onde voce nasceu
- quando vc nasceu
- quem te fez
- quem te produziu
- quem é seu pai
- fez a tais
- criou a tais
- produziu a tais
- desenvolveu a tais
- desenvolveu
- criou
- produziu
- programou

**Comment by LeoSilvaGomes-zz** [comment]
Concluída com sucesso! @palomacmamede Parabéns :)

**Comment by LeoSilvaGomes-zz** [comment]
Mediante os teste feitos e na issue #439, podemos concluir que a refatoração na confusão entre duas intents muito parecidas, desta forma, ao final dessa refatoração foi feito testes para comprovar a aprovação das mudanças feitas. E como podemos ver na imagem abaixo, por termos preenchido apenas a diagonal principal, concluímos que as mudanças foram bem sucedidas. 

![image](https://user-images.githubusercontent.com/38738836/56302776-d3a9c380-6110-11e9-9788-52291933ec4a.png)
