### ISSUE TITLE
Iniciar conversa automaticamente 

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#44]
A Rouana deve iniciar a conversa assim que a pessoa abrir a janela do chat. 

#Atualização:

O Livechat já envia o trigger de iniciar a conversa, mas a Taís ainda precisa que o usuário dê Oi para iniciar o Raza.

- [ ] Alterar o fluxo da Tais para que o processo de dar Oi aconteça de forma natural na conversa
- [ ] Avaliar a possibilidade de eliminar completamente a obrigatoriedade do usuário dar Oi.

---------

**Critérios de aceitação**

- [ ] A Taís dá "Oi" automaticamente ao abrir a janela do Livechat
- [ ] A Taís não repete a mensagem de apresentação
- [ ] O processo de saudação flui como uma conversa normal.
- [ ] Esse comportamento pode ser testado no ambiente de desenvolvimento

**Comment by diegodorgam** [comment]
a resposta pra isso ta no livechat, tem a possibilidade dele próprio iniciar a conversa através de um gatilho de tempo ou de URL, que dispara a abertura da sala com o agente e o guest.
Outra opção é na API do livechat, usar o evento onChatMaximized() para disparar um payload para o bot.

**Comment by MatheusFaria** [comment]
Falta remover o a mensagem de "oi" do lado do rasa, ela vai ser executada no lado do Rocket Chat agora (@brunapinos @KahCosta façam isso durante a refatoração)
