### ISSUE TITLE
Criar API para gerenciamento de conteúdo

### ISSUE THREAD

**Issue by BrunaNayara** [lablivre-unb/tais#443]
Criar uma API para gerenciar o conteúdo dentro da plataforma de conteúdo

**Tarefas**

- [x] Criar endpoint de POST
- [x] Criar endpoint de GET

**Critérios de aceitação**

- [x] A API consegue receber e retornar informações de intents, utter e stories

**Comment by ygortgaleno** [comment]
Revise o pull request: https://github.com/lappis-unb/rasa-nlu-trainer/pull/2
