### ISSUE TITLE
[Errro de Fluxo] - Confusão intents

### ISSUE THREAD

**Issue by LeoSilvaGomes-zz** [lablivre-unb/tais#445]
### Reproduzir ###
- tudo bem?
- o que é o Salic?
- não
- o que é a lei rouanet?
- como fazer um projeto?
- não
- tem whatsapp?
- sim
- não obrigado 
- nada, obrigado tais

Confirmação:
Para confirmar o erro no fluxo execute a frase: "como fazer um projeto?", e tenha noção que ela confundirá ou cairá no fallback!
 
### Intents & utters ###
* processo_como_funciona
    - utter_processo_como_funciona

**Tarefas**

- [x] Analisar erros referentes a intents mencionada
- [x] Identificar a possível resolução
- [x] Estabelecer melhoria

**Critérios de aceitação**

- [x] Passar nos test, exibindo na matriz apenas a diagonal principal preenchida

**Comment by palomacmamede** [comment]
Criação do Fluxo  "O que é lei Rouanet?" + "Como fazer um projeto?"
## LeiRouanet 41.1
* lei_rouanet_o_que_eh
    - utter_lei_rouanet_o_que_eh
    - utter_continuar_conversa
* processo_como_funciona
    - utter_processo_como_funciona
* afirmar
    - utter_cadastro_salic_video
* negar
    - utter_salic_cadastro_proponente
    - utter_continuar_conversa

## LeiRouanet 41.2
* lei_rouanet_o_que_eh
    - utter_lei_rouanet_o_que_eh
    - utter_continuar_conversa
* processo_como_funciona
    - utter_processo_como_funciona
* afirmar
    - utter_cadastro_salic_video
* afirmar
    - utter_salic_cadastro_usuario
    - utter_salic_cadastro_proponente
    - utter_continuar_conversa

## LeiRouanet 41.3
* lei_rouanet_o_que_eh
    - utter_lei_rouanet_o_que_eh
    - utter_continuar_conversa
* processo_como_funciona
    - utter_processo_como_funciona
* negar
    - utter_continuar_conversa

**Comment by palomacmamede** [comment]
Retirada do "manter_conversa" nas stories de "whatsapp"
## tem wpp 1
* tem_wpp
    - utter_tem_wpp
    - utter_continuar_conversa

## tem wpp 2
* cumprimentar
    - utter_cumprimentar
* tem_wpp
    - utter_tem_wpp
    - utter_continuar_conversa

**Comment by LeoSilvaGomes-zz** [comment]
De acordo com a issue #445 e o detalhamento do problema, podemos concluir que o problema foi resolvido com sucesso, tendo confirmação disso a partir da matriz feita pelo test que identificou o erro no fluxo, que no momento está exibindo a solução do problema com a apenas a diagonal principal da matriz preenchida

![image](https://user-images.githubusercontent.com/38738836/56511557-4517b680-6503-11e9-81f1-b88f45d1d2b8.png)
