### ISSUE TITLE
Aprimoramento do Guia de conversação

### ISSUE THREAD

**Issue by palomacmamede** [lablivre-unb/tais#449]
É preciso aplicar o Guia de Conversação em um fluxo e fazer um passo a passo enxuto para que qualquer pessoa que leia consiga refatorar pelo menos uma utter.

**Tarefas**

- [x] Escolher um fluxo
- [x] Aplicar a personalidade da Tais em dois fluxos
- [x] Escrever um passo a passo enxuto do Guia de Conversação

**Critérios de aceitação**

- [x] Qualquer pessoa que ler este Guia consegue refatorar pelo menos uma Utter
- [x] As utters refatoradas são coerentes com a personalidade dela

**Comment by palomacmamede** [comment]
[Passo a Passo: Guia de conversação](https://docs.google.com/document/d/1wqddvTE9AoHgNRfXgKRijHffipCjK1kAJlVxTSh5ceY/edit)

**Comment by palomacmamede** [comment]
![Screenshot from 2019-04-25 01-17-32](https://user-images.githubusercontent.com/42178586/56709703-04818e00-66f9-11e9-9b1e-856c4e14bb62.png)

**Comment by palomacmamede** [comment]
Primeiro Fluxo escolhido, abarcando também os seus desdobramentos:
## sigla 2
* cumprimentar
    - utter_cumprimentar
* definicao_salic
    - utter_definicao_salic
    - utter_objetivo
* negar
    - utter_continuar_conversa

## sigla 2.1
* cumprimentar
    - utter_cumprimentar
* definicao_salic
    - utter_definicao_salic
    - utter_objetivo
* afirmar
    - utter_processo_como_funciona
* afirmar
    - utter_cadastro_salic_video
* negar
    - utter_salic_cadastro_proponente
    - utter_continuar_conversa

## sigla 2.2
* cumprimentar
    - utter_cumprimentar
* definicao_salic
    - utter_definicao_salic
    - utter_objetivo
* afirmar
    - utter_processo_como_funciona
* afirmar
    - utter_cadastro_salic_video
* afirmar
    - utter_salic_cadastro_usuario
    - utter_salic_cadastro_proponente
    - utter_continuar_conversa

## sigla 2.3
* cumprimentar
    - utter_cumprimentar
* definicao_salic
    - utter_definicao_salic
    - utter_objetivo
* afirmar
    - utter_processo_como_funciona
* negar
    - utter_continuar_conversa

**Comment by palomacmamede** [comment]
Fluxo número 2 escolhido, bem como os seus desdobramentos:
## sigla 1
* cumprimentar
    - utter_cumprimentar
* definicao_tais
    - utter_definicao_tais
    - utter_objetivo
* negar
    - utter_continuar_conversa

## sigla 1.1
* cumprimentar
    - utter_cumprimentar
* definicao_tais
    - utter_definicao_tais
    - utter_objetivo
* afirmar
    - utter_processo_como_funciona
* afirmar
    - utter_cadastro_salic_video
* negar
    - utter_salic_cadastro_proponente
    - utter_continuar_conversa

## sigla 1.2
* cumprimentar
    - utter_cumprimentar
* definicao_tais
    - utter_definicao_tais
    - utter_objetivo
* afirmar
    - utter_processo_como_funciona
* afirmar
    - utter_cadastro_salic_video
* afirmar
    - utter_salic_cadastro_usuario
    - utter_salic_cadastro_proponente
    - utter_continuar_conversa

## sigla 1.3
* cumprimentar
    - utter_cumprimentar
* definicao_tais
    - utter_definicao_tais
    - utter_objetivo
* afirmar
    - utter_processo_como_funciona
* negar
    - utter_continuar_conversa

**Comment by palomacmamede** [comment]
O teste de validação do Guia de Conversação da Tais será realizado segunda, 29/04 às 10:00 horas, usando o conteúdo da issue #272

**Comment by pablodiegoss** [comment]
Eu senti falta no guia de algumas instruções de como quebrar um texto longo em diversas utters, talvez um exemplo de transcrição de um texto pra uma conversa.
Seguindo o guia fiquei inseguro sobre o formato final da utter e como finalizar ela, se era necessário adicionar frases de continuação da conversa parar as multiplas utters, de finalização da instrução ou semelhantes.

**Comment by palomacmamede** [comment]
**Depois do teste foi possível fazer melhorias no Passo a Passo de Conversação da Tais nos seguintes pontos:** conjunções que podem ser usadas nas utters para deixá-la mais coerente e fluída, explicação de como resumir o conteúdo recebido, no caso se devemos ou não transformá-lo em várias utters, como saber o que colocar ou não na utters, etc.

**Comment by palomacmamede** [comment]
**Sobre as utters criadas pelos integrantes da equipe:**
Pude observar que ninguém saiu da personalidade da Tais, todos optaram por transformar o texto em várias utters devido ao  seu tamanho e complexidade do tema, e por incrível que pareça todas as utters estão muito semelhantes e parecidas.

**Comment by palomacmamede** [comment]
Devidamente documentada em GH Pages:
[Tutorial Como Fazer Uma Utter](https://lappis-unb.github.io/tais/tutorial-como-fazer-uma-utter)
