### ISSUE TITLE
Usar Embedding Policy para tratamento de fallback

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#451]
A **Embedding Policy** tem como objetivo tratar melhor as conversas não cooperativas. Logo, nesta issue, adotaremos essa policy, construindo stories e intents para usá-la.

**Tarefas**

- [x] Gerar intents com conteúdo não cooperativo (frase longas)
- [ ] Gerar intents com slots PRONAC
- [x] Gerar stories com conteúdo não cooperativo
- [ ] Testar as novas stories
- [ ] Validar a nova policy com as stories antigas
- [ ] Documentar sobre nova policy

**Critérios de aceitação**

- [ ] Nova policy testada

**Comment by RochaCarla** [comment]
Olhar issue #353

**Comment by brunapinos** [comment]
O estudo sobre esta policy se encontra na [wiki](https://github.com/lappis-unb/tais/wiki/Estudo-de-Embedding-Policy)

**Comment by RochaCarla** [comment]
O problema detectado é na classificação da intenção de frases longas. Pois ela não está sendo correta. Esse estudo precisa ser feito, e talvez uma etapa anterior ao NLU para classificar frases longas a partir da quantidade de caracteres da mensagem.
Por nao ser um problema da policy essa issue será fechada
