### ISSUE TITLE
[Elastic] Criar política de armazenamento dos backups

### ISSUE THREAD

**Issue by guilacerda** [lablivre-unb/tais#453]
A task de salvar um backup roda todo dia às 12 pm. É necessário criar uma política para definir quais e quantos backups ficarão salvos em nossos storages. Caso contrário ficarão salvos todos os backups de todos os dias.

**Tarefas**

- [x] Decidir qual será a política de armazenamento
- [ ] ~Implementar um script que descreve a política~

**Critérios de aceitação**

- [x] Estão sendo armazenados somente os backups decididos na nova política

**Comment by guilacerda** [comment]
Todo dia às 12 horas pm roda um script que gera um backup. Porém não é viável matermos todos os backups gerados. Então, cheguei a conclusão de deixar os últimos 3 backups (últimos 3 dias) e também um backup de cada mês

**Comment by arthurTemporim** [comment]
Bkp diário já está sendo feito.

**Comment by guilacerda** [comment]
Nessa issue foi concluído o script pra armazenar somente os 3 dias mais recentes, mas faltou criar o script pra armazenar o backup mensal. Uma nova issue foi criada pra essa finalidade #477
