### ISSUE TITLE
Deploy continuo do Rasa NLU pages 

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#454]
Realizar Deploy Contínuo do Rasa NLU pages.

**Tarefas**

- [x] Realizar Deploy contínuo da ferramenta para adição de conteúdos das Taís.

**Critérios de aceitação**

- [x] Link documentado na issue
- [x] Plataforma disponível para teste

**Comment by KahCosta** [comment]
Link para acesso para a plataforma [Aqui](https://lappis-unb.github.io/rasa-nlu-trainer/)

**Comment by KahCosta** [comment]
@palomacmamede plataforma pronta para ser testada! Aguardamos seu feedback.

**Comment by palomacmamede** [comment]
**FEEDBACK DA PLATAFORMA**
Eu acho que seria interessante se todos os exemplos de intents de uma mesma intent pudessem ficar juntas e a utters viesse bem grande ao lado. 
![photo_2019-05-10_10-27-16](https://user-images.githubusercontent.com/42178586/57530933-b54d7700-730e-11e9-986d-191bcbf82acb.jpg)

**Comment by palomacmamede** [comment]
**FEEDBACK DA PLATAFORMA**
Acredito que visualmente a parte das stories ficariam boas se viessem em forma de fluxograma. 
![photo_2019-05-10_10-27-13](https://user-images.githubusercontent.com/42178586/57530974-d1e9af00-730e-11e9-83a0-44b06b4921c0.jpg)

**Comment by palomacmamede** [comment]
**FEEDBACK DA PLATAFORMA**
Seria bacana se as intents adicionadas ficassem em ordem ou de modificação ou em ordem alfabeta, ou se a gente pudesse criar um filtro para visualizá-las com várias formas de classificação.
