### ISSUE TITLE
Salvar conteudo do chatbot em arquivo

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#456]
Quando o conteúdo for inserido na plataforma seja por meio de inserção ou por meio de upload na pasta do projeto afim de atualizar os arquivos de intent e story devem ser atualizadas.

**Tarefas**

- [ ] Atualizar arquivos de intents e stories  com o conteúdo inserido na pasta de origem do projeto em questão

**Critérios de aceitação**

- [ ] Arquivos atualizados a cada inserção de conteúdo na plataforma

**Comment by BrunaNayara** [comment]
Foram abertas outras issues #479 e #491
