### ISSUE TITLE
Aplicar as melhorias de experiencia de usuario na plataforma

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#457]
Essa issue é para seguir as guidelines definidas na issue #421 

**Tarefas**

- [ ] Passo a ser feito para que algum critério de aceitação seja cumprido

**Critérios de aceitação**

- [ ] Cada critério de aceitação descreve uma condição necessária para que a issue seja considerada completa
- [ ] A condição necessária pode ser a nível de comportamento ou resultado

**Comment by BrunaNayara** [comment]
Vamos abrir as issues específicas após a apresentação da nova proposta de UX da issue #421
