### ISSUE TITLE
Converter story e utters para json

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#459]
Atualmente o `rasa-nlu-trainer` só funciona com arquivos `json` mas todo nosso conteúdo está em `markdown` então é necessario fazer fazer um parse para transaformar as utters e stories da Tais para `json`

**Tarefas**

- [x] Parse de md para json de utters por meio do arquivo domain.yml
- [ ] ~Parse de md para json de stories~

**Critérios de aceitação**
- [ ] ~Arquivos da Tais atualizados para `json`~

**Comment by KahCosta** [comment]
A conversão das stories foi feita por meio da implementação do parser presente no seguinte repositório:
https://github.com/KahCosta/Parser-Md-Json
A conversão das utters não foi feita por meio da implementação manual de um parser pois foi encontrado uma ferramenta que já realiza esta operação de passar yaml para json
https://codebeautify.org/yaml-to-json-xml-csv

**Comment by RochaCarla** [comment]
Documentar o passo-a- passo de como extrair essas informações no README do rasa-nlu (de preferência de forma mais automatizada possível)

**Comment by arthurTemporim** [comment]
O parse de `md` para `json` está pronto sem a funcionalidade de usar entidades. Só é necessário instalar este [pacote](https://pypi.org/project/rasa-content-parser/) python e usar o comando `rasa-parser -i intents/` no terminal e ele vai gerar um arquivo chamado `intents.json`.

**Comment by arthurTemporim** [comment]
A volta, `json` para `md` ainda não está implementada, pretendo finaliza-la na próxima sprint.

Sobre..

*  **Parse de md para json de stories**: O rasa não usa stories no formato `json` então podemos deixar deste jeito.
*  **Arquivos da Tais atualizados para json**: Acho melhor executar essa atividade em outra issue pois, ela é uma grande mudança e só pode ser feita quando a `plataforma de conteúdo` estiver pronta e funcioando.

**Comment by KahCosta** [comment]
@arthurTemporim já fiz a implementação dos Parses!
para ter acesso basta acessar nosso repo [Rasa-nlu-trainer](https://github.com/lappis-unb/rasa-nlu-trainer)
