### ISSUE TITLE
Entrega SEFIC (16/08/2018) - Encaminhamentos

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#46]
Agenda confirmada

- [ ] Workshop - Refinamento Produto - 24 de agosto a tarde - SEFIC. Participantes: envolvidos na comunicação com o usuário (atendimento + técnicos + ASCOM). Total sugerido de participantes: 08

- [ ] Planejamento Estratégico Taís e ML - 30 de agosto (ML 9h30 às 12h e Taís 14h30 às 17h30) - SEFIC + LAPPIS + CGTEC. Total participantes (6 Lappis, tentar aumentar esse número). Tarefa LAPPIS: Levar os resultados do workshop de refinamento

- [ ] Beta testers - puxar esses nomes com o Romulo

- [ ] Alguns comentários sobre a Taís - estratégia para o ministério reagir rápido via Rouana (ex: asco, noticias quentes), pensar num fluxo para jornalistas, Dinamismo na ferramenta - automação (ex:  diário oficial, salic api, etc). Como vai ser o monitoramento em uso da Rouana? (para tomada de decisões)

**Comment by ricardopoppi** [comment]
Fiz alguns updates no corpo da issue, passando pra Tais e lembrando que o planejamento estratégico do 30 também é do ML. Vou abrir invites de todos esses eventos

**Comment by rodmaia** [comment]
Entrega realizada e encaminhamentos mapeados em outras issues e na wiki
