### ISSUE TITLE
Melhorar qualidade do código

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#460]
Atualemente a Taís está com nota `D` no [codeclimate](https://codeclimate.com/github/lappis-unb/tais) esta nota deve ser melhorada para `A` e se não for possível justificar.

**Tarefas**

- [x] Encontrar todos os arquivos com problemas indicados no codeclimate
- [x] Implementar a melhoria do código

**Critérios de aceitação**

- [x] Ter nota do codeclimate da Tais como `A` e se não for possível justificar.

**Comment by MatheusMiranda** [comment]
Os serviços 'kibana-web' e 'kibana-tais' tem uma grande quantidade de códigos duplicados. É preciso refatorar os serviços e criar um projeto único com os dois como *apps*. Foi criada uma issue para isso: #504.

Os diretórios dessses projetos foram ignorados nas configurações do CodeClimate da Tais. Para alterar isso basta ir no projeto dentro do CodeClimate -> Repo Settings -> Exclude patterns

![image](https://user-images.githubusercontent.com/13803249/58714290-d0a22400-839a-11e9-9720-0480ae7b80c2.png)
