### ISSUE TITLE
Consertar Pipeline de acordo com a arquitetura do PLOC

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#473]
Atualizar Pipeline da Tais

- [x] O arquivo de docker-compose que está na maquina (de homolog) não é o mesmo do repositório (está sem PLOC);
- [x] Utilizar a imagem do Ploc nas configurações do CI para otimizar o tempo dos jobs;

**Comment by pablodiegoss** [comment]
O pipeline estava com problemas para executar testes e validações no bot, pois a execução dos testes de ponta a ponta, exigiam que o bot tivesse acesso as models, e estas estavam contidas apenas no coach e este não possuia os testes e2e para poder executar os testes.
Com essa restrição de executar os scripts a partir de uma única imagem, não estava sendo possível completar o pipeline, pois estavamos acoplando as imagens ao docker-compose.

Com isso, a solução foi remover a dependencia das imagens de um docker-compose, utilizando um multi-stage build na imagem do bot para copiar as models de dentro da imagem coach para o bot, tornando então a imagem do bot independente e ao mesmo tempo mantendo o processo de treinamento separado e versionável com o coach.
