### ISSUE TITLE
Corrigir os Notebooks de acordo com a nova arquitetura

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#474]
**Descrição do erro encontrado:**
O Ploc quebrou os notebooks. É necessário expor a pasta de models do coach dos treinamentos

**Comment by pablodiegoss** [comment]
Verifiquei os notebooks, aparentemente estão todos funcionando agora após as modificações do pipeline, pois alteramos a forma como as imagens interagem em #473. 
De qualquer forma atualizei também o Dockerfile dos notebooks nesse [commit](https://github.com/lappis-unb/tais/commit/df8a9441f3f4efa42142383581f418eb0421cfb9), otimizando algumas coisas que já temos.
Se acontecer algum outro problema, outra issue pode ser criada
