### ISSUE TITLE
[Kibana] Injetar login pela nginx

### ISSUE THREAD

**Issue by guilacerda** [lablivre-unb/tais#475]
Pra fazer um controle de usuário foi necessário criar duas interfaces de login diferentes pra cada tipo. Porém, quando o usuário loga, é requisitado um novo login do próprio kibana. Sendo assim, é necessário injetar o login diretamente pelo nginx, pra que não apareça o pop up pro usuário solicitando um novo usuário/senha.

**Tarefas**
- [x] Estudar como injetar o login pelo nginx
- [ ] Implementar a melhor solução pra não aparecer o pop up

**Critérios de aceitação**

- [x] O usuário não precisa colocar o login no pop up

**Comment by guilacerda** [comment]
Pra entender melhor o que está acontecendo, entrei mais a fundo em como é gerado o usuário do Kibana. 

O Kibana possui três planos de negócio, e cada plano possui o seu nível de segurança disponibilizado:
![image](https://user-images.githubusercontent.com/26297247/57728441-510e1880-766a-11e9-9bfc-913669bd621d.png)

Como mostrado na imagem, quando é código aberto/basic não possui nenhum nível de security, que é exatamente a validação do usuário antes de entrar no kibana. 

**Então como geramos nosso login?**

Temos uma autenticação básica que é fornecida pelo próprio NGINX. Sendo assim, toda vez que entramos no nosso kibana, o nginx que é a camada anterior exige a autorização criada por nós para que forneça acesso àquela aplicação. 

Com isso, temos que quando exportamos o iframe do kibana, é necessário colocar a autorização criada por nós. Então nós mesmo criamos essa barreira pelo motivo de não termos um plano pago.

**Comment by guilacerda** [comment]
Pesquisando um pouco mais, vi que era possível a partir de um HEADER do nginx injetar o login na aplicação.
```
         proxy_set_header  Authorization "Basic user:password | base64";
```

Porém, só é possível essa solução se fosse no próprio serviço do kibana. Como é em um outro serviço que estamos tentando injetar o login, não foi possível

**Comment by guilacerda** [comment]
Conversando com o @pablodiegoss chegamos em uma suposta solução que deixaríamos o nosso kibana rodando local e consumiríamos os dados localmente, não precisando expor o serviço para a web. Contudo, como é gerado o iframe, que é uma url estática, não é possível porque a url gerada vem com "localhost". Só que quando acessado da máquina de outra pessoa, o navegador procura o localhost em sua máquina.

**Comment by guilacerda** [comment]
Uma próxima solução agora vai ser criar um ```location``` com o path do login do iframe e unir com a tentativa 1 de injeção de login. Caso dê errado, será necessário trocar a estratégia e analisar a viabilidade da solução

**Comment by guilacerda** [comment]
> Uma próxima solução agora vai ser criar um `location` com o path do login do iframe e unir com a tentativa 1 de injeção de login. Caso dê errado, será necessário trocar a estratégia e analisar a viabilidade da solução

Tentei setar um Authorization "Basic user:pass | 64"  na nova location, por algum motivo que não entendi não é possível autenticar o login do iframe...

**Comment by guilacerda** [comment]
Como não foi descoberta uma solução, a task de ``` Implementar a melhor solução pra não aparecer o pop up``` não será marcada e a issue será dada com ```done```. Pois não gastaremos mais tempo e esforço em um trabalho que é só adquirir um plano do kibana/elastic

**Comment by RochaCarla** [comment]
Há 2 login

login individual + login admin Kibana !
