### ISSUE TITLE
Estrutura do analytics

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#476]
Atualmente existe 2 projetos Django dentro da Tais.

**Tarefas**

- [ ] Verificar a viabilidade de criação de um novo repositório para visualizações do kibana.
- [ ] Unir os 2 projetos Django da Tais
- [ ] Melhorar qualidade do código dos projetos.

**Critérios de aceitação**

- [ ] Documentar na issue a decisão tomada.
- [ ] Ter os projetos Django unificados.

**Comment by hugonxc** [comment]
Alguém trabalhando nessa issue?
