### ISSUE TITLE
[Elastic] Armazenar backup mensalmente

### ISSUE THREAD

**Issue by guilacerda** [lablivre-unb/tais#477]
O backup é gerado diariamente e armazena somente dos últimos 3 dias. Assim, é necessário armazenar o backup de cada mês separadamente.

**Tarefas**

- [x] Criar script para armazenar mensalmente o backup

**Critérios de aceitação**

- [x] É possível recuperar o backup do mês à escolha
- [x] Todos os meses estão sendo armazenados

**Comment by guilacerda** [comment]
O elastic não fornece um modo fácil pra mover um snapshot de um lugar para outro.

**Comment by guilacerda** [comment]
Então, pensei primeiro em criar um outro path.repo (diretório onde são criados os snapshots dentro do container), possibilitando que eu rodasse um script mensalmente, e nesse repositório ficasse armazenado somente os backups mensais.

Só que não é possível em um mesmo cluster ter dois repositórios pra armazenar snapshot, assim minha ideia foi inviabilizada

**Comment by guilacerda** [comment]
Minha segunda opção agora é copiar os arquivos que foram criados no último dia do mês. É possível fazer isso copiando os dados da pasta do volume que está sendo compartilhado entre o container e a máquina.

**Comment by guilacerda** [comment]
Eu mesclei um pouco da primeira ideia com a segunda ideia. Então está sendo gerado um snapshot diariamente, chegando no último dia do mês ele utiliza um segundo padrão pra nome, indicando o mês. Com isso, é movido de dentro do container o backup de cada mês para uma pasta separada dentro da máquina.

**Comment by RochaCarla** [comment]
snapshot - https://gitlab.com/lappis-unb/snapshots-tais
