### ISSUE TITLE
Visualizar as utters e stories rasa-nlu-trainer

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#480]
visualizar as utters e stories na interface do rasa-nlu-trainer

**Tarefas**

- [ ] ler o json do modelo
- [ ] criar uma nova aba para visualizar as utters + stories

**Critérios de aceitação**

- [ ]  apresentar o conteudo das utters e stories na interface

**Comment by LeoSilvaGomes-zz** [comment]
Mediante algumas decisões feitas pelo grupo, decide-se fazer um repositório para tratar melhor as issues destinadas ao BotFlow (https://github.com/lappis-unb/BotFlow).
