### ISSUE TITLE
Manter vários dados de treinamento 

### ISSUE THREAD

**Issue by BrunaNayara** [lablivre-unb/tais#481]
Atualemente, ao subir um arquivos, os anteriores eram sobrescritos.

**Tarefas**

- [x] Criar um bd para suportar essas operações
- [x] Atualizar o banco a partir de cada atualização na interface
- [x] Separar dados de treinamento por projeto
- [x] Criar campo para saber de qual arquivo de treinamento o dado veio

**Critérios de aceitação**

- [x] Consegue subir vários arquivos e ver os dados de todos

**Comment by ygortgaleno** [comment]
Separei a api do rasa-nlu-trainner, e criei um repositório só para api: https://github.com/lappis-unb/rasa-nlu-trainner-api
