### ISSUE TITLE
Criar projeto no BotFlow

### ISSUE THREAD

**Issue by BrunaNayara** [lablivre-unb/tais#495]
Implementar interface de criação de projetos

**Tarefas**

- [ ] Análise de similares
- [ ] Rascunho da tela
- [ ] Implementar protótipo

**Critérios de aceitação**

- [ ] Estar disponível no GHPages
- [ ] Testado por um usuário

**Comment by LeoSilvaGomes-zz** [comment]
Mediante algumas decisões feitas pelo grupo, decide-se fazer um repositório para tratar melhor as issues destinadas ao BotFlow (https://github.com/lappis-unb/BotFlow).
