### ISSUE TITLE
Editar dados dos projetos no BotFlow

### ISSUE THREAD

**Issue by BrunaNayara** [lablivre-unb/tais#496]
Editar descrição de projetos no BotFlow  de forma a permitir adicionar dados específicos de acordo com divisão de projetos.

**Tarefas**

- [ ] Criar sistema de pastas para divisão de projetos
- [ ] Criar campos de edição de dados de acordo com projeto
- [ ] Editar campos de descrição do projeto

**Critérios de aceitação**

- [ ] Usuário conseguir criar uma pasta referente ao projeto projeto
- [ ] Usuário conseguir adicionar dados referentes ao projeto
- [ ] GHPages atuaizado com a funcionalidade de criação e edição de dados do projeto
- [ ] Testado com usuário

**Comment by RochaCarla** [comment]
detalhar a issue!

**Comment by KahCosta** [comment]
issue detalhada!

**Comment by KahCosta** [comment]
Foi decidido com base em uma reunião de planejamento ocorrida no meio da sprint que baseado no protótipo em desenvolvimento esta funcionalidade será executada em uma sprint seguinte e em decorrência disto será executado uma nova tarefa para entrega desta.

**Comment by KahCosta** [comment]
A nova tarefa a ser realizada é a construção de endpoints na API com relação a criação de projetos na plataforma a fim de facilitar a implementação da funcionalidade listada acima.
Endpoints de :
- Criação
- Adição
- Delete

**Comment by KahCosta** [comment]
Nova issue para a sprint 24  #502

**Comment by KahCosta** [comment]
Além disso foi decido que para facilitação dos membros da equipe quanto a utilização de React, será realizado a documentação da arquitetura do projeto a fim de facilitar o entendimento quanto aos arquivos e fluxo de tarefas executadas no projeto.

**Comment by LeoSilvaGomes-zz** [comment]
Mediante algumas decisões feitas pelo grupo, decide-se fazer um repositório para tratar melhor as issues destinadas ao BotFlow (https://github.com/lappis-unb/BotFlow).
