### ISSUE TITLE
Implementar ferramenta de Analytics

### ISSUE THREAD

**Issue by brunapinos** [lablivre-unb/tais#50]
* ~~https://www.dashbot.io/~~
* [ ] ~~Connector~~
* [ ] ~~Extrair fluxos comuns, erros e contagem da ocorrência~~
* [ ] Implementar ferramenta
* [ ] Levantar ambiente

**Comment by diegodorgam** [comment]
PR agendado pra próxima versão com APIs HTTPs para puxar o histórico
https://github.com/RocketChat/Rocket.Chat/pull/11900/files#diff-02ccb4d008b8d0bdacc6ef841f52034dR4

**Comment by MatheusFaria** [comment]
O script para extração das conversas, utilizando o DDP, foi iniciado na branch `analytics`
continuação na issue #81
