### ISSUE TITLE
Refatorar documentação da Arquitetura BotFlow

### ISSUE THREAD

**Issue by KahCosta** [lablivre-unb/tais#505]
Breve comentário sobre o contexto e descrição da issue.

**Tarefas**

- [ ] Modificar documento de arquitetura baseado na aplicação de duckpattern redux a fim de deixar o código mais claro e limpo e melhorar a componentização

**Critérios de aceitação**

- [ ] Documento refatorado de acordo com nova arquitetura
- [ ] Documento revisado por outro membro da equipe

**Comment by LeoSilvaGomes-zz** [comment]
Mediante algumas decisões feitas pelo grupo, decide-se fazer um repositório para tratar melhor as issues destinadas ao BotFlow (https://github.com/lappis-unb/BotFlow).
