### ISSUE TITLE
Refatorar estrutura de código BotFlow

### ISSUE THREAD

**Issue by KahCosta** [lablivre-unb/tais#506]
Refatorar código a fim de implementar alguns padrões para evolução da arquitetura da plataforma BotFlow.

**Tarefas**

- [ ] Aplicar duckpattern redux a fim de deixar o código mais claro e limpo e melhorar a componentização.

**Critérios de aceitação**

- [ ] Código limpo e claro por meio da aplicação de duckpattern redux.

**Comment by LeoSilvaGomes-zz** [comment]
Mediante algumas decisões feitas pelo grupo, decide-se fazer um repositório para tratar melhor as issues destinadas ao BotFlow (https://github.com/lappis-unb/BotFlow).
