### ISSUE TITLE
Criação do Editor ChatBot - Estudo

### ISSUE THREAD

**Issue by brunapinos** [lablivre-unb/tais#51]
* [ ] Modificaçãod o fluxo
* [ ] Gerar grafo de conversa
* [ ] Visão geral do conteúdo
* [ ] Reporte de erros

**Comment by RochaCarla** [comment]
Decisão: Vai estar no plano de transição (não vai ser prioridade para a próxima entrega). Levantar

- [ ] Possíveis ferramentas

- [ ] Roadmap de com a proposta para a transição do conhecimento (se vai usar ferramenta, se vamos desenvolveram, etc)

**Comment by RochaCarla** [comment]
Essa issue está obsoleta e foi abordada de forma pontual
