### ISSUE TITLE
Melhoria e Expansão do Conteúdo

### ISSUE THREAD

**Issue by brunapinos** [lablivre-unb/tais#52]
* [ ] Trazer proatividade à Tais
* [ ] Encorporar notícias e posicionamento do MinC
* [ ] Integrar o Salic (automação)
* [ ] Expandir conteúdo
* [ ] Expandir Fluxo
* [ ]  Incorporar avaliação da utlização
* [ ] Usuário controlar o final da conversa
* [ ] Desenvolver o **restart** da conversa
* [ ] Criar a Personalidade da Tais

**Comment by rodmaia** [comment]
Identificado como desnecessário
