### ISSUE TITLE
[Fallbecks] Utilizar a hierarquia das policies para responder corretamente

### ISSUE THREAD

**Issue by guilacerda** [lablivre-unb/tais#527]
Existe uma hierarquia de policies nos projetos dos Bots, que devem ser seguidos quando responder via fallback. Ou seja, quando cair no novo custom fallback #507, o bot deverá responder de acordo com a intent que tem a maior confiança. Porém, a confiança deverá ser o segundo critério de aceitação. O primeiro deve ser a policy mais importante primeiro.

**Tarefas**

- [x] Após pegar a resposta das confianças e das policies, fazer um sort primeiro das policies
- [x] Fazer um segundo sort para pegar as maiores confianças
- [x] Encaminhar a resposta com maior confiança da policy com maior nível de hierarquia

**Critérios de aceitação**

- [x] Se duas intents tem o mesmo valor de confiança, deverá seguir para o critério do nível de hierarquia

**Comment by pablodiegoss** [comment]
Conversando com a @brunapinos, @guilacerda, decidimos trabalhar com uma média entre as duas confianças que um bot possui: a confiança da intent e a confiança da policy.
Como a conversa pode envolver diferentes bots com diferentes policies, inclusive custom policies, é dificil mensurar o peso de cada uma nas respostas, é necessário decidir o valor da confiança da policy utilizada em relação ao entendimento do bot com a intent do usuário.

Informações relevantes:
* Uma intent respondida com Memoization, tem confiança 1 na resposta, porém um valor de 0 a 1 na confiança da intent do usuário.
* Uma intent respondida com Keras tem confiança 0 a 1 na resposta e um valor de 0 a 1 na intent.
* Custom policies também tem confiança de 0 a 1 nas respostas

a partir dessas informações, era possível priorizar o memoization sempre na decisão, porém é possível ter um bot sem Memoization ou munido de custom policies. Também, acabaria priorizando uma resposta feita com Memoization e confiança na intent baixa, como 0.2.

Assim, pensamos em realizar uma média da confiança na intent com a confiança da policy, pois isto priorizaria de qualquer forma o Memoization que tem confiança 1 e daria a chance de um bot com melhor entendimento da intent, 0.8 de confiança da intent e 0.8, responder ao invés do bot com Memoization (1) e confiança da intent 0.2.

**Comment by pablodiegoss** [comment]
O json da api do rasa é acessada no link /conversations/default/tracker
```JSON
...
{
      "event": "user",
      "input_channel": null,
      "parse_data": {
        "entities": [],
        "intent": {
          "confidence": 0.9253216981887817,
          "name": "lei_rouanet_o_que_eh"
        },
        "intent_ranking": [...],
        "text": "o que é a lei rouanet"
      },
      "text": "o que é a lei rouanet",
      "timestamp": 1563978395.399682
    },
    {
      "confidence": 0.9980258981168246,
      "event": "action",
      "name": "utter_lei_rouanet_o_que_eh",
      "policy": "policy_0_KerasPolicy",
      "timestamp": 1563978395.4252572
    },
...
```

Nesse link é possível obter uma lista de eventos.
Eventos do tipo 'user' contém a informação sobre a mensagem do usuário e a intent.
Eventos do tipo 'action' vem em seguida de um evento user e contém a informação da utter e da policy utilizada para responder a intent do evento 'user' imediatamente anterior.

**Comment by pablodiegoss** [comment]
Percebi que utilizando a média entre as duas confianças, como exemplo exatamente o caso que citei no json anterior, pode acabar acontecendo uma priorização do Keras sobre o Memoization, então ao invés de calcular uma média entre a confiança das policies, decidir por apenas somar ambas as confianças.
A confiança de um memoization é sempre 1, então isso dá ao Memoization a vantagem desejada pela equipe sobre o Keras.

**Comment by joaovitor3** [comment]
Foi trabalhado no [Pull Request](https://github.com/lappis-unb/rasa-ptbr-boilerplate/pull/48)
