### ISSUE TITLE
Implementar nova visualização do site da comunidade Tais

### ISSUE THREAD

**Issue by brunapinos** [lablivre-unb/tais#528]
Feito o levantamento dos requisitos #483, aplicaremos o layout com base no que foi decidido pela @AniaGomes  

**Tarefas**

- [x] Aplicação das cores, layout e tipografia na página inicial
- [x] Criar navbar da Documentação, Comunidade e Tutorial
- [x] Modificar o footer existente para adequar a nova visualização

**Critérios de aceitação**

- [x] Para cada página, o novo layout seja aplicado

**Comment by AniaGomes** [comment]
[Tdetais.zip](https://github.com/lappis-unb/tais/files/3301573/Tdetais.zip) - icone da Tais
