### ISSUE TITLE
Workshop de Refinamento TAIS

### ISSUE THREAD

**Issue by brunapinos** [lablivre-unb/tais#54]
* [x]  Processo
* [x] Feedback
* [x] Comunicação

### Objetivo
- Identificar Bugs
- Validar Qualidade de texto
- Validar o Fluxo
- Levantar Questões Extras
- Mapear Processo/Ferramenta  de análise dos históricos

**Comment by brunapinos** [comment]
* Apresentação
* Guia por tópico: moderador e 2 acompanhando
* Feedback do tópico: erros, acertos e percepções
* Feedback geral do processo: form
* Comunicação via email

**Comment by RochaCarla** [comment]
Local confirmado do workshop de Refinamento: SEFIC

**Comment by MatheusFaria** [comment]
@brunapinos @KahCosta @arthurTemporim @rodmaia2099 bora puxar isso ao longo da próxima semana? Para as anotações mentais não se perderem no tempo. Criei um página na nossa wiki para postar os resultados

https://github.com/lappis-unb/rouana/wiki/Tais-Homologa%C3%A7%C3%A3o-v2.0

**Comment by rodmaia** [comment]
Passei as notas do stand-up que fizemos para a página acima.

@brunapinos conseguiu abrir os resultados da pesquisa?

**Comment by rodmaia** [comment]
@MatheusFaria bora sim! Marca um horário no grupo pra gente fazer isso com todos os presentes no dia.

**Comment by rodmaia** [comment]
O workshop foi realizado e a análise dos resultados mapeada em #60.

Equipe, onde documentamos o feedback do stand-up que fizemos no dia do workshop?
