### ISSUE TITLE
Identificar erros a partir dos logs de conversa da Tais

### ISSUE THREAD

**Issue by MatheusMiranda** [lablivre-unb/tais#541]
Analisar as conversas da Tais e criar issues a partir dos erros e falhas de comportamento encontrados.

**Tarefas**

- [x] Abrir issues dos pontos de melhoria das conversas [processo contínuo]
- [x] Documentar processo de monitoramento das conversas e melhoria do bot

**Issues de bugs**

- [x] #508 
- [x] #509 
- [x] #514 
- [x] #516 
- [x] #518 
- [x] #519 
- [x] #530 
- [x] #535 
- [x] #536 
- [x] #537 
- [x] #539 
- [x] #254 
- [x] #279 
- [x] #286 
- [x] #288 
- [x] #542 
- [x] #543 
- [x] #550 
- [x] #554

**Comment by palomacmamede** [comment]
**Texto provisório**
https://docs.google.com/document/d/17DziY1ez3RnXbp9ygAz_b7LdCHIiAfxx5ughPFlc2mI/edit?usp=sharing

**Comment by palomacmamede** [comment]
**Tipos de Bug**

atualização de intents
atualização de stories
atualização de conteúdo
inserir conteúdo novo
melhoria de utter

**Comment by palomacmamede** [comment]
https://lappis-unb.github.io/tais/documentacao/aperfei%C3%A7oamento-da-tais/
