### ISSUE TITLE
Ambiente de Produção

### ISSUE THREAD

**Issue by brunapinos** [lablivre-unb/tais#55]
* [ ] ~Aprovação pela SEFIC do conteúdo da Taís~ (Mapeado em #115)
* [x] Configuração do ambiente
* [ ] ~Pensar Detalhar processo de deploy contínuo na wiki~
* [ ]  ~Informar a equipe CGTIC das atividades que são responsabilidade deles~ => (#137)
* [x] Criar uma página de "teste" da produção que não dependa da CGTIC

--------
**Critérios de aceitação**
* [x] Conseguimos fazer deploy e testar a Taís em produção antes do dia 24.
* [x] Conseguimos testar a Taís em produção a qualquer momento, sem depender da CGTIC.
* [ ] A documentação do processo de subir uma atualização em produção é clara o suficiente. Qualquer pessoa da equipe com o conhecimento técnico consegue realizar o procedimento.
* [x] A CGTIC recebeu todas as infromações que precisavam da gente.

**Comment by MatheusFaria** [comment]
O @LucianoPC vai ver se utilizaremos a mesma VM do SALIC ML ou se vai ser necessário a criação de uma nova VM no MinC

**Comment by MatheusFaria** [comment]
O pedido de realocação de recursos da VM foi feito, no aguardo do MinC concluir o pedido para fazer o deploy lá.

**Comment by MatheusFaria** [comment]
@joenio pode ver o dominio junto com o @LucianoPC

**Comment by MatheusFaria** [comment]
Requisitos da VM atual

```
/             - 10GB
/var      - 30GB
/home - 20GB

memóra: 16GB
```

**Comment by joenio** [comment]
qual é o IP dessa VM que eles disponibilizaram?

**Comment by joenio** [comment]
peguei o IP com o @LucianoPC: 192.168.15.16

**Comment by MatheusFaria** [comment]
Atividades:

- [ ] reservar o domínio taischat.cultura.gov.br
- [ ] Alinhar estratégia de deploy com o time de ML
- [ ] Documentar o processo de deploy do lado do minc, de subir o ambiente do zero até o deploy do JS na página da lei rouanet

**Comment by joenio** [comment]
Solicitei o domínio lappis.cultura.gov.br com a ideia de separarmos as várias aplicações pelo PATH, exemplos:
* lappis.cultura.gov.br/taischat
* lappis.cultura.gov.br/salicml
* lappis.cultura.gov.br/salicapi
* etc

Funciona pra vocês? Vocês podem acompanhar os detalhes da solicitação na issue abaixo:
* https://gitlab.com/lappis-unb/athena/issues/36

**Comment by rodmaia** [comment]
@joenio no caso da Taís, a produção provavelmente vai ficar sob um domínio *.cultura.gov.br não relacionado ao Lappis. 

Ter a opção do lappis.cultura.gov.br/taischat me parece interessante. Seria um ambiente separado da produção ou apenas mais uma forma de acessar? Minha sugestão é lappis.cultura.gov.br/tais.

**Comment by joenio** [comment]
misturamos os assuntos, o dominio lappis.cultura.gov.br é para o ambiente de homologação.

**Comment by rodmaia** [comment]
@MatheusFaria @arthurTemporim precisamos ver com o MinC que domínio vai ser e começar a discutir o deploy lá

**Comment by MatheusMiranda** [comment]
Como a página estará rodando no portal da Lei Rouanet. O que a gente precisa colocar em produção é apenas o RocketChat de onde será consumido o IFrame.

Então nesse caso acho que não há problemas em utilizar um domínio como o Joênio sugeriu. Ex: lappis.cultura.gov.br/taischat

**Comment by rodmaia** [comment]
Se vai ter uma instância do Rocket rodando no MinC, precisamos começar a testar o deploy e o funcionamento. 

Esse iFrame vai apontar para páginas que vão estar hospedadas aonde?
ATUALIZAÇÃO: O Miranda me explicou que era o iFrame do lado do MinC para mostrar o RocketChat.

**Comment by rodmaia** [comment]
@MatheusFaria @MatheusMiranda @arthurTemporim atualizei as tasks para cobrir necessidades que identifiquei depois de conversar com o Miranda.
Não deveríamos acrescentar tarefas depois da sprint começar, mas julguei necessário para que a gente reduza o risco de algo dar errado.

**Comment by MatheusFaria** [comment]
Link para o Rocket: https://lappis.cultura.gov.br/
Link para o site Beta: https://lappis.cultura.gov.br/taisbeta
 Documentação para instalação: https://github.com/lappis-unb/rouana/wiki/Instala%C3%A7%C3%A3o-do-Livechat-de-Produ%C3%A7%C3%A3o

Pendência: certificado assinado

**Comment by MatheusFaria** [comment]
**Deploy Continuous** não será feito automaticamente, por razões de estabilidade do ambiente.

**Comment by MatheusFaria** [comment]
**Acesso a VM** Precisamos melhorar o compartilhamento e monitoramento da VM para não precisar compartilhar o acesso com todos
