### ISSUE TITLE
[Fallbecks] Continuar com o Fallback padrão em alguns casos

### ISSUE THREAD

**Issue by guilacerda** [lablivre-unb/tais#553]
**Descrição da nova feature:**
Quando feita a comunicação do bot principal com outros bots, é necessário que o bot volte para seu fallback padrão quando não escolhida nenhuma resposta por todas as confianças recebidas serem abaixo do threshold (nlu ou core). Também, deve-se voltar para o fallback quando enviado uma mensagem para algum bot que esteja fora do ar e faça com que quebre a comunicação.

**Tarefas**

- [x] Criar uma exceção para quando o bot estiver fora do ar, ou quebrar por algum motivo.
- [x] Criar validação para quando a maior confiança for menor do que o nlu/core threshold

**Critérios de aceitação**

- [x] O bot principal entra no seu próprio fallback quando a confiança recebida está abaixo do esperado

**Comment by guilacerda** [comment]
Identificamos alguns erros de quando fazemos uma requisição para o bot e ele não se encontra up. Com isso, adaptamos a ideia de que qualquer erro encontrado ou então nenhum bot sabe responder o que o usuário perguntou, ele responde a utter do fallback do bot principal (bot que o usuário está conversando)

**Comment by joaovitor3** [comment]
Foi trabalhado no [Pull Request](https://github.com/lappis-unb/rasa-ptbr-boilerplate/pull/48)
