### ISSUE TITLE
Tutorial boas práticas monitoramento

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#558]
Inserir no gitpages da Tais um tutorial sobre boas práticas de monitoramento da Tais

A partir do documento gerado na issue #541

**Comment by palomacmamede** [comment]
@RochaCarla preciso de um feedback: https://docs.google.com/document/d/1e922ViZbRtNRvOfpgLyb1VeaW9N_yZY0lL7qAZ8WDYI/edit?usp=sharing

**Comment by rodmaia** [comment]
@palomacmamede, achei que esse tutorial precisa de um pouco mais de detalhamento. As etapas em si são claras, mas seria interessante você detalhar mais as tuas estratégias de avaliação e decisão.

**Comment by palomacmamede** [comment]
![photo_2019-08-22_18-23-07](https://user-images.githubusercontent.com/42178586/63554020-9e740e80-c512-11e9-9a63-78a6c5f5fc39.jpg)

**Comment by palomacmamede** [comment]
![photo_2019-08-21_21-41-26](https://user-images.githubusercontent.com/42178586/63554693-ae8ced80-c514-11e9-8f27-7f0963867c4b.jpg)

**Comment by palomacmamede** [comment]
![photo_2019-08-22_19-39-15](https://user-images.githubusercontent.com/42178586/63554768-f6137980-c514-11e9-91c3-d44fb092cd49.jpg)

**Comment by palomacmamede** [comment]
![photo_2019-08-22_19-39-19](https://user-images.githubusercontent.com/42178586/63554783-062b5900-c515-11e9-9731-29cef85d6b00.jpg)

**Comment by palomacmamede** [comment]
https://lappis-unb.github.io/tais/tutoriais/tutorial-monitoramento-tais/
