### ISSUE TITLE
Proposta Planejamento Estratégico

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#56]
- [ ] Plano de transição/transferência de conhecimento

- [ ] TAIS em Produção

- [ ] Plano de Entrega Contínua

- [ ] Ampliação do Conteúdo 

   - Preenchimento Propostas OU
   - Visão Geral do Fluxo

**Comment by rodmaia** [comment]
Contemplado em: https://github.com/lappis-unb/EcossistemasSWLivre/wiki/Planejamento-Estrat%C3%A9gico-Etapa-III
