### ISSUE TITLE
Aumentar a cobertura de testes da Tais

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#561]
Aumentar a cobertura de testes da Tais

**Tarefas**

- [x] Criar novas histórias com fluxos de conversas nos testes

- [x] Melhorar intents que apresentarem problemas

- [x] Melhoras stories que apresentarem problemas

**Fluxos**

- [x] Definições
definicao_tais
definicao_proposta
definicao_proponente
definicao_projeto
definicao_vinculada
definicao_salic
definicao_sefic
definicao_minc
definicao_cnic

- [x] Geral
utter_o_que_sei_falar
utter_elogios
utter_quem_criou_a_tais
utter_tudo_bem
utter_contato
utter_endereco

- [x] Lei Rouanet
utter_lei_rouanet_origem_do_dinheiro
utter_lei_rouanet_quantidade_de_projetos
utter_lei_rouanet_quantidade_de_projetos_este_ano
utter_lei_rouanet_quem_pode_ser_proponente
utter_lei_rouanet_beneficios_incentivo_projetos_culturais
utter_lei_rouanet_porcentagem_de_deducao_do_imposto
utter_lei_rouanet_quem_pode_incentivar
utter_lei_rouanet_remuneracao_proponente
utter_lei_rouanet_comercializacao_de_ingressos
utter_lei_rouanet_promocao_de_marca
utter_lei_rouanet_valores_pagamento_caches
utter_lei_rouanet_denuncia
utter_lei_rouanet_divulgacao_patrocinio
utter_lei_rouanet_edital
utter_lei_rouanet_tipos_projeto
utter_lei_rouanet_receber_incetivo_de_parentes
utter_lei_rouanet_democratizacao
utter_lei_rouanet_remanejamento
utter_lei_rouanet_reembolso_despesa
utter_lei_rouanet_recibo_mecenato
utter_lei_rouanet_etapas_aprovacao_projeto
utter_lei_rouanet_apresentacao_de_proposta
utter_lei_rouanet_analise_de_admissibilidade
utter_lei_rouanet_analise_tecnica
utter_lei_rouanet_analise_pela_cnic
utter_lei_rouanet_decisao_final
utter_lei_rouanet_valor_maximo_projeto
utter_lei_rouanet_valor_maximo_pessoa_fisica
utter_lei_rouanet_valor_maximo_pessoa_juridica
utter_lei_rouanet_valor_maximo_regiao
utter_lei_rouanet_valor_minimo

- [x] Captação
utter_captacao
utter_quando_captar
utter_captacao_como_captar

- [x] Processo
utter_processo_como_funciona
utter_processo_prazo_periodo_captacao
utter_processo_prazo
utter_processo_prazo_apresentar_proposta
utter_processo_prazo_analise_proposta
utter_processo_prazo_analise_tecnica
utter_processo_prazo_prestacao_contas
utter_processo_reativacao_de_proposta
utter_processo_prazo_desarquivar
utter_processo_prazo_readequacao
utter_processo_prazo_envio_cnae
utter_processo_prazo_diligencias
utter_processo_prazo_desistir_recurso
utter_processo_definicao_etapas
utter_processo_preenchimento
utter_processo_admissibilidade
utter_processo_aprovacao
utter_processo_execucao
utter_processo_analise_de_resultados

- [x] Salic
utter_cadastro_salic_video
utter_salic_cadastro_usuario
utter_salic_cadastro_proponente
utter_salic_erros
utter_salic_erros_planilha_desapareceu
utter_salic_erros_salvamento_de_proposta
utter_salic_erros_achar_proposta
utter_salic_recuperacao_de_senha
utter_salic_preenchimento
utter_salic_preenchimento_alteracao_proponente
utter_salic_preenchimento_comprovacao_financeira
utter_salic_preenchimento_campo_custo_auditoria
utter_salic_preenchimento_cadastro_rubrica_advogado_contador
utter_salic_preenchimento_valor_ingresso
utter_salic_preenchimento_cadastro_fornecedor
utter_salic_preenchimento_planilha_orcamentaria
utter_salic_preenchimento_vinculo_cpf_proposta
utter_salic_preenchimento_cadastro_agencia_bancaria

**Critérios de aceitação**

- [x] Todos os testes estarem passando

**Comment by palomacmamede** [comment]
## end-to-end story 3
* o_que_sei_falar: me ajuda
    - utter_o_que_sei_falar
* captacao: quero falar sobre captação?
    - utter_captacao
* captacao_quando_captar: quando posso começar a captar?
    - utter_captacao_quando_captar
    - utter_continuar_conversa
* elogios: adorei
    - utter_elogios
    - utter_continuar_conversa
* lei_rouanet_origem_do_dinheiro: de onde vem o dinheiro?
    - utter_lei_rouanet_origem_do_dinheiro
    - utter_continuar_conversa
* negar_despedir: nada
    - utter_despedir

**Comment by palomacmamede** [comment]
## end-to-end story 5
* quem_criou_a_tais: quem te criou?
   - utter_quem_criou_a_tais
   - utter_continuar_conversa
* definicao_tais: o que você é?
   - utter_definicao_tais
   - utter_objetivo
* negar: não
   - utter_continuar_conversa
* lei_rouanet_quantidade_de_projetos: quantos projetos foram aprovados?
   - utter_lei_rouanet_quantidade_de_projetos
   - utter_continuar_conversa
* lei_rouanet_quantidade_de_projetos_este_ano: quantos projetos foram aprovados este ano?
   - utter_lei_rouanet_quantidade_de_projetos_este_ano
   - utter_continuar_conversa
* lei_rouanet_quem_pode_ser_proponente: quem pode submeter uma proposta?
   - utter_lei_rouanet_quem_pode_ser_proponente
   - utter_continuar_conversa
* negar_despedir: não obrigado
   - utter_despedir

**Comment by palomacmamede** [comment]
## end-to-end story 6
* tudo_bem: tudo bem, Tais?
   - utter_tudo_bem
   - utter_menu
* lei_rouanet_beneficios_incentivo_projetos_culturais: qual é a vantagem de incentivar? 
   - utter_lei_rouanet_beneficios_incentivo_projetos_culturais
   - utter_continuar_conversa
* lei_rouanet_porcentagem_de_deducao_do_imposto: como funciona a isenção fiscal?
   - utter_lei_rouanet_porcentagem_de_deducao_do_imposto
   - utter_continuar_conversa
* lei_rouanet_quem_pode_incentivar: quem pode incentivar um projeto?
   - utter_lei_rouanet_quem_pode_incentivar
   - utter_continuar_conversa
* lei_rouanet_remuneracao_proponente: qual a remuneração do proponente?
   - utter_lei_rouanet_remuneracao_proponente
   - utter_continuar_conversa
* negar_despedir: não tenho mais perguntas
   - utter_despedir

**Comment by palomacmamede** [comment]
## end-to-end story 7
* lei_rouanet_comercializacao_de_ingressos: qual deve ser o preço dos ingressos?
   - utter_lei_rouanet_comercializacao_de_ingressos
   - utter_continuar_conversa
* lei_rouanet_promocao_de_marca: quero divulgar a logo do patrocinador
   - utter_lei_rouanet_promocao_de_marca
   - utter_continuar_conversa
* lei_rouanet_valores_pagamento_caches: pagamento de cachê
   - utter_lei_rouanet_valores_pagamento_caches
   - utter_continuar_conversa
* lei_rouanet_denuncia: quero denunciar um projeto
   - utter_lei_rouanet_denuncia
   - utter_continuar_conversa
* contato: quero falar com uma pessoa
   - utter_contato
   - utter_continuar_conversa
* endereco: qual é o endereço?
   - utter_endereco
   - utter_continuar_conversa
* negar_despedir: não tenho mais perguntas
   - utter_despedir

**Comment by palomacmamede** [comment]
## end-to-end story 8
* o_que_sei_falar: me ajuda
   - utter_o_que_sei_falar
* lei_rouanet_edital: tem algum edital aberto?
   - utter_lei_rouanet_edital
   - utter_continuar_conversa
* lei_rouanet_tipos_projeto: quais os tipos de projeto podem ser submetidos?
   - utter_lei_rouanet_tipos_projeto
   - utter_continuar_conversa
* lei_rouanet_receber_incetivo_de_parentes: meus pais podem incentivar meu projeto?
   - utter_lei_rouanet_quem_pode_incentivar
   - utter_continuar_conversa
* lei_rouanet_democratizacao: o que é democratização do acesso e formação de plateia?
   - utter_lei_rouanet_democratizacao
   - utter_continuar_conversa
* processo_como_funciona: como posso submeter uma proposta?
   - utter_processo_como_funciona
* afirmar: sim
   - utter_cadastro_salic_video
* afirmar: quero
   - utter_salic_cadastro_usuario
   - utter_salic_cadastro_proponente
   - utter_continuar_conversa
* negar_despedir: nada
   - utter_despedir

**Comment by palomacmamede** [comment]
## end-to-end story 9
* tudo_bem: tudo bem?
   - utter_tudo_bem
   - utter_menu
* lei_rouanet_remanejamento: gostaria de saber como fazer o remanejamento orçamentário
   - utter_lei_rouanet_remanejamento
   - utter_continuar_conversa
* lei_rouanet_reembolso_despesa: como fazer o reembolso?
   - utter_lei_rouanet_reembolso_despesa
   - utter_continuar_conversa
* lei_rouanet_recibo_mecenato: como baixar o recibo de mecenato? 
   - utter_lei_rouanet_recibo_mecenato
   - utter_continuar_conversa
* salic_preenchimento_cadastro_fornecedor: como cadastrar fornecedor não cadastrado?
   - utter_salic_preenchimento_cadastro_fornecedor
   - utter_continuar_conversa
* salic_preenchimento_planilha_orcamentaria: como faço para preencher a planilha orçamentária?
   - utter_salic_preenchimento_planilha_orcamentaria
   - utter_continuar_conversa
* negar_despedir: não tenho mais perguntas
   - utter_despedir

**Comment by palomacmamede** [comment]
## end-to-end story 10
* lei_rouanet_etapas_aprovacao_projeto: quais etapas de aprovação de um projeto?
   - utter_lei_rouanet_etapas_aprovacao_projeto
   - utter_continuar_conversa
* lei_rouanet_apresentacao_de_proposta: #apresentaçãodeproposta
   - utter_lei_rouanet_apresentacao_de_proposta
   - utter_continuar_conversa
* lei_rouanet_analise_de_admissibilidade: #análisedeadmissibilidade
   - utter_lei_rouanet_analise_de_admissibilidade
   - utter_continuar_conversa
* lei_rouanet_analise_tecnica: #analisetecnica
   - utter_lei_rouanet_analise_tecnica
   - utter_continuar_conversa
* lei_rouanet_analise_pela_cnic: #análisepelacnic
   - utter_lei_rouanet_analise_pela_cnic
   - utter_continuar_conversa
* negar_despedir: não tenho mais dúvidas
   - utter_despedir

**Comment by palomacmamede** [comment]
## end-to-end story 11
* definicao_proposta: o que é proposta?
   - utter_definicao_proposta
   - utter_continuar_conversa
* definicao_proponente: o que é proponente?
   - utter_definicao_proponente
   - utter_continuar_conversa
* lei_rouanet_etapas_aprovacao_projeto: quais etapas de aprovação de um projeto?
   - utter_lei_rouanet_etapas_aprovacao_projeto
   - utter_continuar_conversa
* lei_rouanet_decisao_final: #decisaofinal
   - utter_lei_rouanet_decisao_final
   - utter_continuar_conversa
* negar_despedir: não obrigado
   - utter_despedir

**Comment by palomacmamede** [comment]
## end-to-end story 12
* o_que_sei_falar: me ajuda
   - utter_o_que_sei_falar
* definicao_projeto: o que significa projeto?
   - utter_definicao_projeto
   - utter_continuar_conversa
* lei_rouanet_valor_maximo_projeto: qual é o valor maximo de projetos?
   - utter_lei_rouanet_valor_maximo_projeto
* lei_rouanet_valor_maximo_pessoa_fisica: pessoa fisica
   - utter_lei_rouanet_valor_minimo
   - utter_lei_rouanet_valor_maximo_pessoa_fisica
   - utter_lei_rouanet_valor_maximo_regiao
   - utter_continuar_conversa
* negar_despedir: nada
   - utter_despedir

**Comment by palomacmamede** [comment]
## end-to-end story 13
* o_que_sei_falar: me ajuda
   - utter_o_que_sei_falar
* lei_rouanet_valor_maximo_projeto: qual é o valor maximo de projetos?
   - utter_lei_rouanet_valor_maximo_projeto
* lei_rouanet_valor_maximo_pessoa_juridica: pessoa juridica
   - utter_lei_rouanet_valor_minimo
   - utter_lei_rouanet_valor_maximo_pessoa_juridica
   - utter_lei_rouanet_valor_maximo_regiao
   - utter_continuar_conversa
* negar_despedir: nada
   - utter_despedir

**Comment by palomacmamede** [comment]
## end-to-end story 14
* lei_rouanet_valor_maximo_projeto: qual é o valor maximo de projetos?
   - utter_lei_rouanet_valor_maximo_projeto
* lei_rouanet_valor_maximo_geral: sobre todos
   - utter_lei_rouanet_valor_minimo
   - utter_lei_rouanet_valor_maximo_pessoa_fisica
   - utter_lei_rouanet_valor_maximo_pessoa_juridica
   - utter_lei_rouanet_valor_maximo_regiao
   - utter_continuar_conversa
* negar_despedir: não obrigada
   - utter_despedir

**Comment by palomacmamede** [comment]
## end-to-end story 4
* o_que_sei_falar: me ajuda
   - utter_o_que_sei_falar
* captacao: tenho duvidas sobre captacao
   - utter_captacao
* captacao_quando_captar: quando posso começar a captar?
   - utter_captacao_quando_captar
   - utter_continuar_conversa
* captacao_como_captar: como funciona a captação?
   - utter_captacao_como_captar
   - utter_continuar_conversa
* processo_prazo_periodo_captacao: quanto tempo para captar
   - utter_processo_prazo_periodo_captacao
   - utter_continuar_conversa
* lei_rouanet_origem_do_dinheiro: de onde vem o dinheiro?
   - utter_lei_rouanet_origem_do_dinheiro
   - utter_continuar_conversa
* elogios: você me ajudou muito
   - utter_elogios
   - utter_continuar_conversa
* negar_despedir: nada
   - utter_despedir

## end-to-end story 5
* quem_criou_a_tais: quem te criou?
   - utter_quem_criou_a_tais
   - utter_objetivo
* negar: não
   - utter_continuar_conversa
* lei_rouanet_quantidade_de_projetos: quantos projetos foram aprovados?
   - utter_lei_rouanet_quantidade_de_projetos
   - utter_continuar_conversa
* lei_rouanet_quantidade_de_projetos_este_ano: quantos projetos foram aprovados este ano?
   - utter_lei_rouanet_quantidade_de_projetos_este_ano
   - utter_continuar_conversa
* lei_rouanet_quem_pode_ser_proponente: quem pode submeter uma proposta?
   - utter_lei_rouanet_quem_pode_ser_proponente
   - utter_continuar_conversa
* negar_despedir: não obrigado
   - utter_despedir

## end-to-end story 6
* tudo_bem: tudo bem, Tais?
   - utter_tudo_bem
   - utter_menu
* salic_preenchimento_vinculo_cpf_proposta: vinculo de proposta
   - utter_salic_preenchimento_vinculo_cpf_proposta
   - utter_continuar_conversa
* lei_rouanet_beneficios_incentivo_projetos_culturais: tem beneficio para quem incentiva projeto?
   - utter_lei_rouanet_beneficios_incentivo_projetos_culturais
   - utter_continuar_conversa
* lei_rouanet_porcentagem_de_deducao_do_imposto: como funciona a isenção fiscal das empresas?
   - utter_lei_rouanet_porcentagem_de_deducao_do_imposto
   - utter_continuar_conversa
* lei_rouanet_quem_pode_incentivar: quais a regras de elegibilidade no caso de empresas
   - utter_lei_rouanet_quem_pode_incentivar
   - utter_continuar_conversa
* negar_despedir: não tenho mais perguntas
   - utter_despedir

## end-to-end story 7
* lei_rouanet_comercializacao_de_ingressos: qual deve ser o preço dos ingressos?
   - utter_lei_rouanet_comercializacao_de_ingressos
   - utter_continuar_conversa
* lei_rouanet_promocao_de_marca: quero divulgar a logo do patrocinador
   - utter_lei_rouanet_promocao_de_marca
   - utter_continuar_conversa
* lei_rouanet_divulgacao_patrocinio: como é feita a  divulgação do patrocínio?
   - utter_lei_rouanet_divulgacao_patrocinio
   - utter_continuar_conversa
* lei_rouanet_valores_pagamento_caches: pagamento de cachê
   - utter_lei_rouanet_valores_pagamento_caches
   - utter_continuar_conversa
* lei_rouanet_denuncia: quero denunciar um projeto
   - utter_lei_rouanet_denuncia
   - utter_continuar_conversa
* contato: quero falar com uma pessoa
   - utter_contato
   - utter_continuar_conversa
* endereco: qual é o endereço?
   - utter_endereco
   - utter_continuar_conversa
* negar_despedir: não tenho mais perguntas
   - utter_despedir

## end-to-end story 8
* o_que_sei_falar: me ajuda
   - utter_o_que_sei_falar
* lei_rouanet_edital: tem algum edital aberto?
   - utter_lei_rouanet_edital
   - utter_continuar_conversa
* lei_rouanet_tipos_projeto: quais os tipos de projeto podem ser submetidos?
   - utter_lei_rouanet_tipos_projeto
   - utter_continuar_conversa
* lei_rouanet_receber_incetivo_de_parentes: meus pais podem incentivar meu projeto?
   - utter_lei_rouanet_quem_pode_incentivar
   - utter_continuar_conversa
* lei_rouanet_democratizacao: é necessário a formação de plateia?
   - utter_lei_rouanet_democratizacao
   - utter_continuar_conversa
* processo_como_funciona: como submeter uma proposta?
   - utter_processo_como_funciona
* afirmar: sim
   - utter_cadastro_salic_video
* afirmar: quero
   - utter_salic_cadastro_usuario
   - utter_salic_cadastro_proponente
   - utter_continuar_conversa
* negar_despedir: nada
   - utter_despedir

## end-to-end story 9
* tudo_bem: tudo bem?
   - utter_tudo_bem
   - utter_menu
* lei_rouanet_remanejamento: gostaria de saber como fazer o remanejamento orçamentário
   - utter_lei_rouanet_remanejamento
   - utter_continuar_conversa
* lei_rouanet_reembolso_despesa: como fazer o reembolso?
   - utter_lei_rouanet_reembolso_despesa
   - utter_continuar_conversa
* lei_rouanet_recibo_mecenato: como baixar o recibo de mecenato? 
   - utter_lei_rouanet_recibo_mecenato
   - utter_continuar_conversa
* salic_preenchimento_cadastro_fornecedor: como cadastrar fornecedor não cadastrado?
   - utter_salic_preenchimento_cadastro_fornecedor
   - utter_continuar_conversa
* salic_preenchimento_planilha_orcamentaria: como faço para preencher a planilha orçamentária?
   - utter_salic_preenchimento_planilha_orcamentaria
   - utter_continuar_conversa
* salic_preenchimento_comprovacao_financeira: quero enviar a comprovação financeira do projeto
   - utter_salic_preenchimento_comprovacao_financeira
   - utter_continuar_conversa
* processo_prazo_readequacao: qual é o prazo para readequação?
   - utter_processo_prazo_readequacao
   - utter_continuar_conversa
* negar_despedir: não tenho mais perguntas
   - utter_despedir

## end-to-end story 10
* lei_rouanet_etapas_aprovacao_projeto: quais etapas de aprovação de um projeto?
   - utter_lei_rouanet_etapas_aprovacao_projeto
   - utter_continuar_conversa
* lei_rouanet_apresentacao_de_proposta: #apresentaçãodeproposta
   - utter_lei_rouanet_apresentacao_de_proposta
   - utter_continuar_conversa
* lei_rouanet_analise_de_admissibilidade: #análisedeadmissibilidade
   - utter_lei_rouanet_analise_de_admissibilidade
   - utter_continuar_conversa
* lei_rouanet_analise_tecnica: #analisetecnica
   - utter_lei_rouanet_analise_tecnica
   - utter_continuar_conversa
* lei_rouanet_analise_pela_cnic: #análisepelacnic
   - utter_lei_rouanet_analise_pela_cnic
   - utter_continuar_conversa
* negar_despedir: não tenho mais dúvidas
   - utter_despedir

## end-to-end story 11
* definicao_proposta: o que é proposta?
   - utter_definicao_proposta
   - utter_continuar_conversa
* definicao_proponente: o que é proponente?
   - utter_definicao_proponente
   - utter_continuar_conversa
* lei_rouanet_etapas_aprovacao_projeto: quais etapas de aprovação de um projeto?
   - utter_lei_rouanet_etapas_aprovacao_projeto
   - utter_continuar_conversa
* lei_rouanet_decisao_final: #decisaofinal
   - utter_lei_rouanet_decisao_final
   - utter_continuar_conversa
* negar_despedir: não obrigado
   - utter_despedir

## end-to-end story 12
* o_que_sei_falar: me ajuda
   - utter_o_que_sei_falar
* definicao_projeto: o que significa projeto?
   - utter_definicao_projeto
   - utter_continuar_conversa
* lei_rouanet_valor_maximo_projeto: qual é o valor maximo de projetos?
   - utter_lei_rouanet_valor_maximo_projeto
* lei_rouanet_valor_maximo_pessoa_fisica: pessoa fisica
   - utter_lei_rouanet_valor_minimo
   - utter_lei_rouanet_valor_maximo_pessoa_fisica
   - utter_lei_rouanet_valor_maximo_regiao
   - utter_continuar_conversa
* negar_despedir: nada
   - utter_despedir

## end-to-end story 13
* o_que_sei_falar: me ajuda
   - utter_o_que_sei_falar
* lei_rouanet_valor_maximo_projeto: qual é o valor maximo de projetos?
   - utter_lei_rouanet_valor_maximo_projeto
* lei_rouanet_valor_maximo_pessoa_juridica: pessoa juridica
   - utter_lei_rouanet_valor_minimo
   - utter_lei_rouanet_valor_maximo_pessoa_juridica
   - utter_lei_rouanet_valor_maximo_regiao
   - utter_continuar_conversa
* negar_despedir: nada
   - utter_despedir

## end-to-end story 14
* lei_rouanet_valor_maximo_projeto: qual é o valor maximo de projetos?
   - utter_lei_rouanet_valor_maximo_projeto
* lei_rouanet_valor_maximo_geral: sobre todos
   - utter_lei_rouanet_valor_minimo
   - utter_lei_rouanet_valor_maximo_pessoa_fisica
   - utter_lei_rouanet_valor_maximo_pessoa_juridica
   - utter_lei_rouanet_valor_maximo_regiao
   - utter_continuar_conversa
* negar_despedir: não obrigada
   - utter_despedir

## end-to-end story 15
* processo_prazo: prazos
   - utter_processo_prazo
   - utter_continuar_conversa
* processo_prazo_apresentar_proposta: qual a data de apresentação de proposta?
   - utter_processo_prazo_apresentar_proposta
   - utter_continuar_conversa
* processo_prazo_analise_proposta: qual é o prazo para a análise de proposta?
   - utter_processo_prazo_analise_proposta
   - utter_continuar_conversa
* processo_prazo_analise_tecnica: qual é o prazo da análise técnica?
   - utter_processo_prazo_analise_tecnica
   - utter_continuar_conversa
* processo_prazo_prestacao_contas: qual é o prazo para prestação de contas?
   - utter_processo_prazo_prestacao_contas
   - utter_continuar_conversa
* negar_despedir: não tenho mais perguntas
   - utter_despedir

## end-to-end story 16
* processo_reativacao_de_proposta: como reativar uma proposta?
   - utter_processo_reativacao_de_proposta
   - utter_continuar_conversa
* processo_prazo_desarquivar: data para desarquivar proposta
   - utter_processo_prazo_desarquivar
   - utter_continuar_conversa
* salic_erros: estou com problemas no salic
   - utter_salic_erros
   - utter_continuar_conversa
* salic_erros_planilha_desapareceu: minha planilha desapareceu
   - utter_salic_erros_planilha_desapareceu
   - utter_continuar_conversa
* salic_erros_salvamento_de_proposta: houve um erro ao gravar minha proposta
   - utter_salic_erros_salvamento_de_proposta
   - utter_continuar_conversa
* salic_recuperacao_de_senha: perdi minha senha
   - utter_salic_recuperacao_de_senha
   - utter_continuar_conversa
* salic_erros_achar_proposta: não consigo encontrar minha proposta
   - utter_salic_erros_achar_proposta
   - utter_continuar_conversa
* negar_despedir: nada mais
   - utter_despedir

## end-to-end story 17
* processo_prazo_envio_cnae: envio do cnae
   - utter_processo_prazo_envio_cnae
   - utter_continuar_conversa
* processo_prazo_diligencias: quero saber o prazo de diligências
   - utter_processo_prazo_diligencias
   - utter_continuar_conversa
* processo_prazo_desistir_recurso: quero desistir do prazo de recurso
   - utter_processo_prazo_desistir_recurso
   - utter_continuar_conversa
* salic_preenchimento_alteracao_proponente: como mudar o proponente do projeto?
   - utter_salic_preenchimento_alteracao_proponente
   - utter_continuar_conversa
* definicao_vinculada: o que é vinculada
   - utter_definicao_vinculada
   - utter_objetivo
* negar: não
   - utter_continuar_conversa
* negar_despedir: não obrigada
   - utter_despedir

## end-to-end story 18
* definicao_sefic: o que é sefic?
   - utter_definicao_sefic
   - utter_objetivo
* negar: não
   - utter_continuar_conversa
* definicao_salic: o que é salic?
   - utter_definicao_salic
   - utter_continuar_conversa
* salic_preenchimento: instruções de preenchimento
   - utter_salic_preenchimento
   - utter_continuar_conversa
* salic_preenchimento_campo_custo_auditoria: como preencher o campo custo de auditoria?
   - utter_salic_preenchimento_campo_custo_auditoria
   - utter_continuar_conversa
* salic_preenchimento_cadastro_rubrica_advogado_contador: cadastrar as rubricas de advogado e contador
   - utter_salic_preenchimento_cadastro_rubrica_advogado_contador
   - utter_continuar_conversa
* salic_preenchimento_valor_ingresso: como calcula o valor do ingresso?
   - utter_salic_preenchimento_valor_ingresso
   - utter_continuar_conversa
* negar_despedir: só isso mesmo, obrigada
   - utter_despedir

## end-to-end story 19
* processo_definicao_etapas: gostaria de saber o passo a passo na elaboração do projeto
   - utter_processo_definicao_etapas
   - utter_continuar_conversa
* processo_preenchimento: preenchimento
   - utter_processo_preenchimento
   - utter_continuar_conversa
* processo_admissibilidade: admissibilidade
   - utter_processo_admissibilidade
   - utter_continuar_conversa
* processo_aprovacao: etapa de aprovação
   - utter_processo_aprovacao
   - utter_continuar_conversa
* processo_execucao: fase de execução
   - utter_processo_execucao
   - utter_continuar_conversa
* processo_analise_de_resultados: o que devo fazer na análise de resultados?
   - utter_processo_analise_de_resultados
   - utter_continuar_conversa
* salic_preenchimento_cadastro_agencia_bancaria: precisa ter conta no banco do brasil?
   - utter_salic_preenchimento_cadastro_agencia_bancaria
   - utter_continuar_conversa
* negar_despedir: nada mais
   - utter_despedir

## end-to-end story 20
* tudo_bem: tudo bem
   - utter_tudo_bem
   - utter_menu
* definicao_minc: o que é minc?
   - utter_definicao_minc
   - utter_objetivo
* afirmar: quero
   - utter_processo_como_funciona
* afirmar: sim
   - utter_cadastro_salic_video
* afirmar: sim
   - utter_salic_cadastro_usuario
   - utter_salic_cadastro_proponente
   - utter_continuar_conversa
* negar_despedir: não tenho mais dúvidas
   - utter_despedir

## end-to-end story 21
* tudo_bem: tudo bem
   - utter_tudo_bem
   - utter_menu
* definicao_cnic: o que é cnic?
   - utter_definicao_cnic
   - utter_objetivo
* afirmar: quero
   - utter_processo_como_funciona
* afirmar: sim
   - utter_cadastro_salic_video
* negar: não
   - utter_salic_cadastro_proponente
   - utter_continuar_conversa
* negar_despedir: não tenho mais perguntas
   - utter_despedir

**Comment by RochaCarla** [comment]
esse conteúdo está em alguma Branch/PR?

**Comment by palomacmamede** [comment]
@RochaCarla ele tá na branch test, vpu testar mais uma vez pra abrir o PR (:
