### ISSUE TITLE
Relatório de uso da Tais

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#569]
Fazer um relato sobre o uso da Tais: qual o perfil de usuário que acessa a tais, como eh a interação, de forma qualitativa como eh a experincia dos usuarios.

**Tarefas**

- [x] Quantidade de usuarios/dia

- [x] Qual o perfil do usuario (mais avancado, iniciante, curioso)

- [x] Como eh a forma de interaçao (ele conversa com a tais, pergunta direto, etc)

**Comment by palomacmamede** [comment]
@RochaCarla também preciso de um feedback aqui, eu achei a análise um pouco superficial, mas não sei como melhorá-la: https://docs.google.com/document/d/1h1KH0Do4IrKCcWjcYM3sBXAwmvZJHVuSSdJyM2Q2MtA/edit?usp=sharing

**Comment by rodmaia** [comment]
@palomacmamede, fiz alguns comentários direto no arquivo, mas no geral me parece um perfil bem construído

**Comment by RochaCarla** [comment]
https://dashboard.cauldron.io/goto/887094ae27fae25bacc06f68877c0000
