### ISSUE TITLE
Apresentação Refinamento Workshop

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#57]
- [x] Introdução/ contextualização

- [x] Pauta/agenda

- [x] Acessos (link TAIS)

- [x] Tópicos

- [x] Feedback por tópicos

- [x] Feedback geral

- [x] Contatos

**Comment by RochaCarla** [comment]
@arthurTemporim  - Observador/anotando (gravar audio)
Mediadores - @rodmaia2099 @brunapinos @ricardopoppi

**Comment by arthurTemporim** [comment]
[apresentação](https://docs.google.com/presentation/d/1XsOjEKfiZYotFeSrrA4WH1Rza0ZSYc68YGDGXVf9Enk/edit#slide=id.g35f391192_00)

**Comment by RochaCarla** [comment]
Segue abaixo a relação dos indicados da SEFIC para participação no Workshop de Refinamento da Assistente Virtual  - TAIS, 24/08 (sexta-feira), das 14h30 às18h00
 
Reservamos a sala de treinamento localizado no 7º andar aqui do Ed. Parque Cidade para o evento. Lá temos computadores para serem utilizados pelos participantes.
 
Quanto à gravação, um de nossos técnicos irá verificar a possibilidade e nos retornará.

Nº | NOME 
-- | -- 
01 | Ana Paula Batista Gomes
02 | Carla Maria da Silva Ferreira Almeida
03 | Graciele Pereira do Nascimento 
04 | Janete Rodrigues da Silva 
05 | Maria José Batista de Moraes
06 | Alexandre de Brito Lins 
07 | Patrícia das Graças Souza 
08 | Lucélia C. das Chagas

**Comment by brunapinos** [comment]
* Levar um notebook com o ambiente configurado e um cabo de rede. @arthurTemporim

**Comment by rodmaia** [comment]
Atualizei a apresentação aqui: https://docs.google.com/presentation/d/1XsOjEKfiZYotFeSrrA4WH1Rza0ZSYc68YGDGXVf9Enk/edit#slide=id.g3ee581c395_0_215.
@brunapinos e @arthurTemporim revisem pra ver se eu não escrevi nada errado.
@ricardopoppi, @KahCosta e @palomacmamede vale à pena vocês darem uma olhada pra se familiarizarem com o conteúdo também.

**Comment by rodmaia** [comment]
Precisamos deixar o link do questionário nas máquinas que os participantes vão usar durante o refinamento.
https://goo.gl/forms/9csbMDUdcFcTVuNi1

**Comment by KahCosta** [comment]
Alguns tópicos discutidos durante o Stand Up que ocorreu ao final do Workshop:

1.  Reavaliar a mensagem inicial que a Taís apresenta no ínicio da conversa. 
     * Foi sugerido que talvez seja interessante que no momento em que o usuário abrir o chat ela já dê 
       boas vindas evitando assim que o usuário seja obrigado a cumprimentá-la.

2. Rever as interações da Taís com o usuário.
    * Durante o treinamento foi sugerido que as interação fossem mais curtas e objetivas uma vez que 
       os  proponentes são pessoas impaciêntes e que procuram por respostas de maneira rápida.

3. Entender o motivo pelo qual os participantes do treinamento não seguiram o roteiro apresentado 
    durante o Workshop.
    * Durante o treinamento foi observado que alguns participantes fizeram uso de um roteiro impresso 
      e individual.

4. Foi discutido a possibilidade da Taís sempre reforçar uma pergunta ao usuário com a finalidade de 
    fazer com que o usuário siga de forma correta o fluxo existente.
    * Durante o treinamento foi observado que os participantes ignoravam as interações e pulavam para 
      a pergunta que gostariam de saber sem se atentar as perguntas solicitadas pela Taís.

5. Durante o terinamento foi observado que alguns participantes estavam conferindo as respostas dadas pela Taís para averiguar se estava de acordo com o roteiro individual que alguns levaram.

6. Analisar chat da participante "Lucélia" para investigar as perguntas e o fluxo que estava tentando inserir na Taís.

7. Tentar entender como foi feita a preparação dos participantes para o treinamento.
    * Foi observado que os participantes estavam focados em analisar se a Taís estava ou não 
      funcionando corretamente e que não estavam cientes de que ainda encontra-se em fase de 
      treinamento.

8. Foi discutido a possibilidade de marcar uma nova rodada de treinamento porém desta vez tendo cuidado com a tecnologia,ou seja,implementando por exemplo botões que auxiliem o usuário a seguir o fluxo corretamente.

9. Implementar um meio de  checagem para que ao usuário perguntar algo a Taís, ela possa responder até que se atinja um certo nível de segurança e não responda mais.
    * Por exemplo ao usuário perguntar sobre determinado assunto ela vá perguntando ao usuário
      alguns pontos específicos até que tenha certeza sobre o que o usuário deseja realmente saber.
