### ISSUE TITLE
Workshop de entrega

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#577]
## Tarefas

- [x] Local para o evento (@ricardopoppi )
- [x] Infra para filmagem (@LeoSilvaGomes )
- [x] [Tutorial para deploy da Taís - issue 579](https://github.com/lappis-unb/tais/issues/579)
- [x] [Gitbook da BoilerPlaite - issue  578](https://github.com/lappis-unb/tais/issues/578) (referencia: https://tutorial.djangogirls.org/pt/)
- [x] Fazer flyer de divulgação (@LeoSilvaGomes )
- [x] Fazer vídeo de apresentação (@LeoSilvaGomes )
- [x] Fazer animação de bots se comunicando (@LeoSilvaGomes )
- [x] Convidar chatbotlabs (@ricardopoppi )
- [x] Convidar defensoria, email formalizando (@ricardopoppi )
- [x] VM’s para subir os chatbots (pelo menos 5)
- [x] Cadastrar no sympla no evento (nome, local, apresentações/cronograma/roteiro, ...) (@guilacerda )

### Apresentações

Todas as apresentações devem conter o slide no drive do lappis e devem passa pelo processo de revisão.

**Abertura**
- [ ] Projetando conversas inteligentes (30 minutos) (Carla)

---

**Trilha DevOps**

MANHÃ

- [ ] Arquitetura, O que é o Boilerplate, conceitual (15 minutos) (Temporim) 
- [ ] Subir ambiente de desenvolvimento (Baseado no README - make build, make first-run, etc) (30 minutos) (Pablo)
- [ ] Explicando a estrutura das pastas + logs (15 minutos) (Temporim)
- [x] BI (30 minutos) (Lacerda)

TARDE 

- [ ] Testes automatizados (30 minutos) (Leo)
- [ ] Apresentação do pipeline da Tais (30 minutos) (Moura)
- [ ] Workshop de deploy em produção - dojo (1 hora) (Miranda, Lacerda e Pablo)

---

**Trilha Curadoria**

MANHÃ
- [x] Roadmap da trilha (15 minutos) (Maia)
- [x] Seleção de conteúdo (15 minutos) (Maia)
- [x] Testando conteúdo sem chatbot (15 minutos (Bruna e Maia)
- [x] Elementos básicos de domínio (1 hora) (Bruna)

TARDE  
- [x] Apresentação da personalidade da Tais e exercício prático (30 minutos) (Paloma)
- [x] Apresentação de curadoria orientada a dados (UX) (30 minutos) (Paloma [técnico] - Maia [negócio])
- [x] Hands-on de curadoria orientada a dados (evoluindo a Taís) (1 hora) (Paloma)

---

- [ ] **16hs**: Mesa redonda (1 hora): **Chatbots além do feijão com arroz**
Participantes:
Carla Rocha (Prof Coordenadora do Lappis/UnB): O futuro das tecnologias livres para chatbots
Rodrigo Maia (Pesquisador Sênior Lappis/UnB): Uma visão estratégica de chatbots para serviços públicos
Joelson Vellozo (Diretor do Departamento de Experiência de Usuário/SGD): Tendências de unificação de canais no atendimento aos cidadãos
João Sigora (GNova/ENAP): A estratégia de expansão da rede Inovagov
Rogers Pereira (Chatbot Labs): Lei Geral de Proteção de Dados no contexto de chatbots

**Comment by RochaCarla** [comment]
Ps: as apresentações devem estar prontas até a segunda feira da semana do evento para ser revisada por alguém externo do time

**Comment by LeoSilvaGomes-zz** [comment]
- Local para o evento (@ricardopoppi )

Foi confirmado a reserva da sala 202 na ENAP, Campus Asa Sul. Mediante isso, iremos precisar dos nossos equipamentos de gravação, que deveram está preparados para o workshop essa semana.

**Comment by palomacmamede** [comment]
[Personalidade da Tais](https://docs.google.com/presentation/d/1wnEPuhiukD_UUcYz8I9dGD0KaDSGqUgDKk3bGboCCv4/edit?usp=sharing)

**Comment by ricardopoppi** [comment]
@RochaCarla @rodmaia2099 @brunapinos @palomacmamede @arthurTemporim @pablodiegoss @guilacerda  @LeoSilvaGomes @MatheusMiranda atualizei o corpo da issue com todas as atividades e o tempo. Algumas atividades tiveram pequenos ajustes de tempo e algumas do inicio da tarde passaram pro final da manhã (nas duas trilhas). Observem isso agora na reta final da preparação de vocês, p fv.

**Comment by guilacerda** [comment]
@ricardopoppi pensamos em algumas modificações para a trilha devops:

* O Miranda não vai precisar de 1 hora e meia pra fazer as duas últimas apresentações, sendo assim, decidimos reservar uma hora e juntar as apresentações em uma só.

* Com isso, seria possível descer a apresentação do @LeoSilvaGomes para a tarde e deixar um tempo maior pra introdução do evento e também uma margem de erro pra qualquer atraso.

* Aumentar o tempo do Indie bot pra 20/30 minutos

**Comment by ricardopoppi** [comment]
Pessoal, completem com os exercícios práticos que vcs vão propor:

Trilha DevOps

Subir ambiente de desenvolvimento (Baseado no README - make build, make first-run, etc) (30 minutos) (Pablo)
Exercício prático: @pablodiegoss , sugestao: formamos um grupo para cada VM e eles simulam subir o ambiente de dev nas VMs

BI (30 minutos) (Lacerda)
Exercício prático: @guilacerda o que podemos propor pra exercício prático aqui?

Testes automatizados (30 minutos) (Leo)
Exercício prático: @LeoSilvaGomes  o que podemos propor de exercício prático aqui?

Workshop de deploy em produção - dojo (1 hora) (Miranda, Lacerda e Pablo)
Exercício prático: @MatheusMiranda  @guilacerda @pablodiegoss formamos um grupo por VM com a missão de subirem o ambiente de produção, certo?


Trilha Curadoria

Elementos básicos de domínio (1 hora) (Bruna)
Exercício prático: @brunapinos @rodmaia2099 Dinâmica de como testar conteúdo de bot sem ter bot (vai ser isso né?)

Apresentação da personalidade da Tais e exercício prático (30 minutos) (Paloma)
Exercício prático: @palomacmamede como pode ser esse exercicio prático?

Hands-on de curadoria orientada a dados (evoluindo a Taís) (1 hora) (Paloma)
Exercício prático: @palomacmamede como pode ser esse exercicio prático?

**Comment by pablodiegoss** [comment]
@ricardopoppi Subir ambiente de desenvolvimento (Baseado no README - make build, make first-run, etc) (30 minutos) (Pablo)

Exercício prático: Formamos um grupo para cada VM e eles simulam subir o ambiente de dev nas VMs. Utilizar os comandos básicos:
make build-requirements ( Instalar novas dependências )
make train ( Criar as modelos a partir dos insumos do bot )
make build-bot (reconstrói o bot)
make run-console ( Testar o bot no console )
make run-api (Habilitar o modo API apenas ) 
make run-rocketchat ( Executar o bot utilizando o Rocket.chat)

**Comment by guilacerda** [comment]
Na minha programação de BI, eu vou passar um pouco na teoria, explicar algumas métricas que levantamos como essenciais para chatbot. Vou falar também o que é o ElasticSearch e o Kibana. E ao final é uma prática elaborando 3 visualizações no próprio kibana, passando por alguns elementos básicos na interface. Como teremos algumas máquinas disponíveis, o pessoal vai poder elaborar no próprio kibana as visualizações

**Comment by palomacmamede** [comment]
Na minha apresentação sobre a Personalidade da Tais, vou falar daquela parte do mbti, a persona que criamos (gênero, cargo, objetivo, etc), depois vou pontuar com partes do guia de conversação, incluindo como desvirtuar a personalidade da Tais, e por fim vou passar um exercício para que cada um escreva duas utters tentando implementar a personalidade da Tais.

Na minha apresentação sobre monitoramento, vou falar do passo a passo de análise, kibana, rocketchat, da classificação de bugs, mostrando exemplos de cada um deles, depois vou mostrar como "quebrar a tais", usando nosso primeiro caso de denúncia, em seguida um outro caso que tive dificuldades que é o de readequação, um ou outro bug e como eu o resolveria, e por fim na parte de Hands ON eles vão fazer o monitoramento do bot que eles criaram.

**Comment by ricardopoppi** [comment]
> e por fim na parte de Hands ON eles vão fazer o monitoramento do bot que eles criaram

@palomacmamede talvez aqui pensar num plano B porque eles vão trabalhar todos na Tais, então não haverá um outro tipo de bot. Sugiro que nesse hands on eles possam executar uma tarefa simples de monitoramento (minimalista mesmo) só que dentro da base de conhecimento da Taís

**Comment by guilacerda** [comment]
As duas apresentações do @arthurTemporim 

1) Apresentação da história do boilerplate, contextualização de chatbots e o objetivo do projeto pela visão técnica. O que um desenvolvedor deve saber para construir um chatbot Rasa

2) Explicando a nova versão do Rasa e boilerplate, vantagens do uso do projeto, como contribuir, e oq você é capaz de fazer usando o boilerplate. Todo o fluxo de desenvolvimento, manutenção e evolução de um chatbot Rasa. Show me the code!

**Comment by guilacerda** [comment]
O workshop do @MatheusMiranda  vai abordar o seguinte assunto:

Processo de deploy do bot, desde a inicialização dos serviços até a configuração de um certificado (SSL) e disponibilização da janela de conversa do bot em uma página web.

**Comment by victorcmoura** [comment]
Na apresentação sobre o pipeline da Taís, serão comentados os seguintes tópicos:
- Introdução às ferramentas: Docker + GitLabCI
    - Paradigma do CI (baseado em runners que executam imagens Docker)
    - Organização em Stages e Jobs (jobs do mesmo stage são executados em paralelo)
- Pipeline básico da Taís:
    - Overview da versão pré otimização
    - Identificação de gargalos
    - Otimização
    - Pipeline final

**Comment by rodmaia** [comment]
Na sessão **Seleção de conteúdo** vai ter um exercício rápido de rascunho de perguntas e respostas para bot, em preparação para a sessão da Bruna.

**Testando conteúdo sem chatbot** é basicamente 100% exercício de testar conteúdos.

Em **Elementos básicos de domínio** vai ter prática no BotFlow, passar o conteúdo rascunhado e preparar para as sessões da Paloma à tarde.
