### ISSUE TITLE
Migrar gitpage da tais para o Boilerplate

### ISSUE THREAD

**Issue by RochaCarla** [lablivre-unb/tais#578]
Migrar o gitpage da Tais para o Boilerplate

**Tarefas**

- [x] Copiar todo o conteúdo de tutoriais, documentação da Tais para o boilerplate (o conteúdo genérico)

- [x] Inserir texto no gitpage da Tais indicado que a evolução do conteúdo será disponível no boilerplate

- [x] subir o gitbook do boilerplate, seguindo um paramêtro de tutorial

**Comment by RochaCarla** [comment]
https://github.com/DjangoGirls/tutorial/tree/master/pt

**Comment by LeoSilvaGomes-zz** [comment]
Foi migrado os tutoriais que estavam no gitpage da tais para um [gitbook](https://docs.rasaboilerplate.lappis.rocks/v/create_gitbook/) no boilerplate, onde será gerado novas versões dos tutoriais.
