### ISSUE TITLE
Verificar históricos de conversa

### ISSUE THREAD

**Issue by brunapinos** [lablivre-unb/tais#59]
* [ ] Verificar como recuperar as conversas dos usuários
* [ ] Encontrar a melhor forma de divisão de trabalho (Ex.: quantidade de pessoas, por tópicos)

**Comment by gabibguedes** [comment]
Link para as rotas da api do rocket chat: https://rocket.chat/docs/developer-guides/rest-api/

**Comment by diegodorgam** [comment]
Tem várias formas de pegar o histórico das conversas, dependendo do propósito, do que quiser fazer com o histórico, da pra sugerir um método melhor.
Da pra pegar o histórico pela API REST, pela API RealTime (DDP) e também da pra configurar os webhooks do livechat pra postar o payload das conversas em um determinado endpoint, além é claro de extrair do banco de dados com o mongoexport.

**Comment by MatheusMiranda** [comment]
Implementamos uma solução mais simples, utilizando o call method 'loadHistory' da API Real Time do RocketChat. O propósito era fazer a análise manual dos arquivos de conversas.
Esta solução será descartada e implementaremos uma abordagem mais madura de Analytics. Focaremos em evoluir o connector do Rasa Core para o RocketChat, para gerar dados de forma mais estruturada.
