### ISSUE TITLE
Analisar o Histórico de Conversa

### ISSUE THREAD

**Issue by brunapinos** [lablivre-unb/tais#60]
* [x] Achar melhor disposição dos resultados extraídos (Ex.: planilha)
* [x] Enumerar os pontos de interação da Tais
* [x] Fazer análise do histórico de conversa
* [x] Levantar sinônimos, frases e erros ortográficos comuns 
* [ ] Levantar erros de fluxo 
* [ ] O resultado deve ir para issue #87

**Comment by MatheusFaria** [comment]
Seria mais interessante colocar o resultado na wiki deste repositório ou no Ecossistemas?

**Comment by rodmaia** [comment]
Pessoal, qual o endereço da planilha de compilação para a gente acompanhar os resultados?

**Comment by KahCosta** [comment]
[Planilha](https://docs.google.com/spreadsheets/d/1hb6chITZdLfqKfccMHMlTHHJ6645smdouFg72dwULTM/edit?usp=sharing)
Endereço da planilha @rodmaia2099

**Comment by palomacmamede** [comment]
@KahCosta  agora vai <3

**Comment by rodmaia** [comment]
No momento precisamos identificar três coisas:

1. Formas de perguntar diferentes (sinônimos) para tópicos que já respondemos.
2. Dúvidas que a Taís foi incapaz de responder (novos tópicos).
3. Qual a intenção das pessoas no momento em que a Taís falhou (quebrou a conversa, terminou inesperadamente, respondeu algo nada a ver, etc). Se a intenção foi legítima, ou seja, se a pessoa prestou atenção na resposta da Taís e fez uma pergunta válida, aí precisamos documentar essa intenção.

@KahCosta @arthurTemporim @palomacmamede faz sentido?

**Comment by palomacmamede** [comment]
@rodmaia2099, acredito que todos esses tópicos que você listou são essenciais para a análise.
