### ISSUE TITLE
Coletar nome do Usuário

### ISSUE THREAD

**Issue by palomacmamede** [lablivre-unb/tais#62]
A interação inicial poderia ser feita da seguinte forma:

'Olá, como você se chama? ’

[interação]
 
‘Prazer em te conhecer, ____________. Fico feliz em te receber aqui! ’
‘Eu sou a Taís, assistente virtual do Minc.’  
‘O meu objetivo é te ajudar a concretizar o seu projeto.’ 
‘Posso esclarecer dúvidas sobre a lei Rouanet ou solucionar problemas de proposta e projeto.’ 
'Você prefere conversar sobre criação e andamento de projetos, ou '
'prefere falar mais sobre a Lei Rouanet?'

**Comment by palomacmamede** [comment]
**Por que é importante que a Taís saiba o nome do usuário?**

"Recalling and integrating your client’s name into a conversation – not to be overused – is very important for a few reasons. [...] **Names are unique identifiers**. Dale Carnegie said it best, “A person’s name is to that person, the sweetest, most important sound in any language.” According to the brain research mentioned earlier, hearing our names lights up different parts of our brand that no other words do. Our names prompt specific and unique responses in our minds that are powerful associations for anyone to use. Everyone responds to being known by name."

link: https://www.naturaltraining.com/blog/2016/03/11/how-important-is-it-to-use-your-customers-name/

**Comment by rodmaia** [comment]
O princípio é muito bom. Personalizar a conversa pode ajudar a pessoa a ficar mais à vontade. Por outro lado, já começar a conversa pedindo o nome da pessoa pode parecer um pouco intimidador para certas pessoas. 

Pontos para reflexão:

* Será que não teríamos um momento mais oportuno para perguntar o nome? 
* Se tivermos o nome, precisamos usá-lo ao longo de toda a conversa. Não o tempo todo, mas de vez em quando ao longo do fluxo. E aí precisamos prever o caso de não ter o nome nesses mesmos pontos. Perguntar o nome apenas para usar "bem-vinda fulana" pode ser um custo muito alto para pouco valor entregue.

Sobre o conteúdo:

* ‘Prazer em te conhecer, ____________. Fico feliz em te receber aqui! ’ Seria bom testarmos a reação das pessoas em relação a esse tipo de tom/formalidade. Algumas pessoas podem se sentir reconfortadas. Já outras podem achar muito próximo com uma interação no mundo concreto, como se a Taís tivesse convidado a vizinha pra tomar um café. É uma linha tênue, vamos sempre correr riscos de uma forma ou de outra.
*  ‘O meu objetivo é te ajudar a concretizar o seu projeto.’ Cuidado com as expectativas que criamos. Quando fizemos os testes com produtores culturais e perguntamos o que mais gostariam que a Taís fizesse, invariavelmente a resposta era "captar dinheiro". Era uma resposta de brincadeira, mas demonstra o que anda no subconsciente delas. Prometer concretizar o projeto pode ter um significado diferente para essas pessoas.
* ‘Posso esclarecer dúvidas sobre a lei Rouanet ou solucionar problemas de proposta e projeto.’ 'Você prefere conversar sobre criação e andamento de projetos, ou prefere falar mais sobre a Lei Rouanet?' Isso pra mim é um dilema. Por um lado acho redundante. Por outro sei que se a gente usar apenas "Sobre o que você quer conversar?" as pessoas vão querer falar sobre qualquer outro assunto. Será que tem um meio termo?

**Comment by palomacmamede** [comment]
@rodmaia2099 as suas reflexões foram bem pontuais, achei ótimo. Vou pensar sobre esses pontos e mais tarde proponho soluções.

**Comment by palomacmamede** [comment]
Sobre um momento mais oportuno para se perguntar o nome do usuário, eu acho que o único momento que valeria a pena seria mesmo nessa "etapa de apresentação". No caso, eu defendo que seria interessante testar esse nível de intimidade com o usuário, justamente pela hipótese de personalidade que eu criei da Taís, mas se vocês acharem mais interessante deixar a conversa mais profissional mesmo, podemos tentar estabelecer um nível de intimidade com o usuário bem menos explícito. Sendo assim, o "Prazer em te conhecer", seria nessa ideia mesmo de criar um vínculo com o proponente, todavia existe sim um impacto que pode gerar um contraponto negativo em alguns usuários. A ideia era essa mesmo de fazer com que a pessoa se sentisse em casa hahahaha (:

**Comment by palomacmamede** [comment]
**Hipótese mais profissional:** 

'Olá, é um prazer te receber aqui! '
‘Eu sou a Taís, assistente virtual do Minc.’  
‘_O meu objetivo é te ajudar a sanar dúvidas sobre como concretizar o seu projeto.’_

**Comment by diegodorgam** [comment]
Sobre o nome do usuário, se o bot estiver funcionando dentro de algum ambiente com essas informações já, é possível passar esses dados para o livechat [nome,e-mail, customFields...] e pegar pelo bot por meio da API.
Caso ele esteja falando dentro do SALIC por exemplo, ele/ela/isto poderia apenas confirmar o nome e e-mail do usuário.
