### ISSUE TITLE
Refatorar Estrutura do Fluxo

### ISSUE THREAD

**Issue by brunapinos** [lablivre-unb/tais#64]
- [x] Modificar a estrutura de actions e templates (domain.yml e actions/)
- [X] Conseguir mandar várias mensagens no mesmo utter

**Comment by diegodorgam** [comment]
Acabei de verificar, o envio de multiplas linhas no template ainda não é suportado, será necessário fazer uma pequena alteração no [dispatcher.py](https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/dispatcher.py) pra ele reconhecer o envio de multiplas mensagens de texto.

**Comment by MatheusFaria** [comment]
@brunapinos @KahCosta Deem uma olhada no `DomainsMerger` do [mr bot](https://github.com/mrbot-ai/rasa-addons/blob/master/tests/test_domain_merger.py) para evitar que o nosso arquivo de `domain.yml` seja gigante

**Comment by MatheusFaria** [comment]
Galera, o padrão para enviar várias mensagens é esse aqui:
```yaml
templates: 
  utter_1: 
    - text: | 
        Oi 1
 
        Oi 2

        Oi 3
```

Precisa ter  o `|` e depois tem que ter uma linha em branco entre cada uma das mensagens

**Comment by arthurTemporim** [comment]
Criamos um issue sobre o `DomainMerger`. #77
