### ISSUE TITLE
Criar grupo de discussão para beta testers

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#67]
- [x] Criar grupo
- [x] Testar processo de convidar/adicionar pessoas.
- [ ] Documentar processo para convidar/adicionar pessoas.
- [ ] Adicionar a conta do Lappis e todos os seniores do projeto como administradores da lista.

**Comment by MatheusFaria** [comment]
@palomacmamede @rodmaia2099 
- [ ] Criar mensagem de Boas Vindas
- [ ] Criar mensagem de update "Oi! Temos uma versão novinha para você testar, que tem: X, Y e Z"

**Comment by palomacmamede** [comment]
Bacana! Já vou começar a pensar sobre isso hoje.

**Comment by rodmaia** [comment]
@arthurTemporim @brunapinos Como ficou a criação do grupo? Precisamos do endereço para acessar e documentar a senha no repositório da infra.

**Comment by palomacmamede** [comment]
Galera, quais foram as mudanças que ocorreram da versão antiga pra essa nova?

**Comment by palomacmamede** [comment]
Achei essa explicação interessante, sobre chatbot vs assistente virtual. 

[O que são chatbots e assistentes virtuais?](https://faledireto.com.br/afinal-o-que-s%C3%A3o-chatbots-e-assistentes-virtuais-be773b439fe7)

**Comment by palomacmamede** [comment]
PROPOSTA DE TEXTO PARA APRESENTAÇÃO DA TAIS

Seja bem-vindo! 
Eu sou a Taís, Assistente Virtual do MinC, eu sou uma Inteligência Artificial criada por um programa de computador. Fui desenvolvida com o objetivo de ajudar vocês a sanarem dúvidas sobre a Lei Rouanet. Eu sou fruto de uma parceria entre o  LAPPIS (Laboratório Avançado de Produção Pesquisa e Inovação em Software), um Laboratório de Software  Livre da Universidade de Brasília campus Gama e o Ministério da Cultura. Meu nome é uma sigla que significa Tecnologia de Aprendizado Interativo Salic, isso quer dizer que eu estou aprendendo vocabulário humano para ser mais eficiente na nossa comunicação. A cada conversa eu aprendo mais e me torno mais eficiente para te ajudar.

**Comment by palomacmamede** [comment]
PROPOSTA DE APRESENTAÇÃO DA NOVA VERSÃO
Agora estou em uma nova versão, sendo assim eu posso te responder sobre o significado das siglas dos estados do seu processo, consigo sanar dúvidas sobre as etapas do seu projeto (inscrição, andamento, execução), e algumas curiosidades como “O que é a Lei Rouanet?”, “O que é o Salic?”, “O que é a Sefic?”, “O papel do MinC na Lei rouanet”, “Quanto projetos já foram incentivados pela lei Rouanet”, entre outras. Se tiver alguma dúvida sobre a Lei Rouanet, não hesite, pergunte! Estou aqui para te auxiliar com a sua proposta.

**Comment by rodmaia2099** [comment]
Acho que acabamos misturando issues diferentes. O conteúdo da página de abertura está mapeado em #90. Meu feedback para a @palomacmamede é de que essa página deve ser escrita na voz do Lappis e não na voz da Taís. Além de ser um tom um pouco mais sério do que o tom super-amigável da Taís. Vale à pena rever a issue #90.

**Comment by rodmaia** [comment]
@arthurTemporim te trouxe de volta pra issue porque acho que misturamos as coisas. Dá uma olhada nas tasks que eu adicionei à descrição.
Documenta aqui também o endereço da lista, pfv. Já temos nomes para convidar.
Ah, dá um assign em quem tiver te ajudando com isso.

**Comment by palomacmamede** [comment]
PROPOSTA DE APRESENTAÇÃO DA NOVA VERSÃO EM TERCEIRA PESSOA

A nova versão da Taís está pronta para ser testada, esta versão permite que ela responda sobre as siglas dos estados do seu processo (ex. A12, A20), dúvidas sobre o seu projeto (inscrição, andamento, execução, elegibilidades, benefícios), e algumas curiosidades como “O que é a lei Rouanet?”, “O que é o Salic?”, “O que é a Sefic?”, “O papel do MinC na lei Rouanet”, “Quanto projetos já foram incentivados pela lei Rouanet”, entre outras. Se tiver alguma dúvida sobre a lei Rouanet, não hesite, pergunte para a Taís.

**Comment by palomacmamede** [comment]
@rodmaia2099 escrevi duas hipóteses de texto em terceira pessoa, que acho que fica mais homogêneo. Aceito feedback para que possamos ir adequando o texto até ele ficar na estrutura adequada.

**Comment by arthurTemporim** [comment]
O grupo está criado desde segunda-feira [aqui](https://groups.google.com/forum/#!managemembers/tais-assistente-virtual), já fiz os testes necessários e configurei as permissões de visualização e edição.

Sobre `Documentar processo para convidar/adicionar pessoas.` fica no menu lateral do grupo essa opção não vejo necessidade de documentar isso, vcs acham que é relevante?

Tem que adicionar as informações que o @MatheusFaria comentou [aqui](https://github.com/lappis-unb/rouana/issues/67#issuecomment-420027964), @rodmaia2099 ou @palomacmamede pode fazer isso, por favor? Estou adicionando todos os outros envolvidos.

**Comment by rodmaia** [comment]
O grupo de discussão vai ser colocado em pausa por enquanto, pois obriga que as pessoas tenham contas do Gmail para acessar um grupo privado. Como temos prioridades maiores no momento, vamos enviar e-mails simples por enquanto.

**Comment by arthurTemporim** [comment]
Foi criado a conta tais.betateste@gmail.com para envio das mensagens.
