### ISSUE TITLE
Avatar, ícone, fotinha da Taís

### ISSUE THREAD

**Issue by MatheusFaria** [lablivre-unb/tais#73]
Criar foto para representar a assistente virtual, pode talvez refletir a personalidade (@palomacmamede )

**Comment by MatheusFaria** [comment]
@peterlima @rodmaia2099  talvez algum bolsista de design possa puxar essa issue?
@MatheusFaria acredito que um dos designers poderá puxar na próxima sprint.

**Comment by rodmaia** [comment]
Acho que a gente pode só trocar o avatar por enquanto e pensar numa foto quando a personalidade estiver definida.
@peterlima tem os fontes daquele avatar que tu fez?

**Comment by rodmaia** [comment]
Novo avatar da Taís:

![avatar](https://user-images.githubusercontent.com/13748586/45428094-d9b95c80-b676-11e8-92a6-dd2c7a27fbcc.jpg)

**Comment by rodmaia** [comment]
Aguardando o review do PR para poder testar o avatar na homologação
