### ISSUE TITLE
Criar catálogo do LAPPIS para o rancher

### ISSUE THREAD

**Issue by MatheusMiranda** [lablivre-unb/tais#74]
* [ ] Criar Rancher Compose para TAIS. Tomar como referência a configuração do EJ (https://github.com/ejplatform/ej-rancher-catalog). 
* [ ] Adicionar as configurações da TAIS e do EJ em um catálogo do LAPPIS, e importar no Rancher.

**Comment by MatheusFaria** [comment]
Mover para o time de devops
@joenio @arthurbdiniz @guilacerda

**Comment by joenio** [comment]
issue no devops: https://gitlab.com/lappis-unb/athena/issues/37
