### ISSUE TITLE
Deixar domain.yml enxuta

### ISSUE THREAD

**Issue by arthurTemporim** [lablivre-unb/tais#77]
Estudar `DomainsMerger` para evitar que o nosso arquivo de `domain.yml` seja gigante.

- [ ] Criar requirements de dev com o pacote [rasa-addons](https://github.com/mrbot-ai/rasa-addons)
- [ ] Adicionar no `train.py` o passo de juntar os domains semelhante a esse script: [mr bot](https://github.com/mrbot-ai/rasa-addons/blob/master/tests/test_domain_merger.py)
- [ ] Separar os arquivos de domain
- [ ] Criar docker de `dev`

**Critérios de Aceitação**

- [ ] Rodar a Taís com os arquivos separados sem warnings e sem erros

**Comment by arthurTemporim** [comment]
Criei esse tópico no fórum do RASA acomapanhem o andamento: [fórum](https://forum.rasa.com/t/reduce-domain-content/1576?u=arthurtemporim)

**Comment by gabibguedes** [comment]
Possivelmente a parte onde carrega o dispatcher no agent será na função run do train.py

**Comment by arthurTemporim** [comment]
Deprecated
