### ISSUE TITLE
Extração e enriquecimento de dados para analytics

### ISSUE THREAD

**Issue by MatheusFaria** [lablivre-unb/tais#81]
Pegar as informações coletadas na Rocket.Chat e inserir e preparar esses dados para o elastic search.

**Tarefas**

- [ ] Extrair as conversas do histórico do Rocket.Chat
- [ ] Enriquecer os dados (NLU, entities, confidence)
    - Extrair as meta informações, por exemplo: Valor de confiança, entidades, posição no fluxo / história

**Critérios de Aceitação**
- [ ] Gerar os dados de forma que o elastic search seja capaz de "ler" (Json) por mensagem

**Comment by arthurTemporim** [comment]
Verificar a conversão de `timestamp` do mongo para elasticsearch
