### ISSUE TITLE
Utilizar Nginx para autenticação

### ISSUE THREAD

**Issue by MatheusFaria** [lablivre-unb/tais#83]
- [x] configurar nginx para a landing page
- [x] fazer autenticação via nginx
- [x] configurar arquivo de autenticação no `Dockerfile`

**Comment by gabibguedes** [comment]
Achei esse [tutorial](https://www.digitalocean.com/community/tutorials/how-to-set-up-basic-http-authentication-with-nginx-on-ubuntu-14-04) da digital ocean q explica como fazer o login com nginx

**Comment by gabibguedes** [comment]
[repositorio](https://github.com/beevelop/docker-nginx-basic-auth) para rodar com docker

**Comment by gabibguedes** [comment]
para gerar o login pra landing page, primeiro precisa subir o docker da landing page e dps dar o docker run:
```
docker run -d \
           -e HTPASSWD='gabi:$apr1$C77jPBTv$nOcETOTbZ8Z5Bybd6AJTI1' \
           -e FORWARD_PORT=8000 \
           --link tais_landing-page_1:web -it --net tais_default -p 80:80 \
           --name auth \
           beevelop/nginx-basic-auth
```

**Comment by arthurTemporim** [comment]
Obrigado pela sua colaboração.
