### ISSUE TITLE
Revisar PR de renomear o repositório de Rouana para Taís

### ISSUE THREAD

**Issue by MatheusFaria** [lablivre-unb/tais#84]
O PR gera muitos conflitos, vai precisar separar um dia para fazer e não quebrar o ambiente de todos

- [ ] Trocar no rancher
- [ ] Arrumar o mirror do gitlab
- [ ] Fazer rebase de branches e PRs abertos

**Comment by rodmaia** [comment]
Decisão: criar novo repositório para a versão "nova" da Taís e preparar para marcar este repositório como *deprecated* no futuro.

**Comment by MatheusFaria** [comment]
Taís foi movida para outro [repositório](https://github.com/lappis-unb/tais), e a branch foi removida.
