### ISSUE TITLE
Evitar que a Taís encerre a conversa

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#86]
Dependendo do ponto em que a pessoa chega no fluxo, a Taís fala que não conhece o assunto e encerra a conversa.

Precisamos:
- [x] Evitar que a Taís encerre a conversa. 
- [x] Fazer com que a Taís pergunte se a pessoa tem dúvidas ou quer saber mais alguma coisa.
- [ ] Estudar a possibilidade do Rocket Chat encerrar a conversa por inatividade

--------

**Critérios de aceitação**

- [x] A Taís não encerra a conversa sem a permissão da pessoa.
- [x] A pessoa consegue recomeçar o processo de tirar dúvidas quando chega ao final do processo.
- [ ] Esse comportamento pode ser testado no ambiente de desenvolvimento

**Comment by palomacmamede** [comment]
Sobre a inatividade, ela poderia deixar uma mensagem do tipo " vc ainda está aí? " e se a pessoa não responder ela pode encerrar o bate-papo depois de algum tempo.

**Comment by rodmaia** [comment]
Não vamos trabalhar o encerramento por inatividade por enquanto.

**Comment by rodmaia** [comment]
Diferenças mapeadas em #116
