### ISSUE TITLE
Enviar alterações dos textos da Refactor para Master

### ISSUE THREAD

**Issue by MatheusFaria** [lablivre-unb/tais#87]
Algumas alterações de texto da Refactor já podem ser colocadas na master. Todas as melhorias de texto feitas pela @palomacmamede podem ser encomporadas na estrutura antiga.

Também devemos incluir mudanças de conteúdo identificadas #60.

Alterações de fluxo ou estrutura irão no PR da Refactor

**Comment by arthurTemporim** [comment]
O esforço de colocar essa issue em produção é grande e não vai ser reaproveitado por causa da refatoração.
