### ISSUE TITLE
Preparar página de abertura para o beta test

### ISSUE THREAD

**Issue by rodmaia** [lablivre-unb/tais#90]
Mostrar os seguintes conteúdos na página que mostra a janela do Live Chat:

- [x] Resumo do que a Taís consegue responder
- [ ] ~Resumo do que a Taís não é capaz de responder~
- [x] Changelog
- [ ] ~Marca do Lappis~
- [x] Informação sobre a construção em parceria Lappis + MinC

**Comment by palomacmamede** [comment]
Vou começar a analisar isso (:

**Comment by palomacmamede** [comment]
TÓPICOS QUE A TAÍS CONSEGUE RESPONDER

O que é a Tais
O que é a lei Rouanet? 
Qual o papel do MinC na lei Rouanet?
O que é a Sefic?
O que é um projeto?
O que é uma proposta?
O que é um proponente?
O que é a etapa preenchimento?
O que é a etapa admissibilidade?
O que é a etapa aprovação?
O que é a etapa execução? 
O que é a etapa prestação de contas?
O que é Salic?
O que são as vinculadas?
Dúvida sobre captação de verba.
Como se cadastrar no Salic?
Como submeter um projeto?
Como inscrever um proponente?

ESTADOS DE PROJETO:

  A12
  A14
  A20
  A23
  B01
  B14
  A13
  A16
  A17
  A42
  B11
  B20
  C09
  C10
  C20
  C26
  C30
  D03
  D14
  D20
  D25
  D27
  E25
  E62
  E66
  E20
  E27
  E30
  E68
  E77
  L03
  L05
  L08
  L10
  L11
  D22
  D28
  D29
  E10
  E11
  E12
  E13
  E15
  E16
  E23
  E24
  E36
  E59
  E63
  E64
  E65
  E75
  E79
  E80
  E81
  E60
  E72
  E50
  L09
  D38
  E22
  E73
  E78
  E47
  L06

 
CURIOSIDADES:

Falar Sobre Projetos
Quantidade Projetos
Benefícios para quem incentiva projetos culturais
Quem submeter um projeto? 
De onde vem o dinheiro usado na lei Rouanet?
Como posso denunciar um projeto?
Quais empresas podem se beneficiar ao apoiar projetos culturais?
Os familiares podem incentivar projetos?
Posso receber incentivo de parentes?
Política de redução dos Impostos para patrocinadores.

DÚVIDAS SOBRE PREENCHIMENTO 

Como preencher:
Campo Custo Auditoria
Vinculo De Propostas
Valor Ingresso
Vinculo CPF Proposta
Agência Bancaria

EVENTUAIS ERROS DO SALIC

Planilha desaparecida
Erro de salvamento
Recuperação de senha
Vínculo: Cpf/Cnpj
Como encontrar uma Proposta cadastrada

DÚVIDAS SOBRE FLUXO DE SUBMISSÃO DE PROJETOS

Captação de recursos
Reativação de proposta
Cadastro proponente

DÚVIDAS SOBRE PRAZO

Envio Cnae
Desistir do Recurso

**Comment by palomacmamede** [comment]
@rodmaia2099  especificando a Taís consegue responder todos esses tópicos listados acima.

**Comment by palomacmamede** [comment]
Sobre os tópicos que estão listados nas Utters e que a Taís não consegue responder: sobre um projeto que está em Execução ou em Prestação de Contas.

**Comment by palomacmamede** [comment]
ANÁLISE DE ASSUNTOS QUE A TAÍS NÃO SABE RESPONDER COM BASE NA PLANILHA
-  Custos
- Tempo de avaliação inicial
- Dúvidas relacionadas ao Cnic
- Valor de dedução do incentivador

**Comment by palomacmamede** [comment]
[Textos de Apresentação/boa vindas da Taís](https://docs.google.com/document/d/1B7oocFa0RcaVPUVQUT1oJEjgks9sJTRBGjTNu3CT1Kw/edit?usp=sharing)

**Comment by rodmaia** [comment]
Adicionei o conteúdo à página e fiz um layout que facilita a leitura mesmo se a janela de chat estiver aberta.
Preferi não incluir o escopo negativo da Taís nem a marca do Lappis para não sobrecarregar ainda mais a página.
O Changelog está pronto, mas comentado. Assim que tiver novidades de fato, basta descomentar e atualizar.

**Comment by rodmaia** [comment]
@palomacmamede acebei mudando os textos por conta do feedback que tivemos do MinC durante a reunião estratégica. Se você tiver tempo, pode dar uma revisada até segunda? Melhor olhar direto nos arquivos do PR #99.

**Comment by palomacmamede** [comment]
@rodmaia2099 posso sim. Hoje a noite dou uma olhada (:

**Comment by palomacmamede** [comment]
Os textos foram devidamente revisados.
